//! Differential tests against the R `survival` reference fixtures in
//! `test/r/fixtures/*.json` (generated by `test/r/generate_fixtures.R`, see
//! `test/r/README.md`).
//!
//! Only kernels reachable without Python are exercised here: the Kaplan-Meier
//! engine (`surv_analysis::compute_survfitkm`), `survdiff2`,
//! `regression::coxph::coxph_fit` and its residual methods,
//! `regression::parametric_survival::survreg`, `concordance::concordance_index`
//! and a few `data_prep` helpers.  The Python suite
//! (`python/tests/test_r_fixtures.py`) covers the remaining topics.
//!
//! Each topic is one `#[test]` that walks every fixture case and aspect it can
//! express.  Failures of cases listed in [`KNOWN_FAILURES`] are reported but
//! tolerated; a listed case that passes fails the test with a message asking
//! for its removal, so the list is a strict burndown.
#![cfg(test)]

use crate::regression::coxph::{CoxPHFit, coxph_fit};
use crate::regression::parametric_survival::survreg;
use crate::surv_analysis::logrank_components::survdiff2;
use crate::surv_analysis::survfitkm_module::compute_survfitkm_with_timefix;
use crate::surv_analysis::{KaplanMeierConfig, SurvFitKMOutput};
use serde_json::Value;
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

/// Relative tolerance for coefficients, curves, residuals and linear predictors.
/// Vectors and matrices also get an absolute floor of `rtol * max|expected|`
/// (see [`assert_vec`]).
const RTOL_COEF: f64 = 1e-8;
/// Relative tolerance for variances, standard errors, test statistics, p-values.
const RTOL_VAR: f64 = 1e-6;

/// Burndown list: `topic/case/aspect` (or `topic/case` for every aspect of a
/// case) -> reason.  A listed entry that passes fails the run.
const KNOWN_FAILURES: &[(&str, &str)] = &[
    (
        "concordance/aml_x_numeric",
        "missing feature: harness: term as.numeric(x)",
    ),
    (
        "concordance/cgd_counting_age_cluster",
        "missing feature: harness: several terms or strata",
    ),
    (
        "concordance/cgd_counting_age_id",
        "mismatch: concordance: 0.426 != 0.42669",
    ),
    (
        "concordance/coxph_survreg_fits",
        "missing feature: concordance of fitted models",
    ),
    (
        "concordance/heart_counting_age",
        "mismatch: concordance: 0.57577 != 0.57546",
    ),
    (
        "concordance/lung_age",
        "mismatch: concordance: 0.4498 != 0.44976",
    ),
    (
        "concordance/lung_age_cluster_inst",
        "missing feature: harness: several terms or strata",
    ),
    (
        "concordance/lung_age_influence",
        "missing feature: concordance_index has no influence output",
    ),
    (
        "concordance/lung_age_ph_karno",
        "missing feature: harness: several terms or strata",
    ),
    (
        "concordance/lung_age_ranks",
        "missing feature: concordance_index has no ranks output",
    ),
    (
        "concordance/lung_age_reverse",
        "mismatch: concordance: 0.5502 != 0.55024",
    ),
    (
        "concordance/lung_age_strata_sex",
        "missing feature: harness: several terms or strata",
    ),
    (
        "concordance/lung_age_timewt_I",
        "mismatch: concordance: 0.5433 != 0.54339",
    ),
    (
        "concordance/lung_age_timewt_S",
        "mismatch: concordance: 0.54962 != 0.54967",
    ),
    (
        "concordance/lung_age_timewt_SG",
        "mismatch: concordance: 0.54916 != 0.54923",
    ),
    (
        "concordance/lung_age_timewt_n",
        "mismatch: concordance: 0.5502 != 0.55024",
    ),
    (
        "concordance/lung_age_timewt_nG2",
        "mismatch: concordance: 0.54916 != 0.54923",
    ),
    (
        "concordance/lung_age_weighted",
        "mismatch: concordance: 0.45501 != 0.45497",
    ),
    (
        "concordance/lung_numeric_y_age",
        "missing feature: harness: numeric (uncensored) response",
    ),
    (
        "concordance/ovarian_age_influence",
        "missing feature: concordance_index has no influence output",
    ),
    (
        "concordance/synthetic_delayed_x",
        "missing feature: concordance_index has no influence output",
    ),
    (
        "concordance/synthetic_ties_x",
        "missing feature: concordance_index has no influence output",
    ),
    (
        "concordance/veteran_karno_age_multi",
        "missing feature: harness: several terms or strata",
    ),
    (
        "coxph/aml_x/residuals.martingale",
        "mismatch: martingale[4]: 0.65156 != 0.67626",
    ),
    (
        "coxph/aml_x/residuals.deviance",
        "mismatch: deviance[4]: 0.89747 != 0.95033",
    ),
    ("coxph/bladder_ag/var", "missing feature: robust variance"),
    (
        "coxph/bladder_ag/linear_predictors",
        "mismatch: linear_predictors[0]: -0.078965 != 0.040542",
    ),
    (
        "coxph/bladder_ag/residuals.martingale",
        "mismatch: martingale[4]: 0.28453 != 0.33371",
    ),
    (
        "coxph/bladder_ag/residuals.deviance",
        "mismatch: deviance[4]: 0.31712 != 0.38032",
    ),
    ("coxph/bladder_wlw/var", "missing feature: robust variance"),
    (
        "coxph/bladder_wlw/linear_predictors",
        "mismatch: linear_predictors[0]: -0.52935 != -0.022133",
    ),
    (
        "coxph/bladder_wlw/residuals.martingale",
        "mismatch: martingale[16]: 0.21381 != 0.26783",
    ),
    (
        "coxph/bladder_wlw/residuals.deviance",
        "mismatch: deviance[16]: 0.23129 != 0.29636",
    ),
    (
        "coxph/cgd_counting_strata_enum/linear_predictors",
        "mismatch: linear_predictors[0]: -1.2156 != -0.85946",
    ),
    (
        "coxph/cgd_counting_strata_enum/residuals.martingale",
        "mismatch: martingale[51]: 0.68659 != 0.69502",
    ),
    (
        "coxph/cgd_counting_strata_enum/residuals.deviance",
        "mismatch: deviance[51]: 0.97329 != 0.99246",
    ),
    (
        "coxph/cgd_counting_treat_cluster_id/var",
        "missing feature: robust variance",
    ),
    (
        "coxph/cgd_counting_treat_cluster_id/residuals.martingale",
        "mismatch: martingale[1]: 0.53933 != 0.57026",
    ),
    (
        "coxph/cgd_counting_treat_cluster_id/residuals.deviance",
        "mismatch: deviance[1]: 0.68665 != 0.74069",
    ),
    (
        "coxph/cgd_counting_treat_id_robust/var",
        "missing feature: robust variance",
    ),
    (
        "coxph/cgd_counting_treat_id_robust/linear_predictors",
        "mismatch: linear_predictors[0]: -1.4867 != -1.068",
    ),
    (
        "coxph/cgd_counting_treat_id_robust/residuals.martingale",
        "mismatch: martingale[1]: 0.56231 != 0.59437",
    ),
    (
        "coxph/cgd_counting_treat_id_robust/residuals.deviance",
        "mismatch: deviance[1]: 0.72654 != 0.78478",
    ),
    (
        "coxph/colon_death_rx_nodes_extent/linear_predictors",
        "mismatch: linear_predictors[0]: 1.7016 != -0.19561",
    ),
    (
        "coxph/colon_death_rx_nodes_extent/residuals.martingale",
        "mismatch: martingale[18]: 0.89558 != 0.89611",
    ),
    (
        "coxph/colon_death_rx_nodes_extent/residuals.deviance",
        "mismatch: deviance[18]: 1.6515 != 1.6543",
    ),
    (
        "coxph/flchain_500_age_sex_kappa/linear_predictors",
        "mismatch: linear_predictors[0]: 14.114 != 2.5746",
    ),
    (
        "coxph/flchain_500_age_sex_kappa/residuals.martingale",
        "mismatch: martingale[0]: 0.34212 != 0.35247",
    ),
    (
        "coxph/flchain_500_age_sex_kappa/residuals.deviance",
        "mismatch: deviance[0]: 0.39144 != 0.40527",
    ),
    (
        "coxph/heart_counting_age_surgery_transplant/coef_names",
        "mismatch: coef names [\"age\", \"surgery\", \"transplant\"] != [\"age\", \"surgery\", \"tr...",
    ),
    (
        "coxph/heart_counting_age_surgery_transplant/linear_predictors",
        "mismatch: linear_predictors[0]: -0.52386 != -0.44801",
    ),
    (
        "coxph/heart_counting_age_surgery_transplant/residuals.martingale",
        "mismatch: martingale[1]: 0.85598 != 0.86288",
    ),
    (
        "coxph/heart_counting_age_surgery_transplant/residuals.deviance",
        "mismatch: deviance[1]: 1.4709 != 1.4993",
    ),
    (
        "coxph/heart_counting_breslow/coef_names",
        "mismatch: coef names [\"age\", \"surgery\", \"transplant\"] != [\"age\", \"surgery\", \"tr...",
    ),
    (
        "coxph/heart_counting_breslow/linear_predictors",
        "mismatch: linear_predictors[0]: -0.52379 != -0.44795",
    ),
    (
        "coxph/jasa_surgery_age/linear_predictors",
        "mismatch: linear_predictors[0]: 0.94619 != -0.43943",
    ),
    (
        "coxph/jasa_surgery_age/residuals.martingale",
        "mismatch: martingale[1]: 0.85575 != 0.86267",
    ),
    (
        "coxph/jasa_surgery_age/residuals.deviance",
        "mismatch: deviance[1]: 1.47 != 1.4985",
    ),
    (
        "coxph/kidney_age_sex/linear_predictors",
        "mismatch: linear_predictors[0]: -0.77242 != 0.57918",
    ),
    (
        "coxph/kidney_age_sex/residuals.martingale",
        "mismatch: martingale[0]: 0.8813 != 0.89374",
    ),
    (
        "coxph/kidney_age_sex/residuals.deviance",
        "mismatch: deviance[0]: 1.581 != 1.642",
    ),
    (
        "coxph/kidney_age_sex_disease/linear_predictors",
        "mismatch: linear_predictors[0]: -1.3941 != 1.0429",
    ),
    (
        "coxph/kidney_age_sex_disease/residuals.martingale",
        "mismatch: martingale[0]: 0.84054 != 0.85746",
    ),
    (
        "coxph/kidney_age_sex_disease/residuals.deviance",
        "mismatch: deviance[0]: 1.411 != 1.4769",
    ),
    (
        "coxph/lung_age_offset/linear_predictors",
        "mismatch: linear_predictors[0]: 2.6349 != 1.2552",
    ),
    (
        "coxph/lung_age_offset/residuals.martingale",
        "mismatch: martingale[6]: -0.22141 != -0.2116",
    ),
    (
        "coxph/lung_age_offset/residuals.deviance",
        "mismatch: deviance[6]: -0.2069 != -0.19828",
    ),
    (
        "coxph/lung_age_sex_breslow/linear_predictors",
        "mismatch: linear_predictors[0]: 0.74639 != 0.39887",
    ),
    (
        "coxph/lung_age_sex_cluster_inst/var",
        "missing feature: robust variance",
    ),
    (
        "coxph/lung_age_sex_cluster_inst/linear_predictors",
        "mismatch: linear_predictors[0]: 0.79178 != 0.40018",
    ),
    (
        "coxph/lung_age_sex_cluster_inst/residuals.martingale",
        "mismatch: martingale[6]: 0.43687 != 0.44188",
    ),
    (
        "coxph/lung_age_sex_cluster_inst/residuals.deviance",
        "mismatch: deviance[6]: 0.52417 != 0.5316",
    ),
    (
        "coxph/lung_age_sex_efron/linear_predictors",
        "mismatch: linear_predictors[0]: 0.74814 != 0.3995",
    ),
    (
        "coxph/lung_age_sex_efron/residuals.martingale",
        "mismatch: martingale[6]: 0.44267 != 0.44753",
    ),
    (
        "coxph/lung_age_sex_efron/residuals.deviance",
        "mismatch: deviance[6]: 0.53278 != 0.54005",
    ),
    (
        "coxph/lung_age_sex_eps/linear_predictors",
        "mismatch: linear_predictors[0]: 0.74818 != 0.39944",
    ),
    (
        "coxph/lung_age_sex_eps/residuals.martingale",
        "mismatch: martingale[6]: 0.44262 != 0.44749",
    ),
    (
        "coxph/lung_age_sex_eps/residuals.deviance",
        "mismatch: deviance[6]: 0.53271 != 0.53999",
    ),
    (
        "coxph/lung_age_sex_exact/linear_predictors",
        "mismatch: linear_predictors[0]: 0.7486 != 0.39993",
    ),
    (
        "coxph/lung_age_sex_init/linear_predictors",
        "mismatch: linear_predictors[0]: 0.74814 != 0.3995",
    ),
    (
        "coxph/lung_age_sex_init/residuals.martingale",
        "mismatch: martingale[6]: 0.44267 != 0.44753",
    ),
    (
        "coxph/lung_age_sex_init/residuals.deviance",
        "mismatch: deviance[6]: 0.53278 != 0.54005",
    ),
    (
        "coxph/lung_age_sex_init_iter0/linear_predictors",
        "mismatch: linear_predictors[0]: 0.98 != 0.42842",
    ),
    (
        "coxph/lung_age_sex_init_iter0/residuals.martingale",
        "mismatch: martingale[6]: 0.43028 != 0.43525",
    ),
    (
        "coxph/lung_age_sex_init_iter0/residuals.deviance",
        "mismatch: deviance[6]: 0.51445 != 0.52177",
    ),
    (
        "coxph/lung_age_sex_nocenter_null/linear_predictors",
        "mismatch: linear_predictors[0]: 0.74814 != 0.3995",
    ),
    (
        "coxph/lung_age_sex_nocenter_null/residuals.martingale",
        "mismatch: martingale[6]: 0.44267 != 0.44753",
    ),
    (
        "coxph/lung_age_sex_nocenter_null/residuals.deviance",
        "mismatch: deviance[6]: 0.53278 != 0.54005",
    ),
    (
        "coxph/lung_age_sex_robust/var",
        "missing feature: robust variance",
    ),
    (
        "coxph/lung_age_sex_robust/linear_predictors",
        "mismatch: linear_predictors[0]: 0.74814 != 0.3995",
    ),
    (
        "coxph/lung_age_sex_robust/residuals.martingale",
        "mismatch: martingale[6]: 0.44267 != 0.44753",
    ),
    (
        "coxph/lung_age_sex_robust/residuals.deviance",
        "mismatch: deviance[6]: 0.53278 != 0.54005",
    ),
    (
        "coxph/lung_age_sex_weighted/var",
        "missing feature: robust variance",
    ),
    (
        "coxph/lung_age_sex_weighted/linear_predictors",
        "mismatch: linear_predictors[0]: 0.1229 != 0.34273",
    ),
    (
        "coxph/lung_age_sex_weighted/residuals.martingale",
        "mismatch: martingale[6]: 0.4397 != 0.44453",
    ),
    (
        "coxph/lung_age_sex_weighted/residuals.deviance",
        "mismatch: deviance[6]: 0.52836 != 0.53556",
    ),
    (
        "coxph/lung_age_sex_weighted_breslow/var",
        "missing feature: robust variance",
    ),
    (
        "coxph/lung_age_sex_weighted_breslow/linear_predictors",
        "mismatch: linear_predictors[0]: 0.12189 != 0.34198",
    ),
    (
        "coxph/lung_age_sex_x_true/linear_predictors",
        "mismatch: linear_predictors[0]: 0.74814 != 0.3995",
    ),
    (
        "coxph/lung_age_sex_x_true/residuals.martingale",
        "mismatch: martingale[6]: 0.44267 != 0.44753",
    ),
    (
        "coxph/lung_age_sex_x_true/residuals.deviance",
        "mismatch: deviance[6]: 0.53278 != 0.54005",
    ),
    (
        "coxph/lung_age_strata_sex/linear_predictors",
        "mismatch: linear_predictors[0]: 1.2671 != 0.15271",
    ),
    (
        "coxph/lung_age_strata_sex/residuals.martingale",
        "mismatch: martingale[18]: 0.85352 != 0.85754",
    ),
    (
        "coxph/lung_age_strata_sex/residuals.deviance",
        "mismatch: deviance[18]: 1.4611 != 1.4773",
    ),
    (
        "coxph/lung_factor_ph_ecog/linear_predictors",
        "mismatch: linear_predictors[0]: 0.69251 != 0.75565",
    ),
    (
        "coxph/lung_factor_ph_ecog/residuals.martingale",
        "mismatch: martingale[6]: 0.13346 != 0.14147",
    ),
    (
        "coxph/lung_factor_ph_ecog/residuals.deviance",
        "mismatch: deviance[6]: 0.1399 != 0.14875",
    ),
    (
        "coxph/lung_interaction",
        "missing feature: harness: formula term age * sex",
    ),
    (
        "coxph/lung_log_transform/linear_predictors",
        "mismatch: linear_predictors[0]: 3.8156 != 0.38466",
    ),
    (
        "coxph/lung_log_transform/residuals.martingale",
        "mismatch: martingale[6]: 0.44157 != 0.44644",
    ),
    (
        "coxph/lung_log_transform/residuals.deviance",
        "mismatch: deviance[6]: 0.53114 != 0.53841",
    ),
    (
        "coxph/mgus2_age_sex_mspike/linear_predictors",
        "mismatch: linear_predictors[0]: 5.4904 != 1.0709",
    ),
    (
        "coxph/mgus2_age_sex_mspike/residuals.martingale",
        "mismatch: martingale[0]: 0.5553 != 0.56184",
    ),
    (
        "coxph/mgus2_age_sex_mspike/residuals.deviance",
        "mismatch: deviance[0]: 0.71421 != 0.72571",
    ),
    (
        "coxph/myeloid_trt_sex_flt3/residuals.martingale",
        "mismatch: martingale[0]: 0.8213 != 0.82233",
    ),
    (
        "coxph/myeloid_trt_sex_flt3/residuals.deviance",
        "mismatch: deviance[0]: 1.3422 != 1.3457",
    ),
    (
        "coxph/nafld1_1000_age_male_bmi/linear_predictors",
        "mismatch: linear_predictors[0]: 6.3981 != 0.21565",
    ),
    (
        "coxph/nafld1_1000_age_male_bmi/residuals.martingale",
        "mismatch: martingale[96]: 0.97997 != 0.98092",
    ),
    (
        "coxph/nafld1_1000_age_male_bmi/residuals.deviance",
        "mismatch: deviance[96]: 2.421 != 2.4405",
    ),
    (
        "coxph/ovarian_age_rx/linear_predictors",
        "mismatch: linear_predictors[0]: 9.8524 != 2.7837",
    ),
    (
        "coxph/ovarian_age_rx_exact/linear_predictors",
        "mismatch: linear_predictors[0]: 9.8524 != 2.7837",
    ),
    (
        "coxph/pbc_trial_age_edema_strata_sex/linear_predictors",
        "mismatch: linear_predictors[0]: 6.1042 != 3.6062",
    ),
    (
        "coxph/pbc_trial_age_edema_strata_sex/residuals.martingale",
        "mismatch: martingale[22]: 0.10142 != 0.13678",
    ),
    (
        "coxph/pbc_trial_age_edema_strata_sex/residuals.deviance",
        "mismatch: deviance[22]: 0.10506 != 0.14356",
    ),
    (
        "coxph/pbc_trial_trt_factor/linear_predictors",
        "mismatch: linear_predictors[0]: -2.3562 != 1.8251",
    ),
    (
        "coxph/pbc_trial_trt_factor/residuals.martingale",
        "mismatch: martingale[22]: 0.87106 != 0.8752",
    ),
    (
        "coxph/pbc_trial_trt_factor/residuals.deviance",
        "mismatch: deviance[22]: 1.5345 != 1.5529",
    ),
    (
        "coxph/rats_rx_litter_cluster/var",
        "missing feature: robust variance",
    ),
    (
        "coxph/rats_rx_litter_cluster/residuals.martingale",
        "mismatch: martingale[31]: 0.88866 != 0.89109",
    ),
    (
        "coxph/rats_rx_litter_cluster/residuals.deviance",
        "mismatch: deviance[31]: 1.6165 != 1.6286",
    ),
    (
        "coxph/synthetic_delayed_x/linear_predictors",
        "mismatch: linear_predictors[0]: -0.61326 != -0.3884",
    ),
    (
        "coxph/synthetic_delayed_x/residuals.martingale",
        "mismatch: martingale[3]: 0.38673 != 0.48532",
    ),
    (
        "coxph/synthetic_delayed_x/residuals.deviance",
        "mismatch: deviance[3]: 0.45215 != 0.59815",
    ),
    (
        "coxph/synthetic_delayed_x_breslow/linear_predictors",
        "mismatch: linear_predictors[0]: -0.59182 != -0.37482",
    ),
    (
        "coxph/synthetic_delayed_x_exact/linear_predictors",
        "mismatch: linear_predictors[0]: -0.62639 != -0.39671",
    ),
    (
        "coxph/synthetic_delayed_x_exact/residuals.deviance",
        "mismatch: deviance[0]: 1.4061 != 0.83923",
    ),
    (
        "coxph/synthetic_ties_breslow/linear_predictors",
        "mismatch: linear_predictors[0]: 0.38227 != 0.14335",
    ),
    (
        "coxph/synthetic_ties_efron/linear_predictors",
        "mismatch: linear_predictors[0]: 0.38214 != 0.1433",
    ),
    (
        "coxph/synthetic_ties_efron/residuals.martingale",
        "mismatch: martingale[0]: 0.84016 != 0.8819",
    ),
    (
        "coxph/synthetic_ties_efron/residuals.deviance",
        "mismatch: deviance[0]: 1.4095 != 1.5839",
    ),
    (
        "coxph/synthetic_ties_exact/linear_predictors",
        "mismatch: linear_predictors[0]: 0.47841 != 0.1794",
    ),
    (
        "coxph/synthetic_timefix_true",
        "missing feature: null model",
    ),
    (
        "coxph/transplant_ltx_age_abo/linear_predictors",
        "mismatch: linear_predictors[0]: -0.57888 != -0.31871",
    ),
    (
        "coxph/transplant_ltx_age_abo/residuals.martingale",
        "mismatch: martingale[1]: 0.84805 != 0.84992",
    ),
    (
        "coxph/transplant_ltx_age_abo/residuals.deviance",
        "mismatch: deviance[1]: 1.4396 != 1.4468",
    ),
    (
        "coxph/veteran_celltype_karno_trt/linear_predictors",
        "mismatch: linear_predictors[0]: -1.6145 != -0.17466",
    ),
    (
        "coxph/veteran_celltype_karno_trt/residuals.martingale",
        "mismatch: martingale[5]: 0.87029 != 0.87538",
    ),
    (
        "coxph/veteran_celltype_karno_trt/residuals.deviance",
        "mismatch: deviance[5]: 1.5311 != 1.5538",
    ),
    (
        "coxph/veteran_celltype_x_true/linear_predictors",
        "mismatch: linear_predictors[0]: -1.8634 != -0.044431",
    ),
    (
        "coxph/veteran_celltype_x_true/residuals.martingale",
        "mismatch: martingale[5]: 0.84227 != 0.84848",
    ),
    (
        "coxph/veteran_celltype_x_true/residuals.deviance",
        "mismatch: deviance[5]: 1.4175 != 1.4412",
    ),
    (
        "coxph/veteran_tt_karno",
        "missing feature: coxph argument tt (time-transform terms)",
    ),
    (
        "coxph/veteran_tt_strata",
        "missing feature: coxph argument tt (time-transform terms)",
    ),
    (
        "coxph_diagnostics/aml_x/residuals.partial",
        "mismatch: partial[4][0]: 0.65156 != 0.67626",
    ),
    (
        "coxph_diagnostics/cgd_counting_treat_cluster_id/residuals.partial",
        "mismatch: partial[1][0]: -0.53289 != -0.50196",
    ),
    (
        "coxph_diagnostics/heart_counting_age_surgery_transplant/residuals.partial",
        "mismatch: partial[0][0]: 0.21011 != 0.28596",
    ),
    (
        "coxph_diagnostics/kidney_age_sex_disease/residuals.partial",
        "mismatch: partial[0]: length 5 differs from expected 3",
    ),
    (
        "coxph_diagnostics/lung_age_offset/residuals.partial",
        "mismatch: partial[0][0]: 2.1383 != 0.7586",
    ),
    (
        "coxph_diagnostics/lung_age_sex_breslow/residuals.partial",
        "mismatch: partial[0][0]: 1.2651 != 0.2027",
    ),
    (
        "coxph_diagnostics/lung_age_sex_cluster_inst/residuals.partial",
        "mismatch: partial[0][0]: 1.2975 != 0.21033",
    ),
    (
        "coxph_diagnostics/lung_age_sex_efron/residuals.partial",
        "mismatch: partial[0][0]: 1.2657 != 0.20131",
    ),
    (
        "coxph_diagnostics/lung_age_sex_exact",
        "mismatch: partial[0][0]: 1.2677 != 0.20235",
    ),
    (
        "coxph_diagnostics/lung_age_sex_nocenter_null/residuals.partial",
        "mismatch: partial[0][0]: 1.2657 != 0.20131",
    ),
    (
        "coxph_diagnostics/lung_age_sex_weighted/residuals.dfbeta",
        "mismatch: dfbeta[1][0]: -0.00018447 != -0.00036893",
    ),
    (
        "coxph_diagnostics/lung_age_sex_weighted/residuals.dfbetas",
        "mismatch: dfbetas[1][0]: -0.023263 != -0.046525",
    ),
    (
        "coxph_diagnostics/lung_age_sex_weighted/residuals.partial",
        "mismatch: partial[0][0]: 0.68097 != 0.099484",
    ),
    (
        "coxph_diagnostics/lung_age_strata_sex/residuals.partial",
        "mismatch: partial[0][0]: 0.78152 != 0.10099",
    ),
    (
        "coxph_diagnostics/ovarian_age_rx/residuals.partial",
        "mismatch: partial[0][0]: 11.475 != 3.1999",
    ),
    (
        "coxph_diagnostics/ovarian_age_rx_exact",
        "mismatch: partial[0][0]: 11.475 != 3.1999",
    ),
    (
        "coxph_diagnostics/pbc_trial_age_edema_strata_sex/residuals.partial",
        "mismatch: partial[0][0]: 1.76 != -0.024718",
    ),
    (
        "coxph_diagnostics/synthetic_delayed_x/residuals.partial",
        "mismatch: partial[0][0]: 0.22366 != 0.44853",
    ),
    (
        "coxph_diagnostics/synthetic_ties_breslow/residuals.partial",
        "mismatch: partial[0][0]: 1.2306 != 0.9917",
    ),
    (
        "coxph_diagnostics/synthetic_ties_efron/residuals.partial",
        "mismatch: partial[0][0]: 1.2223 != 1.0252",
    ),
    (
        "coxph_diagnostics/synthetic_ties_exact",
        "mismatch: partial[0][0]: 1.3101 != 1.011",
    ),
    (
        "coxph_diagnostics/veteran_celltype_karno_trt/residuals.partial",
        "mismatch: partial[0]: length 5 differs from expected 3",
    ),
    (
        "survdiff/lung_one_sample_survexp_us",
        "missing feature: one-sample survdiff against survexp",
    ),
    (
        "survfit_km/aml_fh2_ties",
        "missing feature: survfit argument type",
    ),
    (
        "survfit_km/aml_fh_ties",
        "missing feature: survfit argument type",
    ),
    (
        "survfit_km/aml_x/std_err",
        "mismatch: curve[x=Maintained].std_err[0]: 0.086678 != 0.095346",
    ),
    (
        "survfit_km/aml_x/conf",
        "mismatch: curve[x=Nonmaintained].lower[9]: 0 != NaN",
    ),
    (
        "survfit_km/bladder_rx_enum1/std_err",
        "mismatch: curve[rx=1].std_err[0]: 0.021049 != 0.021507",
    ),
    (
        "survfit_km/cgd_counting_cluster",
        "missing feature: survfit argument cluster",
    ),
    (
        "survfit_km/cgd_counting_treat_id",
        "missing feature: survfit argument id",
    ),
    (
        "survfit_km/cgd_counting_treat_noid/std_err",
        "mismatch: curve[treat=placebo].std_err[0]: 0.015266 != 0.015504",
    ),
    (
        "survfit_km/colon_rx_death/std_err",
        "mismatch: curve[rx=Obs].std_err[0]: 0.0031696 != 0.0031797",
    ),
    (
        "survfit_km/flchain_sex_500/std_err",
        "mismatch: curve[sex=F].std_err[0]: 0.0051239 != 0.0051614",
    ),
    (
        "survfit_km/heart_counting_transplant_id",
        "missing feature: survfit argument id",
    ),
    (
        "survfit_km/jasa_surgery/std_err",
        "mismatch: curve[surgery=0].std_err[0]: 0.016067 != 0.016445",
    ),
    (
        "survfit_km/kidney_sex/std_err",
        "mismatch: curve[sex=1].std_err[0]: 0.048734 != 0.051299",
    ),
    (
        "survfit_km/kidney_sex/conf",
        "mismatch: curve[sex=1].lower[17]: 0 != NaN",
    ),
    (
        "survfit_km/lung_1/std_err",
        "mismatch: curve[1].std_err[0]: 0.0043763 != 0.0043956",
    ),
    (
        "survfit_km/lung_conf_arcsin",
        "missing feature: conf.type arcsin",
    ),
    (
        "survfit_km/lung_conf_int_90/std_err",
        "mismatch: curve[sex=1].std_err[0]: 0.012414 != 0.01269",
    ),
    (
        "survfit_km/lung_conf_log/std_err",
        "mismatch: curve[1].std_err[0]: 0.0043763 != 0.0043956",
    ),
    (
        "survfit_km/lung_conf_logit",
        "missing feature: conf.type logit",
    ),
    (
        "survfit_km/lung_conf_loglog/std_err",
        "mismatch: curve[1].std_err[0]: 0.0043763 != 0.0043956",
    ),
    (
        "survfit_km/lung_conf_lower_modified",
        "missing feature: survfit argument conf.lower",
    ),
    (
        "survfit_km/lung_conf_lower_peto",
        "missing feature: survfit argument conf.lower",
    ),
    (
        "survfit_km/lung_conf_none",
        "missing feature: conf.type none",
    ),
    (
        "survfit_km/lung_conf_plain/std_err",
        "mismatch: curve[1].std_err[0]: 0.0043763 != 0.0043956",
    ),
    (
        "survfit_km/lung_reverse/std_err",
        "mismatch: curve[sex=1].std_err[33]: 0.010471 != 0.010582",
    ),
    (
        "survfit_km/lung_reverse/conf",
        "mismatch: curve[sex=1].lower[118]: 0 != NaN",
    ),
    (
        "survfit_km/lung_reverse_1/std_err",
        "mismatch: curve[1].std_err[19]: 0.0049627 != 0.0049875",
    ),
    (
        "survfit_km/lung_reverse_1/conf",
        "mismatch: curve[1].lower[185]: 0 != NaN",
    ),
    (
        "survfit_km/lung_sex/std_err",
        "mismatch: curve[sex=1].std_err[0]: 0.012414 != 0.01269",
    ),
    (
        "survfit_km/lung_sex_ph_ecog",
        "missing feature: harness: survfit with several grouping terms",
    ),
    (
        "survfit_km/lung_start_time_100",
        "missing feature: survfit argument start.time",
    ),
    (
        "survfit_km/lung_stype1_ctype2",
        "missing feature: survfit argument stype",
    ),
    (
        "survfit_km/lung_stype2_ctype1",
        "missing feature: survfit argument stype",
    ),
    (
        "survfit_km/lung_stype2_ctype2",
        "missing feature: survfit argument stype",
    ),
    (
        "survfit_km/lung_time0",
        "missing feature: survfit argument time0",
    ),
    (
        "survfit_km/lung_type_fh",
        "missing feature: survfit argument type",
    ),
    (
        "survfit_km/lung_type_fh2",
        "missing feature: survfit argument type",
    ),
    (
        "survfit_km/lung_weighted/std_err",
        "mismatch: curve[sex=1].std_err[0]: 0.010217 != 0.011061",
    ),
    (
        "survfit_km/lung_weighted/std_chaz",
        "mismatch: curve[sex=1].std_chaz[0]: 0.01031 != 0.011061",
    ),
    (
        "survfit_km/lung_weighted/conf",
        "mismatch: curve[sex=1].lower[0]: 0.96232 != 0.9607",
    ),
    (
        "survfit_km/lung_weighted_1/std_err",
        "mismatch: curve[1].std_err[0]: 0.0035026 != 0.0035057",
    ),
    (
        "survfit_km/lung_weighted_1/std_chaz",
        "mismatch: curve[1].std_chaz[0]: 0.0035088 != 0.0035057",
    ),
    (
        "survfit_km/lung_weighted_1/conf",
        "mismatch: curve[1].lower[0]: 0.98965 != 0.98964",
    ),
    (
        "survfit_km/mgus2_sex/std_err",
        "mismatch: curve[sex=F].std_err[0]: 0.0069742 != 0.0072024",
    ),
    (
        "survfit_km/mgus2_sex/conf",
        "mismatch: curve[sex=M].lower[231]: 0 != NaN",
    ),
    (
        "survfit_km/myeloid_trt/std_err",
        "mismatch: curve[trt=A].std_err[2]: 0.0031796 != 0.0031898",
    ),
    (
        "survfit_km/nafld1_male_1000/std_err",
        "mismatch: curve[male=0].std_err[0]: 0.0017841 != 0.0017873",
    ),
    (
        "survfit_km/ovarian_rx/std_err",
        "mismatch: curve[rx=1].std_err[0]: 0.073905 != 0.080064",
    ),
    (
        "survfit_km/pbc_trt/std_err",
        "mismatch: curve[trt=1].std_err[0]: 0.0063091 != 0.0063492",
    ),
    (
        "survfit_km/rats_rx/std_err",
        "mismatch: curve[rx=0].std_err[2]: 0.0050377 != 0.0050633",
    ),
    (
        "survfit_km/synthetic_delayed_entry/std_err",
        "mismatch: curve[1].std_err[0]: 0.15215 != 0.18257",
    ),
    (
        "survfit_km/synthetic_delayed_entry/conf",
        "mismatch: curve[1].lower[8]: 0 != NaN",
    ),
    (
        "survfit_km/synthetic_ties/std_err",
        "mismatch: curve[g=a].std_err[0]: 0.11693 != 0.13363",
    ),
    (
        "survfit_km/synthetic_ties/conf",
        "mismatch: curve[g=a].lower[6]: 0 != NaN",
    ),
    (
        "survfit_km/synthetic_ties_1/std_err",
        "mismatch: curve[1].std_err[0]: 0.08268 != 0.094491",
    ),
    (
        "survfit_km/synthetic_ties_1/conf",
        "mismatch: curve[1].lower[8]: 0 != NaN",
    ),
    (
        "survfit_km/synthetic_timefix_false",
        "mismatch: curve[1].time: length 6 differs from expected 8",
    ),
    (
        "survfit_km/synthetic_timefix_true/std_err",
        "mismatch: curve[1].std_err[0]: 0.15309 != 0.20412",
    ),
    (
        "survfit_km/synthetic_timefix_true/conf",
        "mismatch: curve[1].lower[4]: 0 != NaN",
    ),
    (
        "survfit_km/transplant_abo_ltx/std_err",
        "mismatch: curve[abo=A].std_err[0]: 0.0080526 != 0.0082299",
    ),
    (
        "survfit_km/transplant_abo_ltx/conf",
        "mismatch: curve[abo=B].lower[89]: 0 != NaN",
    ),
    (
        "survfit_km/veteran_celltype/std_err",
        "mismatch: curve[celltype=squamous].std_err[0]: 0.039235 != 0.041613",
    ),
    (
        "survfit_km/veteran_celltype/conf",
        "mismatch: curve[celltype=squamous].lower[32]: 0 != NaN",
    ),
    (
        "survreg/interval2_synthetic_lognormal_g",
        "missing feature: harness: Surv(type=) responses",
    ),
    (
        "survreg/interval2_synthetic_weibull",
        "missing feature: harness: Surv(type=) responses",
    ),
    (
        "survreg/interval_status_synthetic_weibull",
        "missing feature: harness: Surv(type=) responses",
    ),
    (
        "survreg/kidney_weibull_age_sex",
        "mismatch: coef[0]: 1.3074 != 3.3176",
    ),
    (
        "survreg/lung_age_sex_exponential/loglik",
        "mismatch: loglik: -281.87 != -1156.1",
    ),
    (
        "survreg/lung_age_sex_gaussian",
        "mismatch: coef[0]: 4.3976 != 403.32",
    ),
    (
        "survreg/lung_age_sex_logistic",
        "mismatch: coef[0]: -0.014205 != 340.77",
    ),
    (
        "survreg/lung_age_sex_loglogistic/loglik",
        "mismatch: loglik: -278.67 != -1152.9",
    ),
    (
        "survreg/lung_age_sex_lognormal/loglik",
        "mismatch: loglik: -284.52 != -1158.8",
    ),
    (
        "survreg/lung_age_sex_rayleigh/coef",
        "mismatch: coef[0]: -27.845 != 6.2597",
    ),
    (
        "survreg/lung_age_sex_rayleigh/loglik",
        "mismatch: loglik: -44210 != -1174.5",
    ),
    (
        "survreg/lung_age_sex_rayleigh/var",
        "mismatch: var[0][0]: 0.017179 != 0.1037",
    ),
    (
        "survreg/lung_age_sex_rayleigh/linear_predictors",
        "mismatch: linear_predictors[0]: 1.9764 != 5.8767",
    ),
    (
        "survreg/lung_age_sex_t/coef",
        "mismatch: coef[0]: 307.34 != 307.34",
    ),
    (
        "survreg/lung_age_sex_t/scale",
        "mismatch: scale: 196.25 != 196.25",
    ),
    (
        "survreg/lung_age_sex_t/linear_predictors",
        "mismatch: linear_predictors[0]: 253.09 != 253.09",
    ),
    (
        "survreg/lung_age_sex_t_df8",
        "missing feature: survreg argument parms",
    ),
    (
        "survreg/lung_age_sex_weibull",
        "mismatch: coef[0]: 0.65845 != 6.2749",
    ),
    (
        "survreg/lung_intercept_only_weibull",
        "mismatch: coef[0]: 0.65847 != 6.0349",
    ),
    (
        "survreg/lung_lognormal_strata_sex/coef",
        "mismatch: coef[0]: 7.3677 != 7.3677",
    ),
    (
        "survreg/lung_lognormal_strata_sex/scale",
        "mismatch: scale[0]: 1.0824 != 1.0824",
    ),
    (
        "survreg/lung_lognormal_strata_sex/loglik",
        "mismatch: loglik: -280.25 != -1139.8",
    ),
    (
        "survreg/lung_lognormal_strata_sex/linear_predictors",
        "mismatch: linear_predictors[1]: 5.8935 != 5.8935",
    ),
    (
        "survreg/lung_weibull_cluster_inst",
        "mismatch: coef[0]: 0.65524 != 6.316",
    ),
    (
        "survreg/lung_weibull_factor_ph_ecog",
        "mismatch: coef[0]: 0.65399 != 6.2576",
    ),
    (
        "survreg/lung_weibull_init",
        "missing feature: survreg argument init",
    ),
    (
        "survreg/lung_weibull_robust",
        "missing feature: survreg argument robust",
    ),
    (
        "survreg/lung_weibull_scale_fixed/loglik",
        "mismatch: loglik: -281.87 != -1156.1",
    ),
    (
        "survreg/lung_weibull_strata_sex",
        "mismatch: coef[0]: 0.74662 != 6.2102",
    ),
    (
        "survreg/lung_weibull_weighted",
        "mismatch: coef[0]: 0.67273 != 5.7756",
    ),
    (
        "survreg/lung_weibull_x_true",
        "missing feature: survreg argument x",
    ),
    (
        "survreg/ovarian_exponential_ecog_rx/coef",
        "mismatch: coef[1]: -0.43313 != -0.43313",
    ),
    (
        "survreg/ovarian_exponential_ecog_rx/loglik",
        "mismatch: loglik: -29.011 != -97.198",
    ),
    (
        "survreg/ovarian_exponential_ecog_rx/linear_predictors",
        "mismatch: linear_predictors[3]: 7.6917 != 7.6917",
    ),
    (
        "survreg/ovarian_loglogistic_age/loglik",
        "mismatch: loglik: -21.364 != -89.551",
    ),
    (
        "survreg/ovarian_weibull_ecog_rx",
        "mismatch: coef[0]: 0.74639 != 6.8967",
    ),
    (
        "survreg/pbc_trial_weibull",
        "mismatch: coef[0]: 0.50626 != 10.057",
    ),
    (
        "survreg/synthetic_ties_weibull/loglik",
        "mismatch: loglik: -15.346 != -30.751",
    ),
    (
        "survreg/tobin_gaussian_left",
        "missing feature: harness: Surv(type=) responses",
    ),
    (
        "survreg/tobin_logistic_left",
        "missing feature: harness: Surv(type=) responses",
    ),
    (
        "survreg/veteran_lognormal_celltype_karno/loglik",
        "mismatch: loglik: -196.75 != -716.16",
    ),
    (
        "survreg/veteran_weibull_celltype_karno",
        "mismatch: coef[0]: 1.1634 != 3.4806",
    ),
];

// ---------------------------------------------------------------------------
// Fixture access
// ---------------------------------------------------------------------------

fn manifest_path(relative: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(relative)
}

fn load_topic(topic: &str) -> Value {
    let path = manifest_path(&format!("test/r/fixtures/{topic}.json"));
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|err| panic!("cannot read {}: {err}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|err| panic!("invalid JSON in {topic}: {err}"))
}

fn is_r_error(value: &Value) -> bool {
    value.get("r_error").is_some()
}

/// Decode one fixture number: `null` -> NaN (R `NA`), the strings `"NaN"`,
/// `"Inf"`, `"-Inf"` -> the corresponding float.
fn num(value: &Value) -> Result<f64, String> {
    match value {
        Value::Null => Ok(f64::NAN),
        Value::Number(n) => n.as_f64().ok_or_else(|| "non-f64 number".to_string()),
        Value::Bool(b) => Ok(if *b { 1.0 } else { 0.0 }),
        Value::String(s) => match s.as_str() {
            "NaN" => Ok(f64::NAN),
            "Inf" => Ok(f64::INFINITY),
            "-Inf" => Ok(f64::NEG_INFINITY),
            other => Err(format!("not a number: {other:?}")),
        },
        other => Err(format!("not a number: {other}")),
    }
}

fn nums(value: &Value) -> Result<Vec<f64>, String> {
    match value {
        Value::Array(items) => items.iter().map(num).collect(),
        Value::Null => Err("missing numeric vector".to_string()),
        other => Ok(vec![num(other)?]),
    }
}

fn matrix(value: &Value) -> Result<Vec<Vec<f64>>, String> {
    match value {
        Value::Array(rows) => rows
            .iter()
            .map(|row| match row {
                Value::Array(_) => nums(row),
                other => Ok(vec![num(other)?]),
            })
            .collect(),
        other => Err(format!("not a matrix: {other}")),
    }
}

/// Values of an R named vector stored as a JSON object.  `serde_json` maps
/// do not preserve insertion order, so the generator also stores the names in
/// R order under `<key>_names`; `names` is that array.
fn named_values(value: &Value, names: &Value) -> Result<Vec<f64>, String> {
    match value {
        Value::Object(map) => match names.as_array() {
            Some(order) => order
                .iter()
                .map(|name| {
                    let key = name.as_str().ok_or("non-string name")?;
                    num(map
                        .get(key)
                        .ok_or_else(|| format!("missing coefficient {key}"))?)
                })
                .collect(),
            None => Err("named vector without an order array".to_string()),
        },
        Value::Array(items) if items.is_empty() => Ok(Vec::new()),
        other => Err(format!("not a named vector: {other}")),
    }
}

fn names_of(value: &Value) -> Vec<&str> {
    value
        .as_array()
        .map(|items| items.iter().filter_map(Value::as_str).collect())
        .unwrap_or_default()
}

fn text(value: &Value) -> Option<&str> {
    value.as_str()
}

fn is_true(value: &Value) -> bool {
    value.as_bool().unwrap_or(false)
}

// ---------------------------------------------------------------------------
// Comparison helpers
// ---------------------------------------------------------------------------

/// `|actual - expected| <= atol + rtol * |expected|`, with NaN matching only
/// NaN and infinities matching only the same infinity.
fn close(actual: f64, expected: f64, rtol: f64, atol: f64) -> bool {
    if expected.is_nan() {
        return actual.is_nan();
    }
    if expected.is_infinite() {
        return actual == expected;
    }
    if !actual.is_finite() {
        return false;
    }
    (actual - expected).abs() <= atol + rtol * expected.abs()
}

/// Largest finite magnitude of a vector or matrix, the scale of the
/// absolute floor used when comparing it.
fn max_abs<'a>(values: impl IntoIterator<Item = &'a f64>) -> f64 {
    values
        .into_iter()
        .filter(|v| v.is_finite())
        .fold(0.0, |acc, v| acc.max(v.abs()))
}

/// Compare a vector element-wise.  Like R's `all.equal`, the tolerance is
/// relative to the size of the whole vector: an element is accepted when
/// `|a - e| <= rtol * max(|e|, max|expected|)`, so floating-point noise
/// around zero (`1e-17` against an exact `0`) inside an otherwise matching
/// vector is not a mismatch.
fn assert_vec(actual: &[f64], expected: &[f64], rtol: f64, path: &str) -> Result<(), String> {
    assert_vec_within(actual, expected, rtol, rtol * max_abs(expected), path)
}

fn assert_vec_within(
    actual: &[f64],
    expected: &[f64],
    rtol: f64,
    atol: f64,
    path: &str,
) -> Result<(), String> {
    if actual.len() != expected.len() {
        return Err(format!(
            "{path}: length {} differs from expected {}",
            actual.len(),
            expected.len()
        ));
    }
    for (idx, (a, e)) in actual.iter().zip(expected).enumerate() {
        if !close(*a, *e, rtol, atol) {
            return Err(format!(
                "{path}[{idx}]: {a:?} != {e:?} (rtol={rtol:e}, atol={atol:e})"
            ));
        }
    }
    Ok(())
}

/// Compare a matrix; the absolute floor is scaled to the whole matrix.
fn assert_matrix(
    actual: &[Vec<f64>],
    expected: &[Vec<f64>],
    rtol: f64,
    path: &str,
) -> Result<(), String> {
    if actual.len() != expected.len() {
        return Err(format!(
            "{path}: {} rows, expected {}",
            actual.len(),
            expected.len()
        ));
    }
    let atol = rtol * max_abs(expected.iter().flatten());
    for (idx, (a, e)) in actual.iter().zip(expected).enumerate() {
        assert_vec_within(a, e, rtol, atol, &format!("{path}[{idx}]"))?;
    }
    Ok(())
}

/// A scalar has no vector to scale against: pure relative tolerance.
fn assert_scalar(actual: f64, expected: f64, rtol: f64, path: &str) -> Result<(), String> {
    if close(actual, expected, rtol, 0.0) {
        Ok(())
    } else {
        Err(format!(
            "{path}: {actual:?} != {expected:?} (rtol={rtol:e})"
        ))
    }
}

/// Outcome of one (case, aspect) check.
enum Outcome {
    Pass,
    Fail(String),
    Unsupported(String),
}

fn outcome(result: Result<(), String>) -> Outcome {
    match result {
        Ok(()) => Outcome::Pass,
        Err(message) if message.starts_with("unsupported:") => Outcome::Unsupported(message),
        Err(message) => Outcome::Fail(message),
    }
}

fn unsupported<T>(reason: impl Into<String>) -> Result<T, String> {
    Err(format!("unsupported: {}", reason.into()))
}

/// When `R_FIXTURES_COLLECT` names a file, append one JSON line per check
/// (`{"id", "kind", "message"}`) so the burndown list can be rebuilt.
fn collect_outcome(id: &str, outcome: &Outcome) {
    let Ok(path) = std::env::var("R_FIXTURES_COLLECT") else {
        return;
    };
    let (kind, message) = match outcome {
        Outcome::Pass => ("pass", String::new()),
        Outcome::Fail(message) => ("mismatch", message.clone()),
        Outcome::Unsupported(message) => ("missing feature", message.clone()),
    };
    let line = serde_json::json!({"id": id, "kind": kind, "message": message});
    if let Ok(mut file) = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(path)
    {
        use std::io::Write;
        let _ = writeln!(file, "{line}");
    }
}

/// Collects outcomes for a topic and applies the KNOWN_FAILURES contract.
struct Report {
    topic: String,
    checked: usize,
    failures: Vec<String>,
    unexpected_passes: Vec<String>,
    known: Vec<String>,
}

impl Report {
    fn new(topic: &str) -> Self {
        Self {
            topic: topic.to_string(),
            checked: 0,
            failures: Vec::new(),
            unexpected_passes: Vec::new(),
            known: Vec::new(),
        }
    }

    fn known_reason(&self, id: &str) -> Option<&'static str> {
        let case_id = id.rsplit_once('/').map(|(head, _)| head).unwrap_or(id);
        KNOWN_FAILURES
            .iter()
            .find(|(key, _)| *key == id || *key == case_id)
            .map(|(_, reason)| *reason)
    }

    fn record(&mut self, case: &str, aspect: &str, result: Result<(), String>) {
        let id = format!("{}/{}/{}", self.topic, case, aspect);
        self.checked += 1;
        let known = self.known_reason(&id);
        let outcome = outcome(result);
        collect_outcome(&id, &outcome);
        match (outcome, known) {
            (Outcome::Pass, None) => {}
            (Outcome::Pass, Some(reason)) => self.unexpected_passes.push(format!(
                "{id} passes; remove it from KNOWN_FAILURES ({reason})"
            )),
            (Outcome::Fail(message) | Outcome::Unsupported(message), Some(_)) => {
                self.known.push(format!("{id}: {message}"))
            }
            (Outcome::Fail(message) | Outcome::Unsupported(message), None) => {
                self.failures.push(format!("{id}: {message}"))
            }
        }
    }

    fn finish(self) {
        let mut summary = String::new();
        let _ = writeln!(
            summary,
            "{}: {} checks, {} failures, {} known failures",
            self.topic,
            self.checked,
            self.failures.len(),
            self.known.len()
        );
        for line in &self.known {
            let _ = writeln!(summary, "  known: {line}");
        }
        for line in &self.failures {
            let _ = writeln!(summary, "  FAIL: {line}");
        }
        for line in &self.unexpected_passes {
            let _ = writeln!(summary, "  XPASS: {line}");
        }
        println!("{summary}");
        assert!(
            self.failures.is_empty() && self.unexpected_passes.is_empty(),
            "{summary}"
        );
    }
}

// ---------------------------------------------------------------------------
// Data frames: bundled CSV datasets and inline fixture frames
// ---------------------------------------------------------------------------

#[derive(Clone, Debug)]
enum Column {
    Num(Vec<f64>),
    /// String column with its R factor levels (empty when the column is
    /// character rather than factor; levels are then the sorted unique values).
    Str(Vec<Option<String>>, Vec<String>),
}

impl Column {
    fn len(&self) -> usize {
        match self {
            Column::Num(values) => values.len(),
            Column::Str(values, _) => values.len(),
        }
    }

    fn subset(&self, rows: &[usize]) -> Column {
        match self {
            Column::Num(values) => Column::Num(rows.iter().map(|&i| values[i]).collect()),
            Column::Str(values, levels) => Column::Str(
                rows.iter().map(|&i| values[i].clone()).collect(),
                levels.clone(),
            ),
        }
    }

    fn levels(&self) -> Vec<String> {
        match self {
            Column::Num(values) => {
                let mut unique: Vec<f64> = values.iter().copied().filter(|v| !v.is_nan()).collect();
                unique.sort_by(f64::total_cmp);
                unique.dedup();
                unique.iter().map(|v| format_r_number(*v)).collect()
            }
            Column::Str(values, levels) => {
                if !levels.is_empty() {
                    return levels.clone();
                }
                let mut unique: Vec<String> = values.iter().flatten().cloned().collect();
                unique.sort();
                unique.dedup();
                unique
            }
        }
    }

    /// Label of row `i` as R would print it in a strata name.
    fn label(&self, i: usize) -> Option<String> {
        match self {
            Column::Num(values) => (!values[i].is_nan()).then(|| format_r_number(values[i])),
            Column::Str(values, _) => values[i].clone(),
        }
    }

    fn numeric(&self, name: &str) -> Result<Vec<f64>, String> {
        match self {
            Column::Num(values) => Ok(values.clone()),
            Column::Str(..) => unsupported(format!("column {name} is not numeric")),
        }
    }
}

fn format_r_number(value: f64) -> String {
    if value.fract() == 0.0 && value.abs() < 1e15 {
        format!("{}", value as i64)
    } else {
        format!("{value}")
    }
}

#[derive(Clone, Debug, Default)]
struct Frame {
    columns: Vec<(String, Column)>,
}

impl Frame {
    fn get(&self, name: &str) -> Result<&Column, String> {
        self.columns
            .iter()
            .find(|(column, _)| column == name)
            .map(|(_, column)| column)
            .ok_or_else(|| format!("column {name:?} not found"))
    }

    fn nrow(&self) -> usize {
        self.columns.first().map_or(0, |(_, column)| column.len())
    }

    fn subset(&self, rows: &[usize]) -> Frame {
        Frame {
            columns: self
                .columns
                .iter()
                .map(|(name, column)| (name.clone(), column.subset(rows)))
                .collect(),
        }
    }

    fn set_levels(&mut self, name: &str, levels: Vec<String>) {
        if let Some((_, Column::Str(_, current))) =
            self.columns.iter_mut().find(|(column, _)| column == name)
        {
            *current = levels;
        }
    }
}

/// Minimal CSV reader for `src/datasets/data/*.csv` (quoted fields, `NA`).
fn parse_csv(text: &str) -> Result<Frame, String> {
    let mut lines = text.lines().filter(|line| !line.trim().is_empty());
    let header = lines.next().ok_or("empty CSV")?;
    let names = split_csv_line(header);
    let mut raw: Vec<Vec<Option<String>>> = vec![Vec::new(); names.len()];
    for line in lines {
        let fields = split_csv_line(line);
        if fields.len() != names.len() {
            return Err(format!(
                "CSV row has {} fields, header {}",
                fields.len(),
                names.len()
            ));
        }
        for (column, field) in raw.iter_mut().zip(fields) {
            column.push(if field == "NA" || field.is_empty() {
                None
            } else {
                Some(field)
            });
        }
    }
    let columns = names
        .into_iter()
        .zip(raw)
        .filter(|(name, _)| name != "rownames")
        .map(|(name, values)| {
            let parsed: Option<Vec<f64>> = values
                .iter()
                .map(|value| match value {
                    None => Some(f64::NAN),
                    Some(text) => text.parse::<f64>().ok(),
                })
                .collect();
            let column = match parsed {
                Some(numbers) => Column::Num(numbers),
                None => Column::Str(values, Vec::new()),
            };
            (name, column)
        })
        .collect();
    Ok(Frame { columns })
}

fn split_csv_line(line: &str) -> Vec<String> {
    let mut fields = Vec::new();
    let mut current = String::new();
    let mut in_quotes = false;
    let mut chars = line.chars().peekable();
    while let Some(ch) = chars.next() {
        match ch {
            '"' if in_quotes && chars.peek() == Some(&'"') => {
                current.push('"');
                chars.next();
            }
            '"' => in_quotes = !in_quotes,
            ',' if !in_quotes => fields.push(std::mem::take(&mut current)),
            _ => current.push(ch),
        }
    }
    fields.push(current);
    fields
}

/// Candidate CSV file names for an R dataset name.
fn dataset_files(name: &str) -> Vec<String> {
    match name {
        "nafld1" => vec!["nafld1.csv".into(), "nafld.csv".into()],
        other => vec![format!("{other}.csv")],
    }
}

fn load_dataset(name: &str) -> Result<Frame, String> {
    for file in dataset_files(name) {
        let path = manifest_path(&format!("src/datasets/data/{file}"));
        if let Ok(text) = std::fs::read_to_string(&path) {
            return parse_csv(&text);
        }
    }
    unsupported(format!("no bundled CSV for dataset {name}"))
}

fn inline_frame(frame: &Value) -> Result<Frame, String> {
    let factors = &frame["factors"];
    let mut columns = Vec::new();
    for (name, values) in frame["columns"]
        .as_object()
        .ok_or("inline frame without columns")?
    {
        let items = values.as_array().ok_or("column is not an array")?;
        let numeric: Result<Vec<f64>, String> = items.iter().map(num).collect();
        let column = match numeric {
            Ok(values) if !items.iter().any(|v| v.is_string() && num(v).is_err()) => {
                Column::Num(values)
            }
            _ => {
                let levels = factors[name]
                    .as_array()
                    .map(|levels| {
                        levels
                            .iter()
                            .filter_map(|v| v.as_str().map(str::to_string))
                            .collect()
                    })
                    .unwrap_or_default();
                Column::Str(
                    items
                        .iter()
                        .map(|v| v.as_str().map(str::to_string))
                        .collect(),
                    levels,
                )
            }
        };
        columns.push((name.clone(), column));
    }
    Ok(Frame { columns })
}

/// The data frame of a case (bundled dataset or inline frame, subset applied).
fn case_frame(doc: &Value, case: &Value) -> Result<Frame, String> {
    let mut frame = if let Some(reference) = text(&case["data_ref"]) {
        inline_frame(&doc["data"][reference])?
    } else if let Some(dataset) = text(&case["dataset"]) {
        let mut frame = load_dataset(dataset)?;
        if let Some(factors) = case["factors"].as_object() {
            for (name, levels) in factors {
                let levels = levels
                    .as_array()
                    .map(|items| {
                        items
                            .iter()
                            .filter_map(|v| v.as_str().map(str::to_string))
                            .collect()
                    })
                    .unwrap_or_default();
                frame.set_levels(name, levels);
            }
        }
        frame
    } else {
        return unsupported("case has no data");
    };
    if let Some(rows) = case["rows"].as_array() {
        let indices: Vec<usize> = rows
            .iter()
            .map(|row| row.as_u64().map(|r| r as usize - 1).ok_or("bad row index"))
            .collect::<Result<_, _>>()?;
        frame = frame.subset(&indices);
    }
    Ok(frame)
}

// ---------------------------------------------------------------------------
// A small R formula reader (enough for the fixture formulas)
// ---------------------------------------------------------------------------

#[derive(Debug)]
struct Response {
    start: Option<Vec<f64>>,
    time: Vec<f64>,
    status: Vec<i32>,
}

/// Evaluate a `Surv(...)` response.  Supports `Surv(time, status)`,
/// `Surv(time, status == v)`, `Surv(start, stop, status)` and the R rule that a
/// 1/2 coded status means 2 = event.
fn response(formula: &str, frame: &Frame) -> Result<Response, String> {
    let lhs = formula.split('~').next().ok_or("formula without ~")?.trim();
    let inner = lhs
        .strip_prefix("Surv(")
        .and_then(|rest| rest.strip_suffix(')'))
        .ok_or_else(|| format!("unsupported: harness: response {lhs:?}"))?;
    let args: Vec<&str> = inner.split(',').map(str::trim).collect();
    if args.iter().any(|arg| arg.starts_with("type")) {
        return unsupported("harness: Surv(type=) responses");
    }
    let status_expr = *args.last().ok_or("empty Surv()")?;
    let status = status_column(status_expr, frame)?;
    match args.len() {
        2 => Ok(Response {
            start: None,
            time: frame.get(args[0])?.numeric(args[0])?,
            status,
        }),
        3 => Ok(Response {
            start: Some(frame.get(args[0])?.numeric(args[0])?),
            time: frame.get(args[1])?.numeric(args[1])?,
            status,
        }),
        _ => unsupported(format!("harness: Surv() with {} arguments", args.len())),
    }
}

fn status_column(expr: &str, frame: &Frame) -> Result<Vec<i32>, String> {
    if let Some((name, value)) = expr.split_once("==") {
        let column = frame.get(name.trim())?;
        let target = value.trim().trim_matches('"');
        return Ok((0..column.len())
            .map(|i| i32::from(column.label(i).as_deref() == Some(target)))
            .collect());
    }
    let values = frame.get(expr)?.numeric(expr)?;
    let max = values.iter().copied().fold(f64::MIN, f64::max);
    let min = values.iter().copied().fold(f64::MAX, f64::min);
    if min == 1.0 && max == 2.0 {
        return Ok(values.iter().map(|&v| i32::from(v == 2.0)).collect());
    }
    Ok(values.iter().map(|&v| i32::from(v != 0.0)).collect())
}

fn rhs_terms(formula: &str) -> Vec<String> {
    formula
        .split_once('~')
        .map(|(_, rhs)| rhs)
        .unwrap_or("")
        .split('+')
        .map(|term| term.trim().to_string())
        .filter(|term| !term.is_empty())
        .collect()
}

/// Rows grouped by the levels of a single column, in R's strata order.
fn groups_by_column(column: &Column) -> Vec<(String, Vec<usize>)> {
    column
        .levels()
        .into_iter()
        .map(|level| {
            let rows = (0..column.len())
                .filter(|&i| column.label(i).as_deref() == Some(level.as_str()))
                .collect();
            (level, rows)
        })
        .collect()
}

/// Treatment-contrast design matrix for `+`-separated terms: numeric
/// columns, `log(x)`, factor/character columns (R level order), `factor(x)`.
/// Returns (column names, rows, strata codes, offset).
struct Design {
    names: Vec<String>,
    rows: Vec<Vec<f64>>,
    strata: Option<Vec<i32>>,
    offset: Option<Vec<f64>>,
}

fn design(formula: &str, frame: &Frame) -> Result<Design, String> {
    let n = frame.nrow();
    let mut names = Vec::new();
    let mut columns: Vec<Vec<f64>> = Vec::new();
    let mut strata = None;
    let mut offset = None;
    for term in rhs_terms(formula) {
        if term == "1" {
            continue;
        }
        if let Some(inner) = term
            .strip_prefix("strata(")
            .and_then(|t| t.strip_suffix(')'))
        {
            let column = frame.get(inner)?;
            let levels = column.levels();
            let codes = (0..n)
                .map(|i| {
                    column
                        .label(i)
                        .and_then(|label| levels.iter().position(|l| *l == label))
                        .map_or(-1, |p| p as i32)
                })
                .collect();
            strata = Some(codes);
            continue;
        }
        if let Some(inner) = term
            .strip_prefix("offset(")
            .and_then(|t| t.strip_suffix(')'))
        {
            offset = Some(frame.get(inner)?.numeric(inner)?);
            continue;
        }
        if term.starts_with("cluster(") {
            continue;
        }
        if term.contains(':') || term.contains('*') || term.contains("tt(") {
            return unsupported(format!("harness: formula term {term}"));
        }
        if let Some(inner) = term.strip_prefix("log(").and_then(|t| t.strip_suffix(')')) {
            let values = frame.get(inner)?.numeric(inner)?;
            names.push(term.clone());
            columns.push(values.iter().map(|v| v.ln()).collect());
            continue;
        }
        let (column_name, force_factor) = match term
            .strip_prefix("factor(")
            .and_then(|t| t.strip_suffix(')'))
        {
            Some(inner) => (inner.to_string(), true),
            None => (term.clone(), false),
        };
        let column = frame.get(&column_name)?;
        match column {
            Column::Num(values) if !force_factor => {
                names.push(term.clone());
                columns.push(values.clone());
            }
            _ => {
                let levels = column.levels();
                for level in levels.iter().skip(1) {
                    names.push(format!("{term}{level}"));
                    columns.push(
                        (0..n)
                            .map(|i| f64::from(column.label(i).as_deref() == Some(level.as_str())))
                            .collect(),
                    );
                }
            }
        }
    }
    let rows = (0..n)
        .map(|i| columns.iter().map(|column| column[i]).collect())
        .collect();
    Ok(Design {
        names,
        rows,
        strata,
        offset,
    })
}

impl Design {
    /// Prepend R's `(Intercept)` column of ones.
    fn with_intercept(mut self) -> Self {
        self.names.insert(0, "(Intercept)".to_string());
        for row in &mut self.rows {
            row.insert(0, 1.0);
        }
        self
    }
}

/// R keeps an intercept unless the formula removes it with `- 1` or `+ 0`.
fn formula_has_intercept(formula: &str) -> bool {
    let rhs: String = formula
        .split_once('~')
        .map(|(_, rhs)| rhs)
        .unwrap_or("")
        .chars()
        .filter(|c| !c.is_whitespace())
        .collect();
    !(rhs.contains("-1") || rhs == "0" || rhs.starts_with("0+") || rhs.contains("+0"))
}

fn complete_rows(response: &Response, design: &Design, extra: &[Option<&[f64]>]) -> Vec<usize> {
    (0..response.time.len())
        .filter(|&i| {
            response.time[i].is_finite()
                && response.start.as_ref().is_none_or(|s| s[i].is_finite())
                && design.rows[i].iter().all(|v| v.is_finite())
                && design.strata.as_ref().is_none_or(|s| s[i] >= 0)
                && design.offset.as_ref().is_none_or(|o| o[i].is_finite())
                && extra
                    .iter()
                    .all(|column| column.is_none_or(|c| c[i].is_finite()))
        })
        .collect()
}

fn pick<T: Copy>(values: &[T], rows: &[usize]) -> Vec<T> {
    rows.iter().map(|&i| values[i]).collect()
}

fn arg_nums(case: &Value, name: &str) -> Option<Vec<f64>> {
    let value = &case["args"][name];
    if value.is_null() {
        None
    } else {
        nums(value).ok()
    }
}

// ---------------------------------------------------------------------------
// survfit_km: Kaplan-Meier curves
// ---------------------------------------------------------------------------

fn km_config(case: &Value) -> Result<KaplanMeierConfig, String> {
    let args = &case["args"];
    for key in [
        "type",
        "stype",
        "ctype",
        "conf.lower",
        "start.time",
        "cluster",
        "id",
        "time0",
    ] {
        if !args[key].is_null() {
            return unsupported(format!("survfit argument {key}"));
        }
    }
    let conf_type = match text(&args["conf.type"]) {
        None | Some("log") => "log",
        Some("log-log") => "log-log",
        Some("plain") => "plain",
        Some(other) => return unsupported(format!("conf.type {other}")),
    };
    let conf_level = args["conf.int"].as_f64().unwrap_or(0.95);
    KaplanMeierConfig::create(None, None, Some(conf_level), Some(conf_type.to_string()))
        .map_err(|err| format!("config: {err:?}"))
}

fn check_km_curve(output: &SurvFitKMOutput, curve: &Value, aspect: &str) -> Result<(), String> {
    let path = format!("curve[{}]", text(&curve["name"]).unwrap_or("?"));
    let absent = |field: &str| curve[field].is_null();
    match aspect {
        "std_err" | "std_chaz" | "conf"
            if absent(if aspect == "conf" { "lower" } else { aspect }) =>
        {
            Ok(())
        }
        "time_counts" => {
            assert_vec(
                &output.time,
                &nums(&curve["time"])?,
                0.0,
                &format!("{path}.time"),
            )?;
            assert_vec(
                &output.n_risk,
                &nums(&curve["n_risk"])?,
                0.0,
                &format!("{path}.n_risk"),
            )?;
            assert_vec(
                &output.n_event,
                &nums(&curve["n_event"])?,
                0.0,
                &format!("{path}.n_event"),
            )?;
            assert_vec(
                &output.n_censor,
                &nums(&curve["n_censor"])?,
                0.0,
                &format!("{path}.n_censor"),
            )
        }
        "surv" => assert_vec(
            &output.estimate,
            &nums(&curve["surv"])?,
            RTOL_COEF,
            &format!("{path}.surv"),
        ),
        "std_err" => assert_vec(
            &output.std_err,
            &nums(&curve["std_err"])?,
            RTOL_VAR,
            &format!("{path}.std_err"),
        ),
        "cumhaz" => assert_vec(
            &output.cumhaz,
            &nums(&curve["cumhaz"])?,
            RTOL_COEF,
            &format!("{path}.cumhaz"),
        ),
        "std_chaz" => assert_vec(
            &output.std_chaz,
            &nums(&curve["std_chaz"])?,
            RTOL_VAR,
            &format!("{path}.std_chaz"),
        ),
        "conf" => {
            if curve["lower"].is_null() {
                return Ok(());
            }
            assert_vec(
                &output.conf_lower,
                &nums(&curve["lower"])?,
                RTOL_VAR,
                &format!("{path}.lower"),
            )?;
            assert_vec(
                &output.conf_upper,
                &nums(&curve["upper"])?,
                RTOL_VAR,
                &format!("{path}.upper"),
            )
        }
        other => unsupported(format!("aspect {other}")),
    }
}

const KM_ASPECTS: &[&str] = &[
    "time_counts",
    "surv",
    "std_err",
    "cumhaz",
    "std_chaz",
    "conf",
];

#[test]
fn r_fixtures_survfit_km() {
    let doc = load_topic("survfit_km");
    let mut report = Report::new("survfit_km");
    for case in doc["cases"].as_array().expect("cases") {
        let name = text(&case["name"]).expect("case name");
        let prepared = (|| -> Result<(Vec<SurvFitKMOutput>, Vec<Value>), String> {
            let frame = case_frame(&doc, case)?;
            let formula = text(&case["formula"]).ok_or("no formula")?;
            let config = km_config(case)?;
            let response = response(formula, &frame)?;
            let weights = arg_nums(case, "weights").unwrap_or_else(|| vec![1.0; frame.nrow()]);
            let timefix = !matches!(case["args"]["timefix"].as_bool(), Some(false));
            let terms = rhs_terms(formula);
            let groups: Vec<(String, Vec<usize>)> = match terms.as_slice() {
                [term] if term == "1" => vec![("1".to_string(), (0..frame.nrow()).collect())],
                [term] => groups_by_column(frame.get(term)?),
                _ => return unsupported("harness: survfit with several grouping terms"),
            };
            let curves = case["expected"]["fit"]["curves"]
                .as_array()
                .ok_or("no curves")?;
            if curves.len() != groups.len() {
                return Err(format!(
                    "{} R curves but {} groups",
                    curves.len(),
                    groups.len()
                ));
            }
            let outputs: Vec<_> = groups
                .iter()
                .map(|(_, rows)| {
                    let status: Vec<f64> = pick(&response.status, rows)
                        .into_iter()
                        .map(f64::from)
                        .collect();
                    let entry = response.start.as_ref().map(|start| pick(start, rows));
                    compute_survfitkm_with_timefix(
                        &pick(&response.time, rows),
                        &status,
                        &pick(&weights, rows),
                        entry.as_deref(),
                        &vec![0; rows.len()],
                        &config,
                        timefix,
                    )
                })
                .collect();
            Ok((outputs, curves.clone()))
        })();
        match prepared {
            Err(message) => {
                for aspect in KM_ASPECTS {
                    report.record(name, aspect, Err(message.clone()));
                }
            }
            Ok((outputs, curves)) => {
                for aspect in KM_ASPECTS {
                    let result = outputs
                        .iter()
                        .zip(&curves)
                        .try_for_each(|(output, curve)| check_km_curve(output, curve, aspect));
                    report.record(name, aspect, result);
                }
            }
        }
    }
    report.finish();
}

// ---------------------------------------------------------------------------
// survdiff
// ---------------------------------------------------------------------------

#[test]
fn r_fixtures_survdiff() {
    let doc = load_topic("survdiff");
    let mut report = Report::new("survdiff");
    for case in doc["cases"].as_array().expect("cases") {
        let name = text(&case["name"]).expect("case name");
        let result = (|| -> Result<_, String> {
            let frame = case_frame(&doc, case)?;
            let formula = text(&case["formula"]).ok_or("no formula")?;
            let response = response(formula, &frame)?;
            if response.start.is_some() {
                return unsupported("counting-process survdiff");
            }
            let mut group_term = None;
            let mut strata_term = None;
            for term in rhs_terms(formula) {
                if let Some(inner) = term
                    .strip_prefix("strata(")
                    .and_then(|t| t.strip_suffix(')'))
                {
                    strata_term = Some(inner.to_string());
                } else if term.starts_with("offset(") {
                    return unsupported("one-sample survdiff against survexp");
                } else if group_term.replace(term).is_some() {
                    return unsupported("harness: several grouping terms");
                }
            }
            let group_column = frame.get(&group_term.ok_or("no group term")?)?;
            let group_levels = group_column.levels();
            let mut rows: Vec<usize> = (0..frame.nrow())
                .filter(|&i| group_column.label(i).is_some() && response.time[i].is_finite())
                .collect();
            let strata_codes: Option<Vec<i32>> = match &strata_term {
                Some(term) => {
                    let column = frame.get(term)?;
                    let levels = column.levels();
                    rows.retain(|&i| column.label(i).is_some());
                    rows.sort_by_key(|&i| {
                        levels
                            .iter()
                            .position(|l| Some(l.as_str()) == column.label(i).as_deref())
                    });
                    let codes: Vec<i32> = rows
                        .iter()
                        .map(|&i| {
                            levels
                                .iter()
                                .position(|l| Some(l.as_str()) == column.label(i).as_deref())
                                .map_or(0, |p| p as i32)
                        })
                        .collect();
                    // stratum end markers
                    Some(
                        (0..codes.len())
                            .map(|k| i32::from(k + 1 == codes.len() || codes[k + 1] != codes[k]))
                            .collect(),
                    )
                }
                None => None,
            };
            let group: Vec<i32> = rows
                .iter()
                .map(|&i| {
                    group_levels
                        .iter()
                        .position(|l| Some(l.as_str()) == group_column.label(i).as_deref())
                        .map_or(0, |p| p as i32 + 1)
                })
                .collect();
            let rho = case["args"]["rho"].as_f64();
            let fit = survdiff2(
                pick(&response.time, &rows),
                pick(&response.status, &rows),
                group,
                strata_codes,
                rho,
                Some(true),
            )
            .map_err(|err| format!("survdiff2: {err:?}"))?;
            Ok(fit)
        })();
        let expected = &case["expected"];
        match result {
            Err(message) => {
                for aspect in ["counts", "var", "chisq"] {
                    report.record(name, aspect, Err(message.clone()));
                }
            }
            Ok(fit) => {
                let counts = (|| {
                    // With strata R reports group x stratum matrices; the kernel
                    // returns the totals over strata.
                    let totals = |value: &Value| -> Result<Vec<f64>, String> {
                        if value
                            .as_array()
                            .is_some_and(|v| v.first().is_some_and(Value::is_array))
                        {
                            Ok(matrix(value)?.iter().map(|row| row.iter().sum()).collect())
                        } else {
                            nums(value)
                        }
                    };
                    assert_vec(&fit.observed, &totals(&expected["obs"])?, 1e-12, "obs")?;
                    assert_vec(&fit.expected, &totals(&expected["exp"])?, RTOL_COEF, "exp")
                })();
                report.record(name, "counts", counts);
                let var = (|| {
                    let expected_var = &expected["var"];
                    if expected_var
                        .as_array()
                        .is_some_and(|v| v.first().is_some_and(Value::is_array))
                    {
                        assert_matrix(&fit.variance, &matrix(expected_var)?, RTOL_VAR, "var")
                    } else {
                        let flat: Vec<f64> = fit.variance.iter().flatten().copied().collect();
                        assert_vec(&flat, &nums(expected_var)?, RTOL_VAR, "var")
                    }
                })();
                report.record(name, "var", var);
                let chisq = (|| {
                    assert_scalar(fit.chi_squared, num(&expected["chisq"])?, RTOL_VAR, "chisq")
                })();
                report.record(name, "chisq", chisq);
            }
        }
    }
    report.finish();
}

// ---------------------------------------------------------------------------
// coxph
// ---------------------------------------------------------------------------

struct CoxCase {
    fit: CoxPHFit,
    names: Vec<String>,
}

fn cox_fit_for_case(doc: &Value, case: &Value) -> Result<CoxCase, String> {
    let frame = case_frame(doc, case)?;
    let formula = text(&case["formula"]).ok_or("no formula")?;
    let args = &case["args"];
    if !args["tt"].is_null() {
        return unsupported("coxph argument tt (time-transform terms)");
    }
    let control = &args["control"];
    let max_iter = control["iter.max"].as_u64().map(|v| v as usize);
    let eps = control["eps"].as_f64();
    let initial_beta = arg_nums(case, "init");
    let response = response(formula, &frame)?;
    let design = design(formula, &frame)?;
    if design.names.is_empty() {
        return unsupported("null model");
    }
    let weights = arg_nums(case, "weights");
    let rows = complete_rows(&response, &design, &[weights.as_deref()]);
    let method = match text(&args["ties"]) {
        None => "efron",
        Some(other) => other,
    };
    // R's default nocenter = c(-1, 0, 1); `nocenter = NULL` centres every column.
    let nocenter = if args.as_object().is_some_and(|o| o.contains_key("nocenter")) {
        Some(Vec::new())
    } else {
        Some(vec![-1.0, 0.0, 1.0])
    };
    let fit = coxph_fit(
        pick(&response.time, &rows),
        pick(&response.status, &rows),
        rows.iter().map(|&i| design.rows[i].clone()).collect(),
        design.strata.as_ref().map(|s| pick(s, &rows)),
        weights.as_ref().map(|w| pick(w, &rows)),
        design.offset.as_ref().map(|o| pick(o, &rows)),
        initial_beta,
        max_iter,
        eps,
        None,
        Some(method),
        response.start.as_ref().map(|s| pick(s, &rows)),
        nocenter,
    )
    .map_err(|err| format!("coxph_fit: {err:?}"))?;
    Ok(CoxCase {
        fit,
        names: design.names,
    })
}

fn cox_beta(fit: &CoxPHFit) -> Vec<f64> {
    fit.coefficients.first().cloned().unwrap_or_default()
}

const COX_CORE_ASPECTS: &[&str] = &[
    "coef",
    "coef_names",
    "var",
    "loglik",
    "score",
    "iter",
    "means",
    "linear_predictors",
    "residuals.martingale",
    "residuals.deviance",
];

fn check_cox_aspect(cox: &CoxCase, expected: &Value, aspect: &str) -> Result<(), String> {
    let fit = &cox.fit;
    match aspect {
        "coef" => assert_vec(
            &cox_beta(fit),
            &named_values(&expected["coef"], &expected["coef_names"])?,
            RTOL_COEF,
            "coef",
        ),
        "coef_names" => {
            let r_names = names_of(&expected["coef_names"]);
            if cox
                .names
                .iter()
                .map(String::as_str)
                .ne(r_names.iter().copied())
            {
                return Err(format!("coef names {:?} != {:?}", cox.names, r_names));
            }
            Ok(())
        }
        "var" => {
            if !expected["naive_var"].is_null() {
                return unsupported("robust variance");
            }
            assert_matrix(
                &fit.information_matrix,
                &matrix(&expected["var"])?,
                RTOL_VAR,
                "var",
            )
        }
        "loglik" => assert_vec(
            &fit.log_likelihood,
            &nums(&expected["loglik"])?,
            RTOL_COEF,
            "loglik",
        ),
        "score" => assert_scalar(fit.score_test, num(&expected["score"])?, RTOL_VAR, "score"),
        "iter" => assert_scalar(
            fit.iterations as f64,
            nums(&expected["iter"])?[0],
            0.0,
            "iter",
        ),
        "means" => assert_vec(&fit.means, &nums(&expected["means"])?, RTOL_COEF, "means"),
        "linear_predictors" => assert_vec(
            &fit.linear_predictors,
            &nums(&expected["linear_predictors"])?,
            RTOL_COEF,
            "linear_predictors",
        ),
        "residuals.martingale" => {
            let expected = &expected["residuals"]["martingale"];
            if is_r_error(expected) {
                return Ok(());
            }
            let actual = fit.martingale_residuals().map_err(|e| format!("{e:?}"))?;
            assert_vec(&actual, &nums(expected)?, RTOL_COEF, "martingale")
        }
        "residuals.deviance" => {
            let expected = &expected["residuals"]["deviance"];
            if is_r_error(expected) {
                return Ok(());
            }
            let actual = fit.deviance_residuals().map_err(|e| format!("{e:?}"))?;
            assert_vec(&actual, &nums(expected)?, RTOL_COEF, "deviance")
        }
        other => unsupported(format!("aspect {other}")),
    }
}

#[test]
fn r_fixtures_coxph() {
    let doc = load_topic("coxph");
    let mut report = Report::new("coxph");
    for case in doc["cases"].as_array().expect("cases") {
        let name = text(&case["name"]).expect("case name");
        if !case["formulas"].is_null() {
            continue;
        }
        let expected = &case["expected"];
        match cox_fit_for_case(&doc, case) {
            Err(message) => {
                for aspect in COX_CORE_ASPECTS {
                    report.record(name, aspect, Err(message.clone()));
                }
            }
            Ok(cox) => {
                for aspect in COX_CORE_ASPECTS {
                    if aspect.starts_with("residuals.") && expected["residuals"].is_null() {
                        continue;
                    }
                    if *aspect == "linear_predictors" && expected["linear_predictors"].is_null() {
                        continue;
                    }
                    report.record(name, aspect, check_cox_aspect(&cox, expected, aspect));
                }
            }
        }
    }
    report.finish();
}

const COX_DIAGNOSTIC_RESIDUALS: &[&str] = &[
    "score",
    "schoenfeld",
    "scaledsch",
    "dfbeta",
    "dfbetas",
    "partial",
];

#[test]
fn r_fixtures_coxph_diagnostics() {
    let doc = load_topic("coxph_diagnostics");
    let mut report = Report::new("coxph_diagnostics");
    for case in doc["cases"].as_array().expect("cases") {
        let name = text(&case["name"]).expect("case name");
        let expected = &case["expected"]["residuals"];
        let cox = cox_fit_for_case(&doc, case);
        for kind in COX_DIAGNOSTIC_RESIDUALS {
            let value = &expected[kind];
            if value.is_null() || is_r_error(value) {
                continue;
            }
            let aspect = format!("residuals.{kind}");
            let result = match &cox {
                Err(message) => Err(message.clone()),
                Ok(cox) => (|| {
                    let actual = match *kind {
                        "score" => cox.fit.score_residuals(),
                        "schoenfeld" => cox.fit.schoenfeld_residuals(),
                        "scaledsch" => cox.fit.scaled_schoenfeld_residuals(),
                        "dfbeta" => cox.fit.dfbeta(),
                        "dfbetas" => cox.fit.dfbetas(),
                        "partial" => cox.fit.partial_residuals(),
                        _ => unreachable!(),
                    }
                    .map_err(|e| format!("{e:?}"))?;
                    let expected_matrix = if value.is_object() {
                        matrix(&value["values"])?
                    } else {
                        matrix(value)?
                    };
                    assert_matrix(&actual, &expected_matrix, RTOL_COEF, kind)
                })(),
            };
            report.record(name, &aspect, result);
        }
    }
    report.finish();
}

// ---------------------------------------------------------------------------
// survreg
// ---------------------------------------------------------------------------

#[test]
fn r_fixtures_survreg() {
    let doc = load_topic("survreg");
    let mut report = Report::new("survreg");
    for case in doc["cases"].as_array().expect("cases") {
        let name = text(&case["name"]).expect("case name");
        if name == "distribution_functions" {
            continue;
        }
        let expected = &case["expected"];
        let fit = (|| -> Result<_, String> {
            let frame = case_frame(&doc, case)?;
            let formula = text(&case["formula"]).ok_or("no formula")?;
            let args = &case["args"];
            for key in ["init", "robust", "x", "parms"] {
                if !args[key].is_null() {
                    return unsupported(format!("survreg argument {key}"));
                }
            }
            let response = response(formula, &frame)?;
            if response.start.is_some() {
                return unsupported("counting-process survreg");
            }
            // R's survreg fits an intercept (the kernel takes the design
            // matrix as given), so add the column of ones R would.
            let mut design = design(formula, &frame)?;
            if formula_has_intercept(formula) {
                design = design.with_intercept();
            }
            if design.offset.is_some() {
                return unsupported("offset");
            }
            let weights = arg_nums(case, "weights");
            let rows = complete_rows(&response, &design, &[weights.as_deref()]);
            let strata = design.strata.as_ref().map(|s| {
                pick(s, &rows)
                    .into_iter()
                    .map(|code| code as usize)
                    .collect::<Vec<usize>>()
            });
            let dist = text(&args["dist"]).unwrap_or("weibull");
            let fixed_scale = args["scale"].as_f64().filter(|s| *s > 0.0);
            let fit = survreg(
                pick(&response.time, &rows),
                pick(&response.status, &rows)
                    .into_iter()
                    .map(f64::from)
                    .collect(),
                rows.iter().map(|&i| design.rows[i].clone()).collect(),
                weights.as_ref().map(|w| pick(w, &rows)),
                None,
                None,
                strata,
                Some(dist),
                None,
                None,
                None,
                None,
                fixed_scale,
                None,
            )
            .map_err(|err| format!("survreg: {err:?}"))?;
            Ok(fit)
        })();
        let aspects = ["coef", "scale", "loglik", "var", "linear_predictors"];
        match fit {
            Err(message) => {
                for aspect in aspects {
                    report.record(name, aspect, Err(message.clone()));
                }
            }
            Ok(fit) => {
                // R's coef is the location part only ((Intercept), terms...);
                // the scale is reported separately.
                report.record(
                    name,
                    "coef",
                    (|| {
                        assert_vec(
                            &fit.location_coefficients,
                            &named_values(&expected["coef"], &expected["coef_names"])?,
                            RTOL_COEF,
                            "coef",
                        )
                    })(),
                );
                report.record(
                    name,
                    "scale",
                    (|| {
                        let scales = nums(&expected["scale"])?;
                        if scales.len() == 1 {
                            assert_scalar(fit.scale, scales[0], RTOL_COEF, "scale")
                        } else {
                            assert_vec(&fit.scales, &scales, RTOL_COEF, "scale")
                        }
                    })(),
                );
                report.record(
                    name,
                    "loglik",
                    (|| {
                        let loglik = nums(&expected["loglik"])?;
                        assert_scalar(fit.log_likelihood, loglik[1], RTOL_COEF, "loglik")
                    })(),
                );
                report.record(
                    name,
                    "var",
                    (|| {
                        // R's var is the full (coefficients, Log(scale) per
                        // stratum) block; the kernel lays it out the same way.
                        assert_matrix(
                            &fit.variance_matrix,
                            &matrix(&expected["var"])?,
                            RTOL_VAR,
                            "var",
                        )
                    })(),
                );
                report.record(
                    name,
                    "linear_predictors",
                    (|| {
                        assert_vec(
                            &fit.linear_predictors,
                            &nums(&expected["linear_predictors"])?,
                            RTOL_COEF,
                            "linear_predictors",
                        )
                    })(),
                );
            }
        }
    }
    report.finish();
}

// ---------------------------------------------------------------------------
// concordance (right-censored, single numeric score)
// ---------------------------------------------------------------------------

#[test]
fn r_fixtures_concordance() {
    use crate::concordance::basic::{concordance_index, counting_concordance_index};
    let doc = load_topic("concordance");
    let mut report = Report::new("concordance");
    for case in doc["cases"].as_array().expect("cases") {
        let name = text(&case["name"]).expect("case name");
        let expected = &case["expected"];
        let result = (|| -> Result<(), String> {
            if expected["coxph"].is_object() {
                return unsupported("concordance of fitted models");
            }
            let frame = case_frame(&doc, case)?;
            let formula = text(&case["formula"]).ok_or("no formula")?;
            let args = &case["args"];
            for key in ["ranks", "influence"] {
                if !args[key].is_null() {
                    return unsupported(format!("concordance_index has no {key} output"));
                }
            }
            if !formula.trim_start().starts_with("Surv(") {
                return unsupported("harness: numeric (uncensored) response");
            }
            let response = response(formula, &frame)?;
            let terms = rhs_terms(formula);
            let score_term = match terms.as_slice() {
                [term] if !term.starts_with("strata(") => term.clone(),
                _ => return unsupported("harness: several terms or strata"),
            };
            if score_term.contains('(') {
                return unsupported(format!("harness: term {score_term}"));
            }
            let scores = frame.get(&score_term)?.numeric(&score_term)?;
            let weights = arg_nums(case, "weights");
            let rows: Vec<usize> = (0..frame.nrow())
                .filter(|&i| scores[i].is_finite() && response.time[i].is_finite())
                .collect();
            let reverse = is_true(&args["reverse"]);
            let timewt = text(&args["timewt"]).unwrap_or("n").to_string();
            // R's default is concordance of y with x; reverse = TRUE treats x
            // as a risk score, which is what concordance_index computes.
            let risk: Vec<f64> = pick(&scores, &rows)
                .into_iter()
                .map(|s| if reverse { s } else { -s })
                .collect();
            let actual = match &response.start {
                Some(start) => counting_concordance_index(
                    pick(start, &rows),
                    pick(&response.time, &rows),
                    pick(&response.status, &rows),
                    risk,
                    weights.map(|w| pick(&w, &rows)),
                    timewt,
                    Some(true),
                )
                .map_err(|err| format!("counting_concordance_index: {err:?}"))?,
                None => concordance_index(
                    pick(&response.time, &rows),
                    pick(&response.status, &rows),
                    risk,
                    weights.map(|w| pick(&w, &rows)),
                    timewt,
                )
                .map_err(|err| format!("concordance_index: {err:?}"))?,
            };
            assert_scalar(
                actual,
                nums(&expected["concordance"])?[0],
                RTOL_COEF,
                "concordance",
            )
        })();
        report.record(name, "concordance", result);
    }
    report.finish();
}

// ---------------------------------------------------------------------------
// data_prep: neardate, aeqSurv
// ---------------------------------------------------------------------------

#[test]
fn r_fixtures_data_prep() {
    use crate::data_prep::{aeq_surv, neardate};
    let mut report = Report::new("data_prep");

    let doc = load_topic("neardate");
    for case in doc["cases"].as_array().expect("cases") {
        let name = text(&case["name"]).expect("case name");
        let args = &case["args"];
        for (aspect, best, nomatch) in [
            ("after", "after", f64::NAN),
            ("prior", "prior", f64::NAN),
            ("after_nomatch0", "after", 0.0),
            ("prior_nomatch0", "prior", 0.0),
        ] {
            let result = (|| -> Result<(), String> {
                let id1: Vec<i64> = nums(&args["id1"])?.into_iter().map(|v| v as i64).collect();
                let id2: Vec<i64> = nums(&args["id2"])?.into_iter().map(|v| v as i64).collect();
                let out = neardate(
                    id1,
                    nums(&args["y1"])?,
                    id2,
                    nums(&args["y2"])?,
                    Some(best),
                    None,
                )
                .map_err(|err| format!("neardate: {err:?}"))?;
                // R returns 1-based row numbers, and `nomatch` where there is none.
                let actual: Vec<f64> = out
                    .indices
                    .iter()
                    .map(|idx| idx.map_or(nomatch, |i| i as f64 + 1.0))
                    .collect();
                assert_vec(&actual, &nums(&case["expected"][aspect])?, 0.0, aspect)
            })();
            report.record(name, aspect, result);
        }
    }

    let doc = load_topic("utilities");
    for case in doc["cases"].as_array().expect("cases") {
        let name = text(&case["name"]).expect("case name");
        if name != "aeqSurv" {
            continue;
        }
        let args = &case["args"];
        for (aspect, time_key, tolerance) in [
            ("right_1e9", "time2", None),
            ("right_1e9_tol_1e8", "time2", Some(1e-8)),
        ] {
            let result = (|| -> Result<(), String> {
                let out = aeq_surv(nums(&args[time_key])?, tolerance)
                    .map_err(|err| format!("aeq_surv: {err:?}"))?;
                let expected = matrix(&case["expected"][aspect]["values"])?;
                let expected_time: Vec<f64> = expected.iter().map(|row| row[0]).collect();
                assert_vec(&out.time, &expected_time, 1e-15, aspect)
            })();
            report.record(name, aspect, result);
        }
    }

    report.finish();
}

// ---------------------------------------------------------------------------
// Sanity checks on the harness itself
// ---------------------------------------------------------------------------

#[test]
fn r_fixture_files_have_metadata() {
    let dir = manifest_path("test/r/fixtures");
    let mut topics: BTreeMap<String, usize> = BTreeMap::new();
    for entry in std::fs::read_dir(&dir).expect("fixture dir") {
        let path = entry.expect("entry").path();
        if path.extension().is_some_and(|ext| ext == "json") {
            let doc: Value =
                serde_json::from_str(&std::fs::read_to_string(&path).expect("read")).expect("json");
            assert!(doc["metadata"]["survival_version"].is_string(), "{path:?}");
            let n_cases = doc["cases"].as_array().map_or(0, Vec::len);
            assert_eq!(
                n_cases,
                doc["n_cases"].as_u64().unwrap_or(0) as usize,
                "{path:?}"
            );
            topics.insert(doc["topic"].as_str().unwrap_or("").to_string(), n_cases);
        }
    }
    assert!(topics.contains_key("survfit_km"));
    assert!(topics.contains_key("coxph"));
}

#[test]
fn known_failures_are_well_formed() {
    let mut seen = std::collections::HashSet::new();
    for (id, reason) in KNOWN_FAILURES {
        assert!(!reason.is_empty(), "{id} has no reason");
        assert!(
            id.matches('/').count() >= 1,
            "{id} must be topic/case[/aspect]"
        );
        assert!(seen.insert(*id), "{id} is listed twice");
    }
}

#[test]
fn comparison_floor_is_scaled_to_the_vector() {
    // Noise around zero next to O(1) entries is within rtol * max|expected|.
    assert!(assert_vec(&[1.0, 0.0, -2.0], &[1.0, -1.2e-17, -2.0], 1e-8, "v").is_ok());
    assert!(
        assert_matrix(
            &[vec![0.0, 1.0], vec![1e-15, 0.0]],
            &[vec![0.0, 1.0], vec![0.0, 0.0]],
            1e-8,
            "m"
        )
        .is_ok()
    );
    // A difference of the same size in a vector of tiny values, or a real
    // difference, is still reported; scalars keep a pure relative tolerance.
    assert!(assert_vec(&[1e-17, 0.0], &[1e-17, 1e-17], 1e-8, "v").is_err());
    assert!(assert_vec(&[1.0, 1e-7], &[1.0, 0.0], 1e-8, "v").is_err());
    assert!(assert_scalar(1e-17, 0.0, 1e-8, "s").is_err());
    // Exact comparisons keep a zero floor.
    assert!(assert_vec(&[3.0, 1e-17], &[3.0, 0.0], 0.0, "v").is_err());
    // NaN and infinities only match themselves.
    assert!(assert_vec(&[f64::NAN, 1.0], &[f64::NAN, 1.0], 1e-8, "v").is_ok());
    assert!(assert_vec(&[0.0], &[f64::NAN], 1e-8, "v").is_err());
    assert!(assert_vec(&[f64::INFINITY], &[f64::NEG_INFINITY], 1e-8, "v").is_err());
}

#[test]
fn formula_intercept_follows_r() {
    assert!(formula_has_intercept("Surv(time, status) ~ age + sex"));
    assert!(formula_has_intercept("Surv(time, status) ~ 1"));
    assert!(!formula_has_intercept("Surv(time, status) ~ age - 1"));
    assert!(!formula_has_intercept("Surv(time, status) ~ age + sex + 0"));
    assert!(!formula_has_intercept("Surv(time, status) ~ 0 + age"));
    let frame = inline_frame(&serde_json::json!({
        "nrow": 2,
        "columns": {"time": [1.0, 2.0], "status": [1, 0], "x": [0.5, 1.5]},
        "factors": {}
    }))
    .expect("frame");
    let design = design("Surv(time, status) ~ x", &frame)
        .expect("design")
        .with_intercept();
    assert_eq!(design.names, ["(Intercept)", "x"]);
    assert_eq!(design.rows, [vec![1.0, 0.5], vec![1.0, 1.5]]);
}
