//! Distribution queries follow the separate vector arithmetic operations in R.
//! Fitting retains its stronger shape and probability validation elsewhere.

use super::*;
use crate::regression::survreg_distributions::{
    SurvregDistribution, SurvregFamily, SurvregTransform,
};

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
pub(crate) enum QueryParms {
    #[default]
    Values,
    Missing,
    Null,
}

/// Conditions generated by R's distribution-query arithmetic. Rust callers can
/// use the warning-aware methods to observe them or stop at the emitting stage.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DpqrWarning {
    Recycling,
    NaNs,
}

impl DpqrWarning {
    pub fn message(self) -> &'static str {
        match self {
            Self::Recycling => "longer object length is not a multiple of shorter object length",
            Self::NaNs => "NaNs produced",
        }
    }
}

#[derive(Clone, Copy)]
enum TMath {
    Cdf,
    Upper,
    Density,
    Quantile,
}

fn is_r_na(value: f64) -> bool {
    value.is_nan() && value.to_bits() & 0x0007_ffff_ffff_ffff == 0x7a2
}

fn quiet(_: DpqrWarning) -> SurvivalResult<()> {
    Ok(())
}

// These ordinary shapes make all arithmetic stages the query's length and
// generate no recycling warnings. Avoid integer divisions in each output row.
fn matching_lengths(n: usize, mean: usize, scale: usize) -> bool {
    n != 0 && (mean == 1 || mean == n) && (scale == 1 || scale == n)
}

/// An arithmetic operation recycles its two operands independently. Empty
/// operands annihilate the result before the divisibility warning is considered.
fn binary_len<E>(
    a: usize,
    b: usize,
    warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
) -> Result<usize, E> {
    if a == 0 || b == 0 {
        return Ok(0);
    }
    if !a.max(b).is_multiple_of(a.min(b)) {
        warn(DpqrWarning::Recycling)?;
    }
    Ok(a.max(b))
}

// R's addition loops preserve the right missing operand for a nonscalar
// RHS. Multiplication additionally preserves the left operand for equal
// lengths. Retain NA versus NaN without depending on this compiler's
// floating-point instruction operand order.
#[derive(Clone, Copy)]
enum Arithmetic {
    Add,
    Subtract,
    Multiply,
    Divide,
}

#[inline]
fn arithmetic(a: f64, b: f64, op: Arithmetic, rhs_len: usize) -> f64 {
    if matches!(op, Arithmetic::Add | Arithmetic::Multiply) && rhs_len > 1 && b.is_nan() {
        b
    } else if a.is_nan() {
        a
    } else if b.is_nan() {
        b
    } else {
        match op {
            Arithmetic::Add => a + b,
            Arithmetic::Subtract => a - b,
            Arithmetic::Multiply => a * b,
            Arithmetic::Divide => a / b,
        }
    }
}

#[inline]
fn multiply(a: f64, b: f64, lhs_len: usize, rhs_len: usize) -> f64 {
    arithmetic(
        a,
        b,
        Arithmetic::Multiply,
        if lhs_len == rhs_len { 1 } else { rhs_len },
    )
}

fn binary_owned<E>(
    mut a: Vec<f64>,
    b: &[f64],
    op: Arithmetic,
    warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
) -> Result<Vec<f64>, E> {
    let n = binary_len(a.len(), b.len(), warn)?;
    let rhs_priority = if matches!(op, Arithmetic::Multiply) && a.len() == b.len() {
        1
    } else {
        b.len()
    };
    if n == 0 {
        a.clear();
        return Ok(a);
    }
    if n == a.len() {
        if b.len() == 1 {
            for value in &mut a {
                *value = arithmetic(*value, b[0], op, rhs_priority);
            }
        } else if b.len() == n {
            for (value, &right) in a.iter_mut().zip(b) {
                *value = arithmetic(*value, right, op, rhs_priority);
            }
        } else {
            for (i, value) in a.iter_mut().enumerate() {
                *value = arithmetic(*value, b[i % b.len()], op, rhs_priority);
            }
        }
        Ok(a)
    } else {
        Ok((0..n)
            .map(|i| arithmetic(a[i % a.len()], b[i % b.len()], op, rhs_priority))
            .collect())
    }
}

impl SurvregDistribution {
    /// Density queries with R's staged vector recycling, including nonfinite
    /// locations and zero or negative scales. Arithmetic warnings are ignored.
    pub fn pdf_values(&self, x: &[f64], mean: &[f64], scale: &[f64]) -> SurvivalResult<Vec<f64>> {
        self.pdf_values_with_warnings(x, mean, scale, &mut quiet)
    }

    /// CDF queries with R's staged vector recycling. Arithmetic warnings are ignored.
    pub fn cdf_values(&self, q: &[f64], mean: &[f64], scale: &[f64]) -> SurvivalResult<Vec<f64>> {
        self.cdf_values_with_warnings(q, mean, scale, &mut quiet)
    }

    /// Quantile queries with R's staged vector recycling. Arithmetic warnings are ignored.
    pub fn quantile_values(
        &self,
        p: &[f64],
        mean: &[f64],
        scale: &[f64],
    ) -> SurvivalResult<Vec<f64>> {
        self.quantile_values_with_warnings(p, mean, scale, &mut quiet)
    }

    /// As [`Self::pdf_values`], reporting warnings immediately at each stage.
    pub fn pdf_values_with_warnings<E: From<SurvivalError>>(
        &self,
        x: &[f64],
        mean: &[f64],
        scale: &[f64],
        warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
    ) -> Result<Vec<f64>, E> {
        self.probability_values_with_warnings(x, mean, scale, true, warn)
    }

    /// As [`Self::cdf_values`], reporting warnings immediately at each stage.
    pub fn cdf_values_with_warnings<E: From<SurvivalError>>(
        &self,
        q: &[f64],
        mean: &[f64],
        scale: &[f64],
        warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
    ) -> Result<Vec<f64>, E> {
        self.probability_values_with_warnings(q, mean, scale, false, warn)
    }

    fn probability_values_with_warnings<E: From<SurvivalError>>(
        &self,
        x: &[f64],
        mean: &[f64],
        scale: &[f64],
        density: bool,
        warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
    ) -> Result<Vec<f64>, E> {
        if self.simple_builtin_query() && self.transform_callbacks.is_none() {
            return self.builtin_probability_values(x, mean, scale, density, warn);
        }
        // R calls dtrans on the original query before trans, even for empty
        // batches or when later arithmetic will yield an empty result.
        let derivative = if density && self.transform != SurvregTransform::Identity {
            Some(self.query_derivatives(x).map_err(E::from)?)
        } else {
            None
        };
        let transformed = self.query_transform(x, warn)?;
        let centered = binary_owned(transformed, mean, Arithmetic::Subtract, warn)?;
        let endpoints = binary_owned(centered, scale, Arithmetic::Divide, warn)?;
        // Query functions select one density column. The other columns and
        // nonfinite rows need not satisfy the fitting likelihood contract.
        let selected = self.query_selected_density(&endpoints, density, warn)?;
        if density {
            let selected = if let Some(derivative) = derivative {
                binary_owned(selected, &derivative, Arithmetic::Multiply, warn)?
            } else {
                selected
            };
            binary_owned(selected, scale, Arithmetic::Divide, warn)
        } else {
            Ok(selected)
        }
    }

    /// As [`Self::quantile_values`], reporting warnings immediately at each stage.
    pub fn quantile_values_with_warnings<E: From<SurvivalError>>(
        &self,
        p: &[f64],
        mean: &[f64],
        scale: &[f64],
        warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
    ) -> Result<Vec<f64>, E> {
        if self.simple_builtin_query() && self.transform_callbacks.is_none() {
            self.quantile_warnings(p, warn)?;
            if let ([mean], [scale]) = (mean, scale)
                && mean.is_finite()
                && scale.is_finite()
            {
                return p
                    .iter()
                    .map(|&p| {
                        if p.is_nan() {
                            Ok(p)
                        } else {
                            self.transform
                                .inverse(self.builtin_quantile(p) * scale + mean)
                                .map_err(E::from)
                        }
                    })
                    .collect();
            }
            if matching_lengths(p.len(), mean.len(), scale.len()) {
                let p_len = p.len();
                return p
                    .iter()
                    .enumerate()
                    .map(|(i, &p)| {
                        let scale_value = scale[if scale.len() == 1 { 0 } else { i }];
                        let mean_value = mean[if mean.len() == 1 { 0 } else { i }];
                        self.query_inverse_one(arithmetic(
                            multiply(self.query_quantile_one(p), scale_value, p_len, scale.len()),
                            mean_value,
                            Arithmetic::Add,
                            mean.len(),
                        ))
                        .map_err(E::from)
                    })
                    .collect();
            }
            let multiplied = binary_len(p.len(), scale.len(), warn)?;
            let n = binary_len(multiplied, mean.len(), warn)?;
            return (0..n)
                .map(|i| {
                    let j = i % multiplied;
                    self.query_inverse_one(arithmetic(
                        multiply(
                            self.query_quantile_one(p[j % p.len()]),
                            scale[j % scale.len()],
                            p.len(),
                            scale.len(),
                        ),
                        mean[i % mean.len()],
                        Arithmetic::Add,
                        mean.len(),
                    ))
                    .map_err(E::from)
                })
                .collect();
        }
        let mut quantiles = if self.callbacks.is_some() || self.family == SurvregFamily::Custom {
            self.custom_callbacks()
                .map_err(E::from)?
                .quantile(p, &self.parms)
                .map_err(E::from)?
        } else if self.family == SurvregFamily::T {
            self.t_math_values(p, TMath::Quantile, warn)?
        } else {
            self.quantile_warnings(p, warn)?;
            p.iter().map(|&p| self.query_quantile_one(p)).collect()
        };
        let located = if matching_lengths(quantiles.len(), mean.len(), scale.len()) {
            // No callbacks or warning-producing stages intervene here. Both
            // operations retain length, so their per-element arithmetic fuses.
            let quantile_len = quantiles.len();
            for (i, value) in quantiles.iter_mut().enumerate() {
                *value = arithmetic(
                    multiply(
                        *value,
                        scale[if scale.len() == 1 { 0 } else { i }],
                        quantile_len,
                        scale.len(),
                    ),
                    mean[if mean.len() == 1 { 0 } else { i }],
                    Arithmetic::Add,
                    mean.len(),
                );
            }
            quantiles
        } else {
            let scaled = binary_owned(quantiles, scale, Arithmetic::Multiply, warn)?;
            binary_owned(scaled, mean, Arithmetic::Add, warn)?
        };
        if self.transform == SurvregTransform::Identity && self.transform_callbacks.is_none() {
            Ok(located)
        } else {
            self.query_inverse(&located).map_err(E::from)
        }
    }

    /// Random draws with R-compatible uniforms when a seed is supplied.
    /// Exactly `n` uniforms are drawn before quantile recycling, so the returned
    /// vector can be longer than `n` or empty when location/scale vectors require it.
    pub fn sample(
        &self,
        n: usize,
        mean: &[f64],
        scale: &[f64],
        seed: Option<i32>,
    ) -> SurvivalResult<Vec<f64>> {
        self.sample_with_warnings(n, mean, scale, seed, &mut quiet)
    }

    /// As [`Self::sample`], reporting warnings immediately at each stage.
    pub fn sample_with_warnings<E: From<SurvivalError>>(
        &self,
        n: usize,
        mean: &[f64],
        scale: &[f64],
        seed: Option<i32>,
        warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
    ) -> Result<Vec<f64>, E> {
        use crate::internal::rng::{RUniform, Rng};
        let uniform: Vec<_> = match seed {
            Some(i32::MIN) => {
                return Err(E::from(SurvivalError::invalid_input(
                    "supplied seed is not a valid integer",
                )));
            }
            Some(seed) => {
                let mut rng = RUniform::new(seed as u32);
                (0..n).map(|_| rng.unif_rand()).collect()
            }
            None => {
                let mut rng = Rng::new();
                (0..n).map(|_| rng.f64()).collect()
            }
        };
        self.quantile_values_with_warnings(&uniform, mean, scale, warn)
    }

    // Builtin queries can fuse all arithmetic stages without allocating their
    // intermediate vectors. Indexes compose through each stage's own length;
    // recycling every original operand by the final index would be incorrect.
    fn builtin_probability_values<E: From<SurvivalError>>(
        &self,
        x: &[f64],
        mean: &[f64],
        scale: &[f64],
        density: bool,
        warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
    ) -> Result<Vec<f64>, E> {
        self.transform_warnings(x, warn)?;
        if let ([mean], [scale]) = (mean, scale)
            && mean.is_finite()
            && scale.is_finite()
        {
            return x
                .iter()
                .map(|&x| {
                    self.finite_scalar_probability_one(x, *mean, *scale, density)
                        .map_err(E::from)
                })
                .collect();
        }
        if matching_lengths(x.len(), mean.len(), scale.len()) {
            let query_len = x.len();
            return x
                .iter()
                .enumerate()
                .map(|(i, &x)| {
                    self.query_probability_one(
                        x,
                        mean[if mean.len() == 1 { 0 } else { i }],
                        scale[if scale.len() == 1 { 0 } else { i }],
                        density,
                        query_len,
                    )
                    .map_err(E::from)
                })
                .collect();
        }
        let centered = binary_len(x.len(), mean.len(), warn)?;
        let standardized = binary_len(centered, scale.len(), warn)?;
        let derivative = density && self.transform != SurvregTransform::Identity;
        let multiplied = if derivative {
            binary_len(standardized, x.len(), warn)?
        } else {
            standardized
        };
        let n = if density {
            binary_len(multiplied, scale.len(), warn)?
        } else {
            standardized
        };
        (0..n)
            .map(|i| {
                let j = if density { i % multiplied } else { i };
                let k = if derivative { j % standardized } else { j };
                let l = k % centered;
                let tx = self.query_transform_one(x[l % x.len()]).map_err(E::from)?;
                let z = arithmetic(
                    arithmetic(tx, mean[l % mean.len()], Arithmetic::Subtract, 1),
                    scale[k % scale.len()],
                    Arithmetic::Divide,
                    1,
                );
                if density {
                    let y = if z.is_nan() {
                        z
                    } else {
                        self.base_pdf(z).map_err(E::from)?
                    };
                    let y = if derivative {
                        multiply(
                            y,
                            self.query_derivative_one(x[j % x.len()]).map_err(E::from)?,
                            standardized,
                            x.len(),
                        )
                    } else {
                        y
                    };
                    Ok(arithmetic(y, scale[i % scale.len()], Arithmetic::Divide, 1))
                } else {
                    if z.is_nan() {
                        Ok(z)
                    } else {
                        self.base_cdf(z).map_err(E::from)
                    }
                }
            })
            .collect()
    }

    fn transform_warnings<E>(
        &self,
        x: &[f64],
        warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
    ) -> Result<(), E> {
        if self.transform == SurvregTransform::Log && x.iter().any(|&v| v < 0.0) {
            warn(DpqrWarning::NaNs)?;
        }
        Ok(())
    }

    // Direct comparisons leave incoming NA/NaN unwarned, as R does; the
    // negated range.contains expression suggested by Clippy would warn.
    #[allow(clippy::manual_range_contains)]
    fn quantile_warnings<E>(
        &self,
        p: &[f64],
        warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
    ) -> Result<(), E> {
        match self.family {
            SurvregFamily::ExtremeValue => {
                if p.iter().any(|&v| v > 1.0) {
                    warn(DpqrWarning::NaNs)?;
                }
                if p.iter().any(|&v| v < 0.0) {
                    warn(DpqrWarning::NaNs)?;
                }
            }
            SurvregFamily::Logistic => {
                if p.iter().any(|&v| v / (1.0 - v) < 0.0) {
                    warn(DpqrWarning::NaNs)?;
                }
            }
            SurvregFamily::Gaussian | SurvregFamily::T => {
                if p.iter().any(|&v| v < 0.0 || v > 1.0) {
                    warn(DpqrWarning::NaNs)?;
                }
            }
            SurvregFamily::Custom => {}
        }
        Ok(())
    }

    fn query_quantile_one(&self, p: f64) -> f64 {
        if p.is_nan() {
            p
        } else {
            self.builtin_quantile(p)
        }
    }

    // Finite scalar operands cannot introduce another missing payload. Check
    // the query once to retain R's NA kind, then use ordinary arithmetic;
    // zero and negative scales still follow the same IEEE operations as R.
    #[inline]
    fn finite_scalar_probability_one(
        &self,
        x: f64,
        mean: f64,
        scale: f64,
        density: bool,
    ) -> SurvivalResult<f64> {
        if x.is_nan() {
            return Ok(x);
        }
        let z = (self.transform.apply(x)? - mean) / scale;
        if density {
            let value = self.base_pdf(z)?;
            let value = if self.transform == SurvregTransform::Identity {
                value
            } else {
                value * self.transform.derivative(x)?
            };
            Ok(value / scale)
        } else {
            self.base_cdf(z)
        }
    }

    #[inline]
    pub(crate) fn query_probability_one(
        &self,
        x: f64,
        mean: f64,
        scale: f64,
        density: bool,
        query_len: usize,
    ) -> SurvivalResult<f64> {
        let z = arithmetic(
            arithmetic(self.query_transform_one(x)?, mean, Arithmetic::Subtract, 1),
            scale,
            Arithmetic::Divide,
            1,
        );
        let value = if z.is_nan() {
            z
        } else if density {
            self.base_pdf(z)?
        } else {
            self.base_cdf(z)?
        };
        if density {
            let value = if self.transform == SurvregTransform::Identity {
                value
            } else {
                multiply(value, self.query_derivative_one(x)?, query_len, query_len)
            };
            Ok(arithmetic(value, scale, Arithmetic::Divide, 1))
        } else {
            Ok(value)
        }
    }

    pub(crate) fn query_quantile_at_one(
        &self,
        p: f64,
        mean: f64,
        scale: f64,
    ) -> SurvivalResult<f64> {
        self.query_inverse_one(arithmetic(
            multiply(self.query_quantile_one(p), scale, 1, 1),
            mean,
            Arithmetic::Add,
            1,
        ))
    }

    fn query_transform_one(&self, x: f64) -> SurvivalResult<f64> {
        if x.is_nan() {
            Ok(x)
        } else {
            self.transform.apply(x)
        }
    }

    fn query_derivative_one(&self, x: f64) -> SurvivalResult<f64> {
        if x.is_nan() {
            Ok(x)
        } else {
            self.transform.derivative(x)
        }
    }

    fn query_inverse_one(&self, x: f64) -> SurvivalResult<f64> {
        if x.is_nan() {
            Ok(x)
        } else {
            self.transform.inverse(x)
        }
    }

    fn query_selected_density<E: From<SurvivalError>>(
        &self,
        z: &[f64],
        density: bool,
        warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
    ) -> Result<Vec<f64>, E> {
        if self.callbacks.is_some() || self.family == SurvregFamily::Custom {
            Ok(self
                .custom_callbacks()
                .map_err(E::from)?
                .density(z, &self.parms)
                .map_err(E::from)?
                .into_iter()
                .map(|v| if density { v.pdf } else { v.cdf })
                .collect())
        } else if self.family == SurvregFamily::T {
            self.t_selected_density(z, density, warn)
        } else {
            z.iter()
                .map(|&z| {
                    if z.is_nan() {
                        Ok(z)
                    } else if density {
                        self.base_pdf(z).map_err(E::from)
                    } else {
                        self.base_cdf(z).map_err(E::from)
                    }
                })
                .collect()
        }
    }

    pub(crate) fn simple_builtin_query(&self) -> bool {
        self.callbacks.is_none()
            && (self.family != SurvregFamily::T
                || self.query_parms == QueryParms::Values
                    && self.parms.len() == 1
                    && self.parms[0] > 0.0)
    }

    fn t_query_parms(&self) -> SurvivalResult<&[f64]> {
        match self.query_parms {
            QueryParms::Values => Ok(&self.parms),
            QueryParms::Missing => Err(SurvivalError::invalid_input(
                "argument \"parms\" is missing, with no default",
            )),
            QueryParms::Null => Err(SurvivalError::invalid_input(
                "Non-numeric argument to mathematical function",
            )),
        }
    }

    fn t_math_values<E: From<SurvivalError>>(
        &self,
        x: &[f64],
        operation: TMath,
        warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
    ) -> Result<Vec<f64>, E> {
        use crate::internal::dist::{dt, pt, qt};
        let df = self.t_query_parms().map_err(E::from)?;
        if x.is_empty() || df.is_empty() {
            return Ok(Vec::new());
        }
        let mut invalid = false;
        // R's Math2 probability functions recycle silently; the t-density's
        // subsequent ordinary arithmetic emits its own recycling warnings.
        let values = (0..x.len().max(df.len()))
            .map(|i| {
                let x = x[i % x.len()];
                let df = df[i % df.len()];
                if is_r_na(x) {
                    return x;
                }
                if is_r_na(df) {
                    return df;
                }
                if x.is_nan() {
                    return x;
                }
                if df.is_nan() {
                    return df;
                }
                let value = match operation {
                    TMath::Cdf => pt(x, df, true, false),
                    TMath::Upper => pt(-x, df, true, false),
                    TMath::Density => dt(x, df, false),
                    TMath::Quantile => qt(x, df, true, false),
                };
                // R warns for NaNs generated by the probability function,
                // after its boundary handling (qt(0, 0) is -Inf).
                invalid |= value.is_nan();
                value
            })
            .collect();
        if invalid {
            warn(DpqrWarning::NaNs)?;
        }
        Ok(values)
    }

    fn t_selected_density<E: From<SurvivalError>>(
        &self,
        x: &[f64],
        density: bool,
        warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
    ) -> Result<Vec<f64>, E> {
        // Stock evaluates all five cbind columns before selecting CDF/PDF.
        let cdf = self.t_math_values(x, TMath::Cdf, warn)?;
        self.t_math_values(x, TMath::Upper, warn)?;
        let pdf = self.t_math_values(x, TMath::Density, warn)?;
        let df = self.parms.len();
        let nx = x.len();
        // The unused score and curvature columns have no callbacks or numeric
        // warnings. Plan each of their ordinary arithmetic operations so their
        // recycling warnings retain the exact stock multiplicity and order.
        let score_product = binary_len(df, nx, warn)?;
        let score_denominator = binary_len(df, nx, warn)?;
        binary_len(score_product, score_denominator, warn)?;
        let curvature_product = binary_len(nx, df, warn)?;
        let curvature_denominator = binary_len(df, nx, warn)?;
        let curvature_ratio = binary_len(curvature_product, curvature_denominator, warn)?;
        let curvature_inner = binary_len(curvature_ratio, 1, warn)?;
        let curvature_product = binary_len(df, curvature_inner, warn)?;
        let curvature_denominator = binary_len(df, nx, warn)?;
        binary_len(curvature_product, curvature_denominator, warn)?;
        Ok(if density { pdf } else { cdf })
    }

    fn query_transform<E: From<SurvivalError>>(
        &self,
        x: &[f64],
        warn: &mut impl FnMut(DpqrWarning) -> Result<(), E>,
    ) -> Result<Vec<f64>, E> {
        if let Some(c) = &self.transform_callbacks {
            c.0.transform(x).map_err(E::from)
        } else {
            self.transform_warnings(x, warn)?;
            x.iter()
                .map(|&v| self.query_transform_one(v).map_err(E::from))
                .collect()
        }
    }

    fn query_derivatives(&self, x: &[f64]) -> SurvivalResult<Vec<f64>> {
        if let Some(c) = &self.transform_callbacks {
            c.0.derivative(x)
        } else {
            x.iter().map(|&v| self.query_derivative_one(v)).collect()
        }
    }

    fn query_inverse(&self, x: &[f64]) -> SurvivalResult<Vec<f64>> {
        if let Some(c) = &self.transform_callbacks {
            c.0.inverse(x)
        } else {
            x.iter().map(|&v| self.query_inverse_one(v)).collect()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::Value;

    fn numbers(value: &Value) -> Vec<f64> {
        value
            .as_array()
            .unwrap()
            .iter()
            .map(|v| match v.as_str() {
                Some("NA") => f64::from_bits(0x7ff8_0000_0000_07a2),
                Some("NaN") => f64::NAN,
                Some("Inf") => f64::INFINITY,
                Some("-Inf") => f64::NEG_INFINITY,
                _ => v.as_f64().unwrap(),
            })
            .collect()
    }

    #[test]
    fn builtin_stages_match_all_stock_length_and_nonfinite_references() {
        let reference: Value = serde_json::from_str(include_str!(
            "../../../python/tests/fixtures/survreg_dpqr_reference.json"
        ))
        .unwrap();
        for case in reference["builtins"]
            .as_array()
            .unwrap()
            .iter()
            .chain(reference["exceptions"].as_array().unwrap())
        {
            let name = case["distribution"].as_str().unwrap();
            let distribution =
                SurvregDistribution::from_name(name, if name == "t" { Some(&[5.0]) } else { None })
                    .unwrap();
            let mean = numbers(&case["mean"]);
            let scale = numbers(&case["scale"]);
            let mut warnings = Vec::new();
            let mut warn = |w: DpqrWarning| {
                warnings.push(w.message());
                Ok::<_, SurvivalError>(())
            };
            let method = case["method"].as_str().unwrap();
            let values = if method == "rsurvreg" {
                distribution.sample_with_warnings(
                    case["query"].as_u64().unwrap() as usize,
                    &mean,
                    &scale,
                    Some(123),
                    &mut warn,
                )
            } else {
                let query = numbers(&case["query"]);
                match method {
                    "dsurvreg" => {
                        distribution.pdf_values_with_warnings(&query, &mean, &scale, &mut warn)
                    }
                    "psurvreg" => {
                        distribution.cdf_values_with_warnings(&query, &mean, &scale, &mut warn)
                    }
                    "qsurvreg" => {
                        distribution.quantile_values_with_warnings(&query, &mean, &scale, &mut warn)
                    }
                    _ => unreachable!(),
                }
            }
            .unwrap();
            let expected = &case["expected"];
            let expected_values = numbers(&expected["values"]);
            assert_eq!(values.len(), expected_values.len(), "{}", case["name"]);
            for (&actual, &expected) in values.iter().zip(&expected_values) {
                if expected.is_nan() {
                    assert!(
                        actual.is_nan(),
                        "{}: expected missing value, got {actual}",
                        case["name"]
                    );
                    assert_eq!(
                        actual.to_bits() & 0x0007_ffff_ffff_ffff == 0x7a2,
                        expected.to_bits() & 0x0007_ffff_ffff_ffff == 0x7a2,
                        "{}: missing value kind differs",
                        case["name"]
                    );
                }
                assert!(
                    actual == expected
                        || actual.is_nan() && expected.is_nan()
                        || (actual - expected).abs() <= 1e-12 * expected.abs().max(1.0),
                    "{}: {actual} != {expected}",
                    case["name"]
                );
            }
            let expected_warnings: Vec<_> = expected["events"]
                .as_array()
                .unwrap()
                .iter()
                .filter(|e| e["kind"] == "warning")
                .map(|e| e["message"].as_str().unwrap())
                .collect();
            assert_eq!(warnings, expected_warnings, "{}", case["name"]);
        }
    }

    #[test]
    fn query_parameters_match_independent_stock_references() {
        let reference: Value = serde_json::from_str(include_str!(
            "../../../python/tests/fixtures/survreg_dpqr_parms_reference.json"
        ))
        .unwrap();
        for case in reference["cases"].as_array().unwrap() {
            let name = case["distribution"].as_str().unwrap();
            let mode = case["parms_mode"].as_str().unwrap();
            let parms = if mode == "numeric" {
                numbers(&case["parms"])
            } else {
                vec![]
            };
            let mut distribution = SurvregDistribution::for_query(
                name,
                if mode == "omitted" {
                    None
                } else {
                    Some(&parms)
                },
            )
            .unwrap();
            if name == "t" && matches!(mode, "null" | "character" | "list") {
                distribution.query_parms = QueryParms::Null;
            }
            let mean = numbers(&case["mean"]);
            let scale = numbers(&case["scale"]);
            let mut warnings = Vec::new();
            let mut warn = |w: DpqrWarning| {
                warnings.push(w.message());
                Ok::<_, SurvivalError>(())
            };
            let method = case["method"].as_str().unwrap();
            let result = if method == "rsurvreg" {
                distribution.sample_with_warnings(
                    case["query"].as_u64().unwrap() as usize,
                    &mean,
                    &scale,
                    Some(123),
                    &mut warn,
                )
            } else {
                let query = numbers(&case["query"]);
                match method {
                    "dsurvreg" => {
                        distribution.pdf_values_with_warnings(&query, &mean, &scale, &mut warn)
                    }
                    "psurvreg" => {
                        distribution.cdf_values_with_warnings(&query, &mean, &scale, &mut warn)
                    }
                    "qsurvreg" => {
                        distribution.quantile_values_with_warnings(&query, &mean, &scale, &mut warn)
                    }
                    _ => unreachable!(),
                }
            };
            let expected = &case["expected"];
            let expected_warnings: Vec<_> = expected["events"]
                .as_array()
                .unwrap()
                .iter()
                .filter(|e| e["kind"] == "warning")
                .map(|e| e["message"].as_str().unwrap())
                .collect();
            assert_eq!(warnings, expected_warnings, "{}", case["name"]);
            if let Some(message) = expected["error"].as_str() {
                let error = result.expect_err(&format!("{} should fail", case["name"]));
                assert!(
                    error.to_string().contains(message),
                    "{}: {error}",
                    case["name"]
                );
                continue;
            }
            let values = result.unwrap_or_else(|e| panic!("{}: {e}", case["name"]));
            let expected_values = numbers(&expected["values"]);
            assert_eq!(values.len(), expected_values.len(), "{}", case["name"]);
            for (&actual, &expected) in values.iter().zip(&expected_values) {
                if expected.is_nan() {
                    assert!(
                        actual.is_nan(),
                        "{}: expected missing, got {actual}",
                        case["name"]
                    );
                    assert_eq!(
                        is_r_na(actual),
                        is_r_na(expected),
                        "{}: missing kind",
                        case["name"]
                    );
                } else {
                    assert!(
                        actual == expected
                            || (actual - expected).abs() <= 2e-12 * expected.abs().max(1.0),
                        "{}: {actual} != {expected}",
                        case["name"]
                    );
                }
            }
        }
    }

    #[test]
    fn finite_scalar_queries_retain_stock_signed_zeros() {
        // Pinned stock R gives negative-zero density at +Inf with scale -1,
        // and negative-zero median at mean=-0, scale=-0 for identity families.
        for name in ["gaussian", "weibull", "logistic", "t"] {
            let distribution = SurvregDistribution::for_query(name, Some(&[4.0])).unwrap();
            let density = distribution
                .pdf_values(&[f64::INFINITY], &[0.0], &[-1.0])
                .unwrap()[0];
            assert_eq!(density.to_bits(), (-0.0_f64).to_bits(), "{name}");
            let quantile = distribution
                .quantile_values(&[0.5], &[-0.0], &[-0.0])
                .unwrap()[0];
            if name == "weibull" {
                assert_eq!(quantile, 1.0);
            } else {
                assert_eq!(quantile.to_bits(), (-0.0_f64).to_bits(), "{name}");
            }
        }
    }

    #[test]
    fn quantile_missing_kind_matches_equal_and_unequal_stock_multiplication() {
        let na = f64::from_bits(0x7ff8_0000_0000_07a2);
        // Pinned stock R: qnorm(c(NA, NaN))*c(NaN, NA) preserves the
        // left missing kinds, while unequal vector lengths use the right.
        for name in ["gaussian", "weibull", "logistic", "t"] {
            let distribution = SurvregDistribution::for_query(name, Some(&[4.0])).unwrap();
            let equal = distribution
                .quantile_values(&[na, f64::NAN], &[0.0], &[f64::NAN, na])
                .unwrap();
            assert!(is_r_na(equal[0]), "{name}");
            assert!(equal[1].is_nan() && !is_r_na(equal[1]), "{name}");
            let unequal = distribution
                .quantile_values(&[na, f64::NAN, na], &[0.0], &[f64::NAN, na])
                .unwrap();
            assert!(unequal[0].is_nan() && !is_r_na(unequal[0]), "{name}");
            assert!(is_r_na(unequal[1]), "{name}");
            assert!(unequal[2].is_nan() && !is_r_na(unequal[2]), "{name}");
        }
    }

    #[test]
    fn scalar_query_views_are_safe_and_agree_with_singleton_batches() {
        for parms in [&[][..], &[3.0, 5.0][..]] {
            let distribution = SurvregDistribution::for_query("t", Some(parms)).unwrap();
            assert!(distribution.pdf(0.2, 0.0, 1.0).is_err());
            assert!(distribution.cdf(0.2, 0.0, 1.0).is_err());
            assert!(distribution.quantile_at(0.2, 0.0, 1.0).is_err());
        }
        let missing = SurvregDistribution::for_query("t", None).unwrap();
        assert!(
            missing
                .pdf(0.2, 0.0, 1.0)
                .unwrap_err()
                .to_string()
                .contains("parms")
        );
        assert!(missing.cdf(0.2, 0.0, 1.0).is_err());
        assert!(missing.quantile_at(0.2, 0.0, 1.0).is_err());
        let mut null = missing;
        null.query_parms = QueryParms::Null;
        assert!(null.pdf(0.2, 0.0, 1.0).is_err());
        assert!(null.cdf(0.2, 0.0, 1.0).is_err());
        assert!(null.quantile_at(0.2, 0.0, 1.0).is_err());
        for df in [
            -1.0,
            0.0,
            1.0,
            2.0,
            4.0,
            f64::INFINITY,
            f64::NAN,
            f64::from_bits(0x7ff8_0000_0000_07a2),
        ] {
            let distribution = SurvregDistribution::for_query("t", Some(&[df])).unwrap();
            let scalar = [
                distribution.pdf(0.2, 0.0, 1.0).unwrap(),
                distribution.cdf(0.2, 0.0, 1.0).unwrap(),
                distribution.quantile_at(0.2, 0.0, 1.0).unwrap(),
            ];
            let batch = [
                distribution.pdf_values(&[0.2], &[0.0], &[1.0]).unwrap()[0],
                distribution.cdf_values(&[0.2], &[0.0], &[1.0]).unwrap()[0],
                distribution
                    .quantile_values(&[0.2], &[0.0], &[1.0])
                    .unwrap()[0],
            ];
            for (scalar, batch) in scalar.into_iter().zip(batch) {
                assert!(scalar == batch || scalar.is_nan() && batch.is_nan());
                assert_eq!(is_r_na(scalar), is_r_na(batch));
            }
        }
    }

    #[test]
    fn warning_failure_stops_before_later_stages() {
        let distribution = SurvregDistribution::from_name("extreme", None).unwrap();
        let mut warnings = Vec::new();
        let result = distribution.quantile_values_with_warnings(
            &[-0.1, 1.1],
            &[0.0, 1.0, 2.0],
            &[1.0],
            &mut |w| {
                warnings.push(w);
                Err::<(), _>(SurvivalError::invalid_input("warning promoted"))
            },
        );
        assert!(result.is_err());
        assert_eq!(warnings, vec![DpqrWarning::NaNs]);
    }
}
