"""R-style survival API split into cohesive modules; ``survival.r_api`` re-exports it.

The ``__all__`` list is exactly the one ``survival.r_api`` has always exported. The redundant
``name as name`` imports keep the few public names ``r_api`` exposed without listing them
(``ConcordanceResult``, ``TurnbullSurvfitResult``, ``predict_terms_constant``) importable.
"""

from __future__ import annotations

from ._aareg import aareg
from ._cch import cch
from ._concordance import concordance, survConcordance, survConcordance_fit
from ._coxph import anova, basehaz, clogit, cox_zph, coxph, coxph_detail, coxph_wtest
from ._data_prep import (
    aeqSurv,
    cumevent,
    cumtdc,
    event,
    lvcf,
    neardate,
    nostutter,
    rttright,
    survcondense,
    survSplit,
    tcut,
    tdc,
    tmerge,
)
from ._finegray import finegray
from ._misc import (
    bcloglog,
    blog,
    blogit,
    bprobit,
    brier,
    cipoisson,
    nsk,
    pspline,
    royston,
    statefig,
    survcheck,
    survobrien,
    yates,
    yates_contrast,
    yates_pairwise,
)
from ._models import (
    aic,
    as_data_frame,
    bic,
    coef,
    coef_names,
    confint,
    degrees_freedom,
    df_residual,
    extract_aic,
    fitted,
    loglik,
    model_formula,
    model_frame,
    model_matrix,
    model_summary,
    model_term_names,
    model_weights,
    nobs,
    predict,
    residuals,
    vcov,
)
from ._models import predict_terms_constant as predict_terms_constant
from ._pyears import (
    is_ratetable,
    pyears,
    ratetableDate,
    survexp,
    survexp_individual,
    survexp_mn,
    survexp_us,
    survexp_usr,
)
from ._surv import (
    Surv,
    Surv2,
    Surv2data,
    format_surv,
    fromtimeline,
    is_na_surv,
    is_surv,
    strata,
    totimeline,
)
from ._survdiff import survdiff
from ._survfit import (
    aggregate_survfit_result,
    survfit,
    survfit0,
    survfit_confint,
    survfitkm_counting_influence,
    survfitkm_influence,
)
from ._survfit_residuals import pseudo, survfit_residuals
from ._survreg import dsurvreg, psurvreg, qsurvreg, rsurvreg, survreg
from ._types import (
    AaregModelResult,
    CchModelResult,
    CoxBaseHazardResult,
    CoxPHDetailResult,
    CoxPHWTestResult,
    CoxSurvfitResult,
    CoxZPHResult,
    FineGrayFrame,
    FineGrayOutput,
    PredictResult,
    PyearsResult,
    RateTable,
    StrataFactor,
    SurvExpResult,
    SurvfitConfidenceIntervalResult,
    SurvfitMultiStateResult,
    SurvfitResult,
    SurvObrienResult,
    TcutResult,
    TMergeFrame,
    TMergeOperation,
    YatesPairwiseResult,
    YatesResult,
)
from ._types import ConcordanceResult as ConcordanceResult
from ._types import TurnbullSurvfitResult as TurnbullSurvfitResult

__all__ = [
    "Surv",
    "Surv2",
    "Surv2data",
    "CoxSurvfitResult",
    "CoxBaseHazardResult",
    "CoxPHDetailResult",
    "CoxPHWTestResult",
    "CoxZPHResult",
    "CchModelResult",
    "FineGrayFrame",
    "FineGrayOutput",
    "TMergeFrame",
    "TMergeOperation",
    "PredictResult",
    "PyearsResult",
    "RateTable",
    "AaregModelResult",
    "StrataFactor",
    "SurvObrienResult",
    "SurvExpResult",
    "SurvfitResult",
    "SurvfitMultiStateResult",
    "SurvfitConfidenceIntervalResult",
    "TcutResult",
    "aic",
    "aareg",
    "aeqSurv",
    "as_data_frame",
    "basehaz",
    "anova",
    "aggregate_survfit_result",
    "brier",
    "bcloglog",
    "coef",
    "coef_names",
    "confint",
    "concordance",
    "clogit",
    "cch",
    "coxph",
    "coxph_detail",
    "coxph_wtest",
    "cox_zph",
    "dsurvreg",
    "df_residual",
    "degrees_freedom",
    "bic",
    "blog",
    "blogit",
    "bprobit",
    "cipoisson",
    "extract_aic",
    "fitted",
    "finegray",
    "tdc",
    "cumtdc",
    "event",
    "cumevent",
    "tmerge",
    "fromtimeline",
    "format_surv",
    "is_surv",
    "is_na_surv",
    "is_ratetable",
    "loglik",
    "lvcf",
    "model_formula",
    "model_summary",
    "model_frame",
    "model_matrix",
    "model_term_names",
    "model_weights",
    "neardate",
    "nobs",
    "nostutter",
    "nsk",
    "pyears",
    "pspline",
    "pseudo",
    "predict",
    "psurvreg",
    "qsurvreg",
    "ratetableDate",
    "residuals",
    "royston",
    "rsurvreg",
    "rttright",
    "statefig",
    "strata",
    "survdiff",
    "survConcordance",
    "survConcordance_fit",
    "survcondense",
    "survcheck",
    "survexp",
    "survexp_individual",
    "survexp_mn",
    "survobrien",
    "survexp_us",
    "survexp_usr",
    "survfit",
    "survfit0",
    "survfit_confint",
    "survfit_residuals",
    "survfitkm_counting_influence",
    "survfitkm_influence",
    "survSplit",
    "survreg",
    "tcut",
    "totimeline",
    "yates",
    "yates_contrast",
    "yates_pairwise",
    "vcov",
    "YatesPairwiseResult",
    "YatesResult",
]
