"""R-style survival API split into cohesive modules; ``survival.r_api`` re-exports it.

``__all__`` lists R's exported functions under Python spellings (``survreg.control`` is
``survreg_control``, ``cox.zph`` is ``cox_zph``) and the R-level fit and result classes, so
they can be named in annotations and ``isinstance`` checks.  The engine classes a few
functions return (``nsk``'s ``SplineBasisResult``, ``survfit_confint``'s ``ConfidenceBands``,
``survreg_control``'s ``SurvregControl``) live in the domain modules (``survival.core``,
``surv_analysis``, ``regression``).  The typed surface is the inline annotations of the
implementation modules (the package ships ``py.typed``).
"""

from __future__ import annotations

from .._survival import AnovaCoxphResult
from ._aareg import aareg
from ._aareg_print import print_aareg, print_summary_aareg
from ._array_print import print_ratetable, print_surv, print_surv2
from ._cch import cch
from ._concordance import concordance, concordancefit, survConcordance, survConcordance_fit
from ._coxph import (
    ClogitModel,
    CoxphModel,
    CoxSchoenfeldResiduals,
    anova,
    basehaz,
    clogit,
    cox_zph,
    coxph,
    coxph_control,
    coxph_detail,
    coxph_wtest,
)
from ._coxph_lowlevel import CoxFitResult, agexact_fit, agreg_fit, coxph_fit
from ._coxph_print import (
    print_coxph,
    print_coxph_null,
    print_coxph_penal,
    print_summary_coxph,
    print_summary_coxph_penal,
)
from ._coxphms import CoxphmsModel, CoxphmsSchoenfeldResiduals, CoxphmsShare
from ._coxsurv import CoxSurvFitList, CoxSurvFitResult, coxsurv_fit, survfitcoxph_fit
from ._data_prep import (
    aeqSurv,
    cumevent,
    cumtdc,
    event,
    fromtimeline,
    lvcf,
    neardate,
    nostutter,
    rttright,
    summary_tmerge,
    survcondense,
    survSplit,
    tcut,
    tdc,
    tmerge,
)
from ._finegray import finegray
from ._misc import (
    bcloglog,
    blog,
    blogit,
    bprobit,
    brier,
    cipoisson,
    nsk,
    predict_pspline,
    pspline,
    royston,
    statefig,
    survcheck,
    survobrien,
)
from ._models import (
    aic,
    as_data_frame,
    bic,
    coef,
    coef_names,
    confint,
    degrees_freedom,
    df_residual,
    extract_aic,
    fitted,
    loglik,
    median,
    model_formula,
    model_frame,
    model_matrix,
    model_summary,
    model_term_names,
    model_weights,
    nobs,
    predict,
    predict_terms_constant,
    quantile,
    residuals,
    vcov,
)
from ._population_print import print_pyears, print_survcheck, print_yates
from ._pyears import (
    PyearsSummary,
    RateTableMatch,
    RateTableSummary,
    is_ratetable,
    match_ratetable,
    pyears,
    ratetableDate,
    summary_pyears,
    summary_ratetable,
    summary_survexp,
    survexp,
    survexp_mn,
    survexp_us,
    survexp_usr,
)
from ._surv import (
    Surv,
    Surv2,
    as_character_surv,
    cluster,
    format_surv,
    is_na_surv,
    is_surv,
    strata,
    totimeline,
)
from ._surv_summary_print import (
    SurvivalTablePrint,
    print_summary_survexp,
    print_summary_survfit,
    print_summary_survfitms,
    print_survexp,
)
from ._surv_vector import (
    concat_surv,
    duplicated_surv,
    head_surv,
    levels_surv,
    rep_surv,
    rev_surv,
    tail_surv,
    transpose_surv,
    unique_surv,
)
from ._survdiff import survdiff
from ._survfit import (
    aggregate_survfit,
    median_surv,
    median_survfit,
    quantile_surv,
    quantile_survfit,
    summary_survfit,
    survfit,
    survfit0,
    survfit_confint,
)
from ._survfit_lowlevel import SurvfitKMResult, survfitKM
from ._survfit_print import SurvfitPrint, print_survfit, print_survfitms
from ._survfit_residuals import pseudo, survfit_residuals
from ._survpenal_lowlevel import SurvpenalFitResult, survpenal_fit
from ._survpenal_print import SurvregPenalPrint, print_survreg_penal
from ._survreg import (
    SurvregAnovaResult,
    SurvregModelResult,
    dsurvreg,
    psurvreg,
    qsurvreg,
    rsurvreg,
    survreg,
    survreg_control,
    survreg_distributions,
    survregDtest,
)
from ._survreg_lowlevel import SurvregFitResult, survreg_fit
from ._survreg_print import print_summary_survreg, print_survreg
from ._terms import SpecialTerms, TermMetadata, attrassign, untangle_specials
from ._test_print import (
    print_cch,
    print_clogit,
    print_concordance,
    print_cox_zph,
    print_summary_cch,
    print_survConcordance,
    print_survdiff,
)
from ._types import (
    AaregModelResult,
    BrierResult,
    CchModelResult,
    ConcordanceResult,
    CoxBaseHazardResult,
    CoxPHDetailResult,
    CoxPHWTestResult,
    CoxSurvfitMultiStateResult,
    CoxSurvfitResult,
    CoxZPHResult,
    FineGrayFrame,
    FineGrayOutput,
    ModelFrame,
    ModelPrint,
    NaAction,
    NamedMatrix,
    PredictResult,
    PsplineResult,
    PyearsResult,
    RateTable,
    RateTablePrint,
    ResponsePrint,
    StateFigResult,
    StrataFactor,
    SummarySurvfitCoxmsResult,
    SummarySurvfitResult,
    SurvCheckProblem,
    SurvCheckResult,
    SurvConcordanceResult,
    SurvDiffResult,
    SurvExpResult,
    SurvExpSummary,
    SurvfitCall,
    SurvfitConfidenceIntervalResult,
    SurvfitInfluenceMatrix,
    SurvfitMultiStateResult,
    SurvfitQuantileResult,
    SurvfitResidualsResult,
    SurvfitResult,
    TcutResult,
    Timeline,
    TMergeFrame,
    TMergeOperation,
    YatesPrint,
    YatesResult,
)
from ._yates import yates
from ._yates_model import YatesModel
from ._yates_setup import YatesLinkPrediction, YatesSurvivalSetup, yates_setup

__all__ = [
    "YatesLinkPrediction",
    "YatesSurvivalSetup",
    "yates_setup",
    "TermMetadata",
    "SpecialTerms",
    "attrassign",
    "untangle_specials",
    "SurvregFitResult",
    "survreg_fit",
    "SurvpenalFitResult",
    "survpenal_fit",
    "CoxSurvFitResult",
    "CoxSurvFitList",
    "coxsurv_fit",
    "survfitcoxph_fit",
    "SurvfitKMResult",
    "survfitKM",
    "CoxFitResult",
    "coxph_fit",
    "agreg_fit",
    "agexact_fit",
    "RateTableMatch",
    "match_ratetable",
    "print_ratetable",
    "print_surv",
    "print_surv2",
    "RateTablePrint",
    "ResponsePrint",
    "print_pyears",
    "print_survcheck",
    "print_yates",
    "YatesPrint",
    "Surv",
    "Surv2",
    "AaregModelResult",
    "AnovaCoxphResult",
    "BrierResult",
    "CchModelResult",
    "ClogitModel",
    "ConcordanceResult",
    "CoxBaseHazardResult",
    "CoxPHDetailResult",
    "CoxPHWTestResult",
    "CoxSchoenfeldResiduals",
    "CoxSurvfitMultiStateResult",
    "CoxSurvfitResult",
    "CoxZPHResult",
    "CoxphModel",
    "CoxphmsModel",
    "CoxphmsSchoenfeldResiduals",
    "CoxphmsShare",
    "FineGrayFrame",
    "FineGrayOutput",
    "ModelFrame",
    "NaAction",
    "NamedMatrix",
    "PredictResult",
    "PsplineResult",
    "PyearsResult",
    "PyearsSummary",
    "RateTableSummary",
    "RateTable",
    "StateFigResult",
    "StrataFactor",
    "SummarySurvfitCoxmsResult",
    "SummarySurvfitResult",
    "SurvCheckProblem",
    "SurvCheckResult",
    "SurvConcordanceResult",
    "SurvDiffResult",
    "SurvExpResult",
    "SurvExpSummary",
    "SurvfitCall",
    "SurvfitConfidenceIntervalResult",
    "SurvfitInfluenceMatrix",
    "SurvfitMultiStateResult",
    "SurvfitQuantileResult",
    "SurvfitResidualsResult",
    "SurvfitResult",
    "SurvregAnovaResult",
    "SurvregModelResult",
    "SurvregPenalPrint",
    "TMergeFrame",
    "TMergeOperation",
    "TcutResult",
    "Timeline",
    "YatesModel",
    "YatesResult",
    "aic",
    "aareg",
    "aeqSurv",
    "as_data_frame",
    "basehaz",
    "anova",
    "aggregate_survfit",
    "brier",
    "bcloglog",
    "coef",
    "coef_names",
    "confint",
    "cluster",
    "concordance",
    "concordancefit",
    "clogit",
    "cch",
    "coxph",
    "coxph_control",
    "coxph_detail",
    "coxph_wtest",
    "cox_zph",
    "dsurvreg",
    "df_residual",
    "degrees_freedom",
    "bic",
    "blog",
    "blogit",
    "bprobit",
    "cipoisson",
    "extract_aic",
    "fitted",
    "finegray",
    "tdc",
    "cumtdc",
    "event",
    "cumevent",
    "tmerge",
    "fromtimeline",
    "format_surv",
    "as_character_surv",
    "concat_surv",
    "duplicated_surv",
    "head_surv",
    "levels_surv",
    "rep_surv",
    "rev_surv",
    "tail_surv",
    "transpose_surv",
    "unique_surv",
    "is_surv",
    "is_na_surv",
    "is_ratetable",
    "loglik",
    "lvcf",
    "model_formula",
    "model_summary",
    "model_frame",
    "model_matrix",
    "model_term_names",
    "model_weights",
    "neardate",
    "nobs",
    "nostutter",
    "nsk",
    "pyears",
    "pspline",
    "pseudo",
    "predict",
    "predict_pspline",
    "print_survreg_penal",
    "print_survreg",
    "print_summary_survreg",
    "print_aareg",
    "print_summary_aareg",
    "print_cch",
    "print_summary_cch",
    "print_clogit",
    "print_cox_zph",
    "print_concordance",
    "print_survConcordance",
    "print_survdiff",
    "ModelPrint",
    "print_coxph",
    "print_coxph_null",
    "print_coxph_penal",
    "print_summary_coxph",
    "print_summary_coxph_penal",
    "SurvfitPrint",
    "print_survfit",
    "print_survfitms",
    "SurvivalTablePrint",
    "print_summary_survfit",
    "print_summary_survfitms",
    "print_survexp",
    "print_summary_survexp",
    "predict_terms_constant",
    "median",
    "median_surv",
    "median_survfit",
    "quantile",
    "quantile_surv",
    "quantile_survfit",
    "psurvreg",
    "qsurvreg",
    "ratetableDate",
    "residuals",
    "royston",
    "rsurvreg",
    "rttright",
    "statefig",
    "strata",
    "survdiff",
    "survConcordance",
    "survConcordance_fit",
    "survcondense",
    "survcheck",
    "survexp",
    "survexp_mn",
    "survobrien",
    "survexp_us",
    "survexp_usr",
    "summary_pyears",
    "summary_ratetable",
    "summary_survexp",
    "summary_tmerge",
    "summary_survfit",
    "survfit",
    "survfit0",
    "survfit_confint",
    "survfit_residuals",
    "survSplit",
    "survreg",
    "survreg_control",
    "survreg_distributions",
    "survregDtest",
    "tcut",
    "totimeline",
    "yates",
    "vcov",
]
