"""R-style survival API split into cohesive modules; ``survival.r_api`` re-exports it.

``__all__`` lists R's exported functions under Python spellings (``survreg.control`` is
``survreg_control``, ``cox.zph`` is ``cox_zph``) and the R-level fit and result classes, so
they can be named in annotations and ``isinstance`` checks.  The engine classes a few
functions return (``nsk``'s ``SplineBasisResult``, ``survfit_confint``'s ``ConfidenceBands``,
``survreg_control``'s ``SurvregControl``) live in the domain modules (``survival.core``,
``surv_analysis``, ``regression``).  The typed surface is the inline annotations of the
implementation modules (the package ships ``py.typed``).
"""

from __future__ import annotations

from .._survival import AnovaCoxphResult
from ._aareg import aareg
from ._cch import cch
from ._concordance import concordance, concordancefit, survConcordance, survConcordance_fit
from ._coxph import (
    ClogitModel,
    CoxphModel,
    CoxSchoenfeldResiduals,
    anova,
    basehaz,
    clogit,
    cox_zph,
    coxph,
    coxph_control,
    coxph_detail,
    coxph_wtest,
)
from ._data_prep import (
    aeqSurv,
    cumevent,
    cumtdc,
    event,
    fromtimeline,
    lvcf,
    neardate,
    nostutter,
    rttright,
    survcondense,
    survSplit,
    tcut,
    tdc,
    tmerge,
)
from ._finegray import finegray
from ._misc import (
    bcloglog,
    blog,
    blogit,
    bprobit,
    brier,
    cipoisson,
    nsk,
    pspline,
    royston,
    statefig,
    survcheck,
    survobrien,
    yates,
)
from ._models import (
    aic,
    as_data_frame,
    bic,
    coef,
    coef_names,
    confint,
    degrees_freedom,
    df_residual,
    extract_aic,
    fitted,
    loglik,
    model_formula,
    model_frame,
    model_matrix,
    model_summary,
    model_term_names,
    model_weights,
    nobs,
    predict,
    predict_terms_constant,
    residuals,
    vcov,
)
from ._pyears import (
    PyearsSummary,
    is_ratetable,
    pyears,
    ratetableDate,
    summary_pyears,
    survexp,
    survexp_individual,
    survexp_mn,
    survexp_us,
    survexp_usr,
)
from ._surv import (
    Surv,
    Surv2,
    cluster,
    format_surv,
    is_na_surv,
    is_surv,
    strata,
    totimeline,
)
from ._survdiff import survdiff
from ._survfit import (
    aggregate_survfit,
    aggregate_survfit_result,
    quantile_survfit,
    summary_survfit,
    survfit,
    survfit0,
    survfit_confint,
    survfitkm_counting_influence,
    survfitkm_influence,
)
from ._survfit_residuals import pseudo, survfit_residuals
from ._survpenal_print import SurvregPenalPrint, print_survreg_penal
from ._survreg import (
    SurvregAnovaResult,
    SurvregModelResult,
    dsurvreg,
    psurvreg,
    qsurvreg,
    rsurvreg,
    survreg,
    survreg_control,
    survreg_distributions,
    survregDtest,
)
from ._types import (
    AaregModelResult,
    BrierResult,
    CchModelResult,
    ConcordanceResult,
    CoxBaseHazardResult,
    CoxPHDetailResult,
    CoxPHWTestResult,
    CoxSurvfitResult,
    CoxZPHResult,
    FineGrayFrame,
    FineGrayOutput,
    ModelFrame,
    NaAction,
    NamedMatrix,
    PredictResult,
    PsplineResult,
    PyearsResult,
    RateTable,
    StateFigResult,
    StrataFactor,
    SummarySurvfitResult,
    SurvCheckProblem,
    SurvCheckResult,
    SurvConcordanceResult,
    SurvDiffResult,
    SurvExpResult,
    SurvfitCall,
    SurvfitConfidenceIntervalResult,
    SurvfitInfluenceMatrix,
    SurvfitMultiStateResult,
    SurvfitQuantileResult,
    SurvfitResidualsResult,
    SurvfitResult,
    TcutResult,
    Timeline,
    TMergeFrame,
    TMergeOperation,
    YatesResult,
)
from ._yates_model import YatesModel

__all__ = [
    "Surv",
    "Surv2",
    "AaregModelResult",
    "AnovaCoxphResult",
    "BrierResult",
    "CchModelResult",
    "ClogitModel",
    "ConcordanceResult",
    "CoxBaseHazardResult",
    "CoxPHDetailResult",
    "CoxPHWTestResult",
    "CoxSchoenfeldResiduals",
    "CoxSurvfitResult",
    "CoxZPHResult",
    "CoxphModel",
    "FineGrayFrame",
    "FineGrayOutput",
    "ModelFrame",
    "NaAction",
    "NamedMatrix",
    "PredictResult",
    "PsplineResult",
    "PyearsResult",
    "PyearsSummary",
    "RateTable",
    "StateFigResult",
    "StrataFactor",
    "SummarySurvfitResult",
    "SurvCheckProblem",
    "SurvCheckResult",
    "SurvConcordanceResult",
    "SurvDiffResult",
    "SurvExpResult",
    "SurvfitCall",
    "SurvfitConfidenceIntervalResult",
    "SurvfitInfluenceMatrix",
    "SurvfitMultiStateResult",
    "SurvfitQuantileResult",
    "SurvfitResidualsResult",
    "SurvfitResult",
    "SurvregAnovaResult",
    "SurvregModelResult",
    "SurvregPenalPrint",
    "TMergeFrame",
    "TMergeOperation",
    "TcutResult",
    "Timeline",
    "YatesModel",
    "YatesResult",
    "aic",
    "aareg",
    "aeqSurv",
    "as_data_frame",
    "basehaz",
    "anova",
    "aggregate_survfit",
    "aggregate_survfit_result",
    "brier",
    "bcloglog",
    "coef",
    "coef_names",
    "confint",
    "cluster",
    "concordance",
    "concordancefit",
    "clogit",
    "cch",
    "coxph",
    "coxph_control",
    "coxph_detail",
    "coxph_wtest",
    "cox_zph",
    "dsurvreg",
    "df_residual",
    "degrees_freedom",
    "bic",
    "blog",
    "blogit",
    "bprobit",
    "cipoisson",
    "extract_aic",
    "fitted",
    "finegray",
    "tdc",
    "cumtdc",
    "event",
    "cumevent",
    "tmerge",
    "fromtimeline",
    "format_surv",
    "is_surv",
    "is_na_surv",
    "is_ratetable",
    "loglik",
    "lvcf",
    "model_formula",
    "model_summary",
    "model_frame",
    "model_matrix",
    "model_term_names",
    "model_weights",
    "neardate",
    "nobs",
    "nostutter",
    "nsk",
    "pyears",
    "pspline",
    "pseudo",
    "predict",
    "print_survreg_penal",
    "predict_terms_constant",
    "quantile_survfit",
    "psurvreg",
    "qsurvreg",
    "ratetableDate",
    "residuals",
    "royston",
    "rsurvreg",
    "rttright",
    "statefig",
    "strata",
    "survdiff",
    "survConcordance",
    "survConcordance_fit",
    "survcondense",
    "survcheck",
    "survexp",
    "survexp_individual",
    "survexp_mn",
    "survobrien",
    "survexp_us",
    "survexp_usr",
    "summary_pyears",
    "summary_survfit",
    "survfit",
    "survfit0",
    "survfit_confint",
    "survfit_residuals",
    "survfitkm_counting_influence",
    "survfitkm_influence",
    "survSplit",
    "survreg",
    "survreg_control",
    "survreg_distributions",
    "survregDtest",
    "tcut",
    "totimeline",
    "yates",
    "vcov",
]
