from . import _survival as _core
from ._binding_utils import bind_names

__all__ = bind_names(
    globals(),
    [
        "CausalForestConfig",
        "CausalForestResult",
        "CausalForestSurvival",
        "causal_forest_survival",
        "CounterfactualSurvivalConfig",
        "CounterfactualSurvivalResult",
        "TVSurvCausConfig",
        "TVSurvCausResult",
        "estimate_counterfactual_survival",
        "estimate_tv_survcaus",
        "CopulaCensoringConfig",
        "CopulaCensoringResult",
        "CopulaType",
        "MNARSurvivalConfig",
        "MNARSurvivalResult",
        "SensitivityBoundsConfig",
        "SensitivityBoundsResult",
        "copula_censoring_model",
        "mnar_sensitivity_survival",
        "sensitivity_bounds_survival",
        "CATEResult",
        "DoubleMLConfig",
        "DoubleMLResult",
        "double_ml_cate",
        "double_ml_survival",
        "GComputationResult",
        "g_computation",
        "g_computation_survival_curves",
        "GEstimationConfig",
        "GEstimationResult",
        "IVCoxConfig",
        "IVCoxResult",
        "MediationSurvivalConfig",
        "MediationSurvivalResult",
        "RDSurvivalConfig",
        "RDSurvivalResult",
        "g_estimation_aft",
        "iv_cox",
        "mediation_survival",
        "rd_survival",
        "IPCWInput",
        "IPCWConfig",
        "IPCWResult",
        "compute_ipcw_weights",
        "ipcw_kaplan_meier",
        "MSMResult",
        "compute_longitudinal_iptw",
        "marginal_structural_model",
        "TargetTrialResult",
        "sequential_trial_emulation",
        "target_trial_emulation",
        "TMLEConfig",
        "TMLEResult",
        "TMLESurvivalResult",
        "tmle_ate",
        "tmle_survival",
    ],
)


def ipcw_treatment_effect(
    time,
    status,
    treatment,
    outcome,
    x_confounders,
    n_obs,
    n_vars,
    tau=None,
):
    return _core.ipcw_treatment_effect(
        time=time,
        status=status,
        treatment=treatment,
        outcome=outcome,
        x_confounders=x_confounders,
        n_obs=n_obs,
        n_vars=n_vars,
        tau=tau,
    )


__all__.append("ipcw_treatment_effect")
