#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGISTRATION_ROOT = ROOT / "src/api/python"
MANIFEST_PATH = ROOT / "python/survival/_binding_manifest.py"
FEATURE_REGISTRATION_PATHS = {
    "ml": (
        "src/api/python/ml.rs",
        "src/api/python/applied.rs",
        "src/api/python/functional_robustness.rs",
    ),
}

IDENT = r"[A-Za-z_][A-Za-z0-9_]*(?:::[A-Za-z_][A-Za-z0-9_]*)*"
WRAP_PYFUNCTION_RE = re.compile(rf"wrap_pyfunction!\s*\(\s*({IDENT})")
ADD_CLASS_RE = re.compile(rf"add_class\s*::\s*<\s*({IDENT})\s*>")
PYFUNCTION_NAME_RE = re.compile(
    rf"#\s*\[\s*pyfunction\s*\(\s*name\s*=\s*\"(?P<export>[^\"]+)\"\s*\)\s*\]\s*"
    rf"(?:#\s*\[[^\]]+\]\s*)*"
    rf"(?:pub(?:\([^)]*\))?\s+)?fn\s+(?P<ident>{IDENT})\s*\(",
    re.DOTALL,
)
REGISTER_MACRO_RE = re.compile(
    r"(?:register_functions|register_classes)!\s*\(\s*m\s*,(?P<body>.*?)\);",
    re.DOTALL,
)
LINE_COMMENT_RE = re.compile(r"//.*")
BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)


def _strip_comments(source: str) -> str:
    source = BLOCK_COMMENT_RE.sub("", source)
    return LINE_COMMENT_RE.sub("", source)


def _binding_name(path: str) -> str:
    return path.strip().split("::")[-1].removeprefix("r#")


def _macro_items(body: str) -> list[str]:
    names: list[str] = []
    for item in body.split(","):
        item = item.strip()
        if not item or item.startswith("$"):
            continue
        names.append(_binding_name(item))
    return names


def _pyfunction_export_names(root: Path) -> dict[str, str]:
    exports: dict[str, str] = {}
    for path in sorted((root / "src").rglob("*.rs")):
        source = _strip_comments(path.read_text())
        for match in PYFUNCTION_NAME_RE.finditer(source):
            exports[_binding_name(match.group("ident"))] = match.group("export")
    return exports


def _extract_registrations_from_files(root: Path, paths: list[Path]) -> tuple[str, ...]:
    names: set[str] = set()
    pyfunction_exports = _pyfunction_export_names(root)

    for path in sorted(paths):
        source = _strip_comments(path.read_text())

        for match in WRAP_PYFUNCTION_RE.finditer(source):
            name = _binding_name(match.group(1))
            names.add(pyfunction_exports.get(name, name))

        for match in ADD_CLASS_RE.finditer(source):
            names.add(_binding_name(match.group(1)))

        for match in REGISTER_MACRO_RE.finditer(source):
            names.update(_macro_items(match.group("body")))

    return tuple(sorted(names))


def extract_rust_registrations(root: Path = ROOT) -> tuple[str, ...]:
    paths = list((root / "src/api/python").rglob("*.rs"))
    return _extract_registrations_from_files(root, paths)


def extract_feature_registrations(root: Path = ROOT) -> dict[str, tuple[str, ...]]:
    return {
        feature: _extract_registrations_from_files(
            root,
            [root / relative_path for relative_path in relative_paths],
        )
        for feature, relative_paths in FEATURE_REGISTRATION_PATHS.items()
    }


def render_manifest(bindings: tuple[str, ...]) -> str:
    lines = [
        "# This file is generated by scripts/generate_binding_manifest.py.",
        "# Do not edit by hand.",
        "",
        "BINDINGS = (",
    ]
    lines.extend(f'    "{name}",' for name in bindings)
    lines.extend(
        [
            ")",
            "",
            "BINDING_NAMES = frozenset(BINDINGS)",
            "",
            "FEATURE_BINDINGS = {",
        ]
    )

    for feature, feature_bindings in extract_feature_registrations(ROOT).items():
        lines.append(f'    "{feature}": (')
        lines.extend(f'        "{name}",' for name in feature_bindings)
        lines.append("    ),")

    lines.extend(
        [
            "}",
            "",
            'ML_BINDING_NAMES = frozenset(FEATURE_BINDINGS["ml"])',
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the Python manifest of PyO3 binding symbols."
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if python/survival/_binding_manifest.py is stale",
    )
    args = parser.parse_args()

    expected = render_manifest(extract_rust_registrations(ROOT))

    if args.check:
        actual = MANIFEST_PATH.read_text() if MANIFEST_PATH.exists() else ""
        if actual != expected:
            diff = difflib.unified_diff(
                actual.splitlines(keepends=True),
                expected.splitlines(keepends=True),
                fromfile=str(MANIFEST_PATH),
                tofile=f"{MANIFEST_PATH} (generated)",
            )
            sys.stderr.writelines(diff)
            return 1
        return 0

    MANIFEST_PATH.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
