"""Generate ``python/survival/_survival.pyi`` from the built extension.

The *structure* of the stub (which names exist, constructor/method/function signatures with
their defaults, ``#[pyo3(get)]`` properties, enum variants) is introspected from the compiled
``survival._survival`` module, so it is exactly the runtime surface.  The *types* are inferred
from the Rust sources: ``#[pyo3(get)]`` field declarations, ``#[pymethods]`` signatures and
``#[pyfunction]`` signatures are parsed and their Rust types mapped to Python annotations
(``Vec<f64>`` -> ``list[float]``, ``Option<T>`` -> ``T | None``, pyclass names -> the class,
...); anything that cannot be resolved is ``Any``.

Usage::

    python3 scripts/generate_stubs.py            # rewrite python/survival/_survival.pyi
    python3 scripts/generate_stubs.py --check    # exit 1 if the stub is stale

The extension must be importable with every manifest symbol present (build it with
``maturin develop --features extension-module,ml``), because the manifest is the list of names
that must be typed.  ``python/tests/test_binding_contract.py`` checks, for every manifest name,
that the stub's signatures agree with ``inspect.signature`` of the runtime object.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import importlib
import importlib.util
import keyword
import re
import runpy
import shutil
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
STUB_PATH = ROOT / "python/survival/_survival.pyi"
MANIFEST_PATH = ROOT / "python/survival/_binding_manifest.py"
LINE_LENGTH = 100

HEADER = '''"""Type stubs for the Rust extension ``survival._survival``.

GENERATED by ``scripts/generate_stubs.py`` -- do not edit by hand.  Signatures come from the
compiled extension, annotations from the Rust sources; ``python3 scripts/generate_stubs.py``
regenerates the file and ``--check`` verifies it in CI.
"""
'''


def _imports(body: str) -> str:
    """Only the imports the rendered body uses (ruff flags unused ones)."""
    abc = [name for name in ("Callable", "Sequence") if f"{name}[" in body]
    lines = []
    if abc:
        lines.append(f"from collections.abc import {', '.join(abc)}")
    lines.append("from typing import Any")
    numpy_typing = [name for name in ("ArrayLike", "NDArray") if re.search(rf"\b{name}\b", body)]
    uses_np = "np." in body
    if uses_np or numpy_typing:
        lines.append("")
        if uses_np:
            lines.append("import numpy as np")
        if numpy_typing:
            lines.append(f"from numpy.typing import {', '.join(numpy_typing)}")
    return "\n".join(lines) + "\n"


# Return-type overrides for symbols whose Rust source cannot be parsed (macro-generated).
RETURN_OVERRIDES: dict[str, str] = {}

# Keys whose value is not a Python object we can annotate; the runtime tells us nothing.
_SKIP_MEMBERS = {"__doc__", "__module__", "__new__", "__init__", "__hash__", "__eq__", "__ne__"}
_DUNDER_METHODS = {
    "__repr__": "str",
    "__str__": "str",
    "__len__": "int",
    "__int__": "int",
    "__float__": "float",
    "__index__": "int",
    "__bool__": "bool",
    "__iter__": "Any",
    "__next__": "Any",
    "__getitem__": "Any",
    "__contains__": "bool",
    "__call__": "Any",
}
_COMPARISONS = {"__lt__", "__le__", "__gt__", "__ge__"}


# ---------------------------------------------------------------------------------------------
# Rust source parsing
# ---------------------------------------------------------------------------------------------


@dataclass
class RustFn:
    ident: str
    py_name: str
    params: list[tuple[str, str]]  # (name, rust type), self/py params removed
    ret: str
    kind: str = "method"  # method | static | class | new | getter | setter | function


@dataclass
class RustClass:
    ident: str
    py_name: str
    fields: dict[str, tuple[str, bool]] = field(default_factory=dict)  # name -> (type, settable)
    methods: dict[str, RustFn] = field(default_factory=dict)
    getters: dict[str, str] = field(default_factory=dict)
    setters: set[str] = field(default_factory=set)
    new: RustFn | None = None
    is_enum: bool = False


_BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
_LINE_COMMENT_RE = re.compile(r"//[^\n]*")


def _strip_comments(source: str) -> str:
    source = _BLOCK_COMMENT_RE.sub("", source)
    return _LINE_COMMENT_RE.sub("", source)


def _matching(source: str, start: int, open_ch: str, close_ch: str) -> int:
    """Index just past the bracket that closes the one at ``start``."""
    depth = 0
    i = start
    while i < len(source):
        ch = source[i]
        if ch == open_ch:
            depth += 1
        elif ch == close_ch:
            depth -= 1
            if depth == 0:
                return i + 1
        elif ch == '"':
            i = _skip_string(source, i)
            continue
        i += 1
    raise ValueError("unbalanced brackets")


def _skip_string(source: str, i: int) -> int:
    i += 1
    while i < len(source):
        if source[i] == "\\":
            i += 2
            continue
        if source[i] == '"':
            return i + 1
        i += 1
    return i


def _read_attributes(source: str, pos: int) -> tuple[list[str], int]:
    """Read consecutive ``#[...]`` attributes starting at ``pos``; return (attrs, new pos)."""
    attrs: list[str] = []
    while True:
        m = re.compile(r"\s*#\s*\[").match(source, pos)
        if m is None:
            return attrs, pos
        end = _matching(source, m.end() - 1, "[", "]")
        attrs.append(source[m.end() : end - 1].strip())
        pos = end


def _attr_name_override(attrs: list[str], attr_prefix: str) -> str | None:
    for attr in attrs:
        if attr.startswith(attr_prefix):
            m = re.search(r'\bname\s*=\s*"([^"]+)"', attr)
            if m:
                return m.group(1)
    return None


def _split_top_level(text: str, sep: str = ",") -> list[str]:
    parts: list[str] = []
    depth = 0
    current: list[str] = []
    for ch in text:
        if ch in "<([{":
            depth += 1
        elif ch in ">)]}":
            depth -= 1
        if ch == sep and depth == 0:
            parts.append("".join(current))
            current = []
        else:
            current.append(ch)
    if "".join(current).strip():
        parts.append("".join(current))
    return [p.strip() for p in parts if p.strip()]


def _parse_fn(source: str, pos: int) -> tuple[RustFn | None, int]:
    """Parse ``fn ident<...>(params) -> ret`` at ``pos``; return (fn, position after signature)."""
    m = re.compile(r"\s*(?:pub(?:\([^)]*\))?\s+)?(?:const\s+)?(?:unsafe\s+)?fn\s+(r#)?(\w+)").match(
        source, pos
    )
    if m is None:
        return None, pos
    ident = m.group(2)
    i = m.end()
    if source[i : i + 1] == "<":
        i = _matching(source, i, "<", ">")
    if source[i : i + 1] != "(":
        return None, pos
    close = _matching(source, i, "(", ")")
    raw_params = source[i + 1 : close - 1]
    j = close
    ret = "()"
    tail = re.compile(r"\s*->").match(source, j)
    if tail:
        k = tail.end()
        depth = 0
        start = k
        while k < len(source):
            ch = source[k]
            if ch in "<([":
                depth += 1
            elif ch in ">)]":
                depth -= 1
            elif ch in "{;" and depth == 0:
                break
            k += 1
        ret = source[start:k].strip()
        j = k
    where = re.compile(r"\s*where\b[^{;]*").match(source, j)
    if where:
        j = where.end()
    params: list[tuple[str, str]] = []
    for part in _split_top_level(raw_params):
        if re.match(r"^(&\s*(mut\s+)?)?(mut\s+)?self$", part) or re.match(
            r"^(mut\s+)?self\s*:", part
        ):
            continue
        if ":" not in part:
            continue
        name, _, typ = part.partition(":")
        name = name.strip().removeprefix("mut ").strip().removeprefix("r#")
        typ = typ.strip()
        if re.match(r"^(&\s*)?Python\b", typ) or name in {"py", "_py"}:
            continue
        if re.match(r"^(&\s*)?(Bound<[^>]*PyType>|Py<PyType>)", typ) or name == "cls":
            continue
        if re.match(r"^(&\s*)?PyRef(Mut)?<['a-z_ ]*Self>", typ) or name in {"slf", "this"}:
            continue
        params.append((name, typ))
    return RustFn(ident=ident, py_name=ident, params=params, ret=ret), j


def _skip_item_body(source: str, pos: int) -> int:
    """Skip a ``{ ... }`` body or a ``;`` at ``pos``."""
    m = re.compile(r"\s*").match(source, pos)
    pos = m.end() if m else pos
    if source[pos : pos + 1] == "{":
        return _matching(source, pos, "{", "}")
    if source[pos : pos + 1] == ";":
        return pos + 1
    return pos


def _parse_struct_fields(body: str, get_all: bool) -> dict[str, tuple[str, bool]]:
    fields: dict[str, tuple[str, bool]] = {}
    pos = 0
    while pos < len(body):
        attrs, pos = _read_attributes(body, pos)
        m = re.compile(r"\s*(?:pub(?:\([^)]*\))?\s+)?(r#)?(\w+)\s*:").match(body, pos)
        if m is None:
            # tuple struct entries or trailing whitespace
            nxt = body.find(",", pos)
            if nxt == -1:
                break
            pos = nxt + 1
            continue
        name = m.group(2)
        start = m.end()
        depth = 0
        k = start
        while k < len(body):
            ch = body[k]
            if ch in "<([":
                depth += 1
            elif ch in ">)]":
                depth -= 1
            elif ch == "," and depth == 0:
                break
            k += 1
        typ = body[start:k].strip()
        pos = k + 1
        pyo3 = [a for a in attrs if a.startswith("pyo3")]
        exposed = get_all or any(re.search(r"\bget\b", a) for a in pyo3)
        if not exposed:
            continue
        settable = any(re.search(r"\bset\b", a) for a in pyo3)
        py_name = _attr_name_override(pyo3, "pyo3") or name
        fields[py_name] = (typ, settable)
    return fields


def _parse_methods(body: str, cls: RustClass) -> None:
    pos = 0
    while pos < len(body):
        attrs, pos = _read_attributes(body, pos)
        fn, after = _parse_fn(body, pos)
        if fn is None:
            m = re.compile(r"\s*\S").match(body, pos)
            if m is None:
                break
            # skip a non-fn item (const, type, ...)
            semi = body.find(";", pos)
            brace = body.find("{", pos)
            if semi == -1 and brace == -1:
                break
            if brace != -1 and (semi == -1 or brace < semi):
                pos = _matching(body, brace, "{", "}")
            else:
                pos = semi + 1
            continue
        pos = _skip_item_body(body, after)
        py_name = _attr_name_override(attrs, "pyo3") or fn.ident
        if any(a == "new" for a in attrs):
            fn.kind = "new"
            fn.py_name = "__init__"
            cls.new = fn
        elif any(a.startswith("getter") for a in attrs):
            getter_attr = next(a for a in attrs if a.startswith("getter"))
            m = re.match(r"getter\s*\(\s*(\w+)\s*\)", getter_attr)
            # PyO3 strips a `get_` prefix from an unnamed getter
            name = m.group(1) if m else py_name.removeprefix("get_")
            cls.getters[name] = fn.ret
        elif any(a.startswith("setter") for a in attrs):
            setter_attr = next(a for a in attrs if a.startswith("setter"))
            m = re.match(r"setter\s*\(\s*(\w+)\s*\)", setter_attr)
            name = m.group(1) if m else py_name.removeprefix("set_")
            cls.setters.add(name)
        else:
            if any(a == "staticmethod" for a in attrs):
                fn.kind = "static"
            elif any(a == "classmethod" for a in attrs):
                fn.kind = "class"
            fn.py_name = py_name
            cls.methods[py_name] = fn


TYPE_ALIASES: dict[str, str] = {}
_TYPE_ALIAS_RE = re.compile(
    r"^\s*(?:pub(?:\([^)]*\))?\s+)?type\s+(\w+)\s*=\s*([^;]+);", re.MULTILINE
)


def parse_rust_sources(src: Path = SRC) -> tuple[dict[str, RustClass], dict[str, RustFn]]:
    classes_by_ident: dict[str, RustClass] = {}
    functions: dict[str, RustFn] = {}
    pending_methods: list[tuple[str, str]] = []

    for path in sorted(src.rglob("*.rs")):
        if "tests" in path.parts or path.name == "registration_audit.rs":
            continue
        source = _strip_comments(path.read_text())

        for m in _TYPE_ALIAS_RE.finditer(source):
            TYPE_ALIASES.setdefault(m.group(1), " ".join(m.group(2).split()))

        for m in re.finditer(r"#\s*\[\s*pyclass\b", source):
            attrs, pos = _read_attributes(source, m.start())
            pyclass_attr = next(a for a in attrs if a.startswith("pyclass"))
            head = re.compile(r"\s*(?:pub(?:\([^)]*\))?\s+)?(struct|enum)\s+(\w+)").match(
                source, pos
            )
            if head is None:
                continue
            kind, ident = head.group(1), head.group(2)
            py_name = _attr_name_override([pyclass_attr], "pyclass") or ident
            cls = RustClass(ident=ident, py_name=py_name, is_enum=kind == "enum")
            i = head.end()
            if source[i : i + 1] == "<":
                i = _matching(source, i, "<", ">")
            ws = re.compile(r"\s*").match(source, i)
            i = ws.end() if ws else i
            if source[i : i + 1] == "{":
                end = _matching(source, i, "{", "}")
                if kind == "struct":
                    get_all = re.search(r"\bget_all\b", pyclass_attr) is not None
                    cls.fields = _parse_struct_fields(source[i + 1 : end - 1], get_all)
            classes_by_ident[ident] = cls

        for m in re.finditer(r"#\s*\[\s*pymethods\s*\]", source):
            attrs, pos = _read_attributes(source, m.start())
            head = re.compile(r"\s*impl\s+(?:<[^>]*>\s*)?(\w+)").match(source, pos)
            if head is None:
                continue
            i = source.find("{", head.end())
            end = _matching(source, i, "{", "}")
            pending_methods.append((head.group(1), source[i + 1 : end - 1]))

        for m in re.finditer(r"#\s*\[\s*pyfunction\b", source):
            attrs, pos = _read_attributes(source, m.start())
            fn, _ = _parse_fn(source, pos)
            if fn is None:
                continue
            py_name = _attr_name_override(attrs, "pyfunction") or _attr_name_override(attrs, "pyo3")
            fn.py_name = py_name or fn.ident
            fn.kind = "function"
            functions[fn.py_name] = fn

    for ident, body in pending_methods:
        cls = classes_by_ident.get(ident)
        if cls is None:
            cls = RustClass(ident=ident, py_name=ident)
            classes_by_ident[ident] = cls
        _parse_methods(body, cls)

    classes = {cls.py_name: cls for cls in classes_by_ident.values()}
    return classes, functions


# ---------------------------------------------------------------------------------------------
# Rust type -> Python annotation
# ---------------------------------------------------------------------------------------------

_SCALARS = {
    "f64": "float",
    "f32": "float",
    "usize": "int",
    "isize": "int",
    "u8": "int",
    "u16": "int",
    "u32": "int",
    "u64": "int",
    "i8": "int",
    "i16": "int",
    "i32": "int",
    "i64": "int",
    "bool": "bool",
    "String": "str",
    "str": "str",
    "char": "str",
    "IdValue": "int | float | str",
}
_ARRAY_NEWTYPES = {
    "FloatVec": ("ArrayLike", "NDArray[np.float64]"),
    "IntVec": ("ArrayLike", "NDArray[np.int32]"),
    "BoolVec": ("ArrayLike", "NDArray[np.bool_]"),
    "FloatMatrix": ("ArrayLike", "NDArray[np.float64]"),
}
_TRANSPARENT = {"PyResult", "SurvivalResult", "Result", "Box", "Arc", "Rc", "PyClassInitializer"}


def _parse_type(text: str) -> tuple[str, list[str]]:
    """Split ``Ident<a, b>`` into (ident, [args]); tuples/arrays/refs are normalised first."""
    text = text.strip()
    text = re.sub(r"^&\s*(?:'\w+\s+)?(?:mut\s+)?", "", text)
    text = re.sub(r"^(?:dyn|impl)\s+", "", text)
    if text.startswith("("):
        inner = text[1:-1] if text.endswith(")") else text[1:]
        return "()", _split_top_level(inner)
    if text.startswith("["):
        inner = text[1:-1]
        elem = _split_top_level(inner, ";")[0]
        return "[]", [elem]
    m = re.match(r"^([\w:]+)\s*(?:<(.*)>)?$", text, re.DOTALL)
    if m is None:
        return text, []
    ident = m.group(1).split("::")[-1]
    args = _split_top_level(m.group(2)) if m.group(2) else []
    args = [a for a in args if not a.startswith("'")]
    return ident, args


def rust_to_python(rust: str, classes: dict[str, str], ctx: str, self_name: str | None) -> str:
    """Map a Rust type to a Python annotation; ``ctx`` is 'param' or 'return'."""
    ident, args = _parse_type(rust)
    sub = lambda t: rust_to_python(t, classes, ctx, self_name)  # noqa: E731
    if ident == "()":
        if not args:
            return "None"
        return f"tuple[{', '.join(sub(a) for a in args)}]"
    if ident == "[]":
        return f"list[{sub(args[0])}]"
    if ident in _SCALARS:
        return _SCALARS[ident]
    if ident in _ARRAY_NEWTYPES:
        return _ARRAY_NEWTYPES[ident][0 if ctx == "param" else 1]
    if ident in {"PyReadonlyArray1", "PyReadonlyArray2", "PyArray1", "PyArray2"}:
        dtype = {"f64": "np.float64", "f32": "np.float32", "i32": "np.int32", "i64": "np.int64"}
        elem = next((dtype[a] for a in args if a in dtype), "Any")
        return f"NDArray[{elem}]"
    if ident == "Self" and self_name:
        return self_name
    if ident in _TRANSPARENT and args:
        return sub(args[0])
    if ident == "Option" and args:
        inner = sub(args[0])
        return inner if inner == "Any" else f"{inner} | None"
    if ident == "Vec" and args:
        inner = sub(args[0])
        return f"Sequence[{inner}]" if ctx == "param" else f"list[{inner}]"
    if ident in {"HashMap", "BTreeMap", "IndexMap"} and len(args) == 2:
        return f"dict[{sub(args[0])}, {sub(args[1])}]"
    if ident in {"HashSet", "BTreeSet"} and args:
        return f"set[{sub(args[0])}]"
    if ident == "Cow" and args:
        return sub(args[-1])
    if ident in {"Py", "PyRef", "PyRefMut", "Bound"} and args:
        target, _ = _parse_type(args[-1])
        if target == "PyAny":
            return "Any"
        if target == "PyDict":
            return "dict[str, Any]"
        if target == "PyList":
            return "list[Any]"
        if target == "PyTuple":
            return "tuple[Any, ...]"
        if target == "PyFunction":
            return "Callable[..., Any]"
        if target in classes:
            return classes[target]
        return "Any"
    if ident in {"PyObject", "PyAny"}:
        return "Any"
    if ident == "PyDict":
        return "dict[str, Any]"
    if ident in classes:
        return classes[ident]
    if ident in TYPE_ALIASES and not args:
        return sub(TYPE_ALIASES[ident])
    return "Any"


# ---------------------------------------------------------------------------------------------
# Runtime introspection
# ---------------------------------------------------------------------------------------------


@dataclass
class Param:
    name: str
    kind: str  # positional-only handled as positional-or-keyword in stubs
    default: str | None
    annotation: str = "Any"


def parse_text_signature(text: str) -> list[Param]:
    text = re.sub(r"\$(self|cls|type|module)\s*,?\s*", "", text)
    text = text.strip()
    if text.startswith("(") and text.endswith(")"):
        text = text[1:-1]
    # a bare positional-only marker is left behind by `($self, /)`
    text = re.sub(r"^\s*/\s*$", "", text)
    tree = ast.parse(f"def _f({text}): pass")
    fn = tree.body[0]
    if not isinstance(fn, ast.FunctionDef):  # pragma: no cover - the source above is a def
        raise TypeError(f"unexpected signature text {text!r}")
    params: list[Param] = []
    args = fn.args
    positional = list(args.posonlyargs) + list(args.args)
    defaults = [None] * (len(positional) - len(args.defaults)) + list(args.defaults)
    for arg, default in zip(positional, defaults, strict=True):
        params.append(Param(arg.arg, "positional", _render_default(default)))
    if args.vararg is not None:
        params.append(Param(args.vararg.arg, "vararg", None))
    for arg, default in zip(args.kwonlyargs, args.kw_defaults, strict=True):
        params.append(Param(arg.arg, "keyword", _render_default(default)))
    if args.kwarg is not None:
        params.append(Param(args.kwarg.arg, "kwarg", None))
    return params


def _render_default(node: ast.AST | None) -> str | None:
    if node is None:
        return None
    if isinstance(node, ast.Constant):
        value = node.value
        if value is Ellipsis:
            return "..."
        if isinstance(value, str):
            return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
        if isinstance(value, float):
            return repr(value)
        return repr(value)
    return ast.unparse(node)


def _text_signature(obj: object) -> str | None:
    text = getattr(obj, "__text_signature__", None)
    if text is None and isinstance(obj, (staticmethod, classmethod)):
        text = getattr(obj.__func__, "__text_signature__", None)
    return text


# ---------------------------------------------------------------------------------------------
# Emission
# ---------------------------------------------------------------------------------------------


def _format_def(
    name: str, params: list[Param], ret: str, indent: str, decorators: list[str], self_arg: str
) -> str:
    rendered: list[str] = []
    if self_arg:
        rendered.append(self_arg)
    seen_star = False
    for p in params:
        if p.kind == "keyword" and not seen_star:
            rendered.append("*")
            seen_star = True
        if p.kind == "vararg":
            rendered.append(f"*{p.name}: Any")
            seen_star = True
            continue
        if p.kind == "kwarg":
            rendered.append(f"**{p.name}: Any")
            continue
        annotation = p.annotation
        if p.default == "None" and annotation != "Any" and not annotation.endswith("| None"):
            annotation = f"{annotation} | None"
        text = f"{p.name}: {annotation}"
        if p.default is not None:
            text += f" = {p.default}"
        rendered.append(text)
    lines = [f"{indent}{d}" for d in decorators]
    one_line = f"{indent}def {name}({', '.join(rendered)}) -> {ret}: ..."
    if len(one_line) <= LINE_LENGTH:
        lines.append(one_line)
        return "\n".join(lines)
    if rendered:
        lines.append(f"{indent}def {name}(")
        for item in rendered:
            lines.append(f"{indent}    {item},")
        closing = f"{indent}) -> {ret}: ..."
    else:
        closing = one_line
    if len(closing) <= LINE_LENGTH:
        lines.append(closing)
    else:
        lines.extend(_wrap_return(closing, ret, indent))
    return "\n".join(lines)


def _wrap_return(closing: str, ret: str, indent: str) -> list[str]:
    """Split an over-long ``) -> outer[inner]: ...`` line the way ruff's formatter does: the
    outermost subscript is opened at the end of the line, its contents go on one indented line
    when they fit (else one item per line with a trailing comma), and ``]: ...`` closes it.

    Keeping this in the generator (rather than relying on ``ruff format``) makes the output
    identical whether or not ruff is installed; ``_ruff_format`` verifies that it stays so.
    """
    head, bracket, rest = ret.partition("[")
    if not bracket or not rest.endswith("]"):
        return [closing]  # not a subscript: nothing ruff would split, leave it long
    prefix = closing[: len(closing) - len(f"{ret}: ...")]  # everything before the annotation
    inner = rest[:-1]
    lines = [f"{prefix}{head}["]
    body = f"{indent}    {inner}"
    if len(body) <= LINE_LENGTH:
        lines.append(body)
    else:
        lines.extend(f"{indent}    {item}," for item in _split_top_level(inner))
    lines.append(f"{indent}]: ...")
    return lines


def _annotate(
    params: list[Param], rust_fn: RustFn | None, classes: dict[str, str], self_name: str | None
) -> None:
    if rust_fn is None:
        return
    names = [p.name for p in params if p.kind in {"positional", "keyword"}]
    rust_names = [n for n, _ in rust_fn.params]
    if names != rust_names:
        return
    types = dict(rust_fn.params)
    for p in params:
        if p.name in types:
            p.annotation = rust_to_python(types[p.name], classes, "param", self_name)


def render_stub(
    core, manifest_names: list[str], classes: dict[str, RustClass], functions, verbose=False
) -> str:
    class_names = {cls.ident: cls.py_name for cls in classes.values()}
    class_names.update(
        {name: name for name in manifest_names if isinstance(getattr(core, name), type)}
    )
    blocks: list[str] = []
    missing_types: list[str] = []

    for name in manifest_names:
        obj = getattr(core, name)
        if isinstance(obj, type):
            blocks.append(_render_class(name, obj, classes.get(name), class_names, missing_types))
        else:
            blocks.append(
                _render_function(name, obj, functions.get(name), class_names, missing_types)
            )
    if verbose and missing_types:
        print("no Rust type found for:", ", ".join(missing_types), file=sys.stderr)
    body = _join_blocks(blocks)
    return HEADER + "\n" + _imports(body) + "\n" + body + "\n"


def _join_blocks(blocks: list[str]) -> str:
    """Ruff's stub layout: consecutive top-level ``def``s touch, classes are separated by one
    blank line."""
    out: list[str] = []
    for index, block in enumerate(blocks):
        if index:
            touching = blocks[index - 1].startswith("def ") and block.startswith("def ")
            out.append("\n" if touching else "\n\n")
        out.append(block)
    return "".join(out)


def _render_function(name, obj, rust_fn, class_names, missing_types) -> str:
    text = _text_signature(obj) or "(*args, **kwargs)"
    params = parse_text_signature(text)
    _annotate(params, rust_fn, class_names, None)
    if name in RETURN_OVERRIDES:
        ret = RETURN_OVERRIDES[name]
    elif name.startswith("load_"):
        # the dataset loaders are macro-generated: one dict of column lists per data frame
        ret = "dict[str, list[Any]]"
    elif rust_fn is not None:
        ret = rust_to_python(rust_fn.ret, class_names, "return", None)
    else:
        ret = "Any"
        missing_types.append(name)
    return _format_def(name, params, ret, "", [], "")


def _render_class(name, cls, rust_cls, class_names, missing_types) -> str:
    """One class block; members are ordered deterministically because PyO3's type ``__dict__``
    order is not stable across processes: variants, ``__init__``, dunders, methods, properties,
    each group alphabetical."""
    lines = [f"class {name}:"]
    members: list[str] = []
    variants = sorted(k for k, v in cls.__dict__.items() if isinstance(v, cls))
    for variant in variants:
        if keyword.iskeyword(variant):
            # e.g. ScreeningRule.None: only reachable through getattr
            continue
        members.append(f"    {variant}: {name}")

    init_text = cls.__text_signature__
    if init_text is not None:
        params = parse_text_signature(init_text)
        _annotate(params, rust_cls.new if rust_cls else None, class_names, name)
        members.append(_format_def("__init__", params, "None", "    ", [], "self"))

    dunders: list[str] = []
    methods: list[str] = []
    properties: list[str] = []
    for key, value in sorted(cls.__dict__.items()):
        if key in _SKIP_MEMBERS or key in _COMPARISONS or key in variants:
            continue
        if keyword.iskeyword(key):
            # e.g. FastCoxConfig.lambda: only reachable through getattr, not declarable in a stub
            continue
        if key.startswith("__") and key.endswith("__"):
            if key in _DUNDER_METHODS:
                text = _text_signature(value)
                params = parse_text_signature(text) if text else []
                dunders.append(_format_def(key, params, _DUNDER_METHODS[key], "    ", [], "self"))
            continue
        type_name = type(value).__name__
        if type_name == "getset_descriptor":
            ret, settable = "Any", False
            if rust_cls is not None:
                if key in rust_cls.fields:
                    rust_type, settable = rust_cls.fields[key]
                    ret = rust_to_python(rust_type, class_names, "return", name)
                elif key in rust_cls.getters:
                    ret = rust_to_python(rust_cls.getters[key], class_names, "return", name)
                    settable = key in rust_cls.setters
                else:
                    missing_types.append(f"{name}.{key}")
            else:
                missing_types.append(f"{name}.{key}")
            properties.append("    @property")
            properties.append(f"    def {key}(self) -> {ret}: ...")
            if settable:
                properties.append(f"    @{key}.setter")
                properties.append(f"    def {key}(self, value: {ret}) -> None: ...")
        elif type_name in {"method_descriptor", "builtin_function_or_method"} or isinstance(
            value, (staticmethod, classmethod)
        ):
            text = _text_signature(value) or "(*args, **kwargs)"
            params = parse_text_signature(text)
            rust_fn = rust_cls.methods.get(key) if rust_cls else None
            _annotate(params, rust_fn, class_names, name)
            ret = rust_to_python(rust_fn.ret, class_names, "return", name) if rust_fn else "Any"
            if rust_fn is None:
                missing_types.append(f"{name}.{key}")
            if isinstance(value, staticmethod):
                methods.append(_format_def(key, params, ret, "    ", ["@staticmethod"], ""))
            elif isinstance(value, classmethod):
                methods.append(_format_def(key, params, ret, "    ", ["@classmethod"], "cls"))
            else:
                methods.append(_format_def(key, params, ret, "    ", [], "self"))
    members.extend(dunders)
    members.extend(methods)
    members.extend(properties)
    if not members:
        members.append("    ...")
    lines.extend(members)
    return "\n".join(lines)


# ---------------------------------------------------------------------------------------------


def load_extension():
    """The built extension: the installed package (a wheel, or `maturin develop`), else the
    source tree with the extension built into it."""

    try:
        return importlib.import_module("survival._survival")
    except ImportError:
        sys.path.insert(0, str(ROOT / "python"))
        return importlib.import_module("survival._survival")


def manifest_names() -> list[str]:
    manifest = runpy.run_path(str(MANIFEST_PATH))
    return sorted(manifest["BINDINGS"])


def generate(verbose: bool = False) -> str:
    core = load_extension()
    names = manifest_names()
    absent = [n for n in names if not hasattr(core, n)]
    if absent:
        raise SystemExit(
            "the extension lacks manifest symbols (build it with "
            "`maturin develop --features extension-module,ml`): " + ", ".join(absent[:10])
        )
    classes, functions = parse_rust_sources()
    return _ruff_format(render_stub(core, names, classes, functions, verbose=verbose))


def _ruff_command() -> list[str]:
    """``ruff`` from PATH, else the one installed next to this interpreter (CI runs
    ``.venv/bin/python`` without activating the venv), else a loud failure -- never silently
    emit unverified text, because the checked-in stub must not depend on the caller's PATH."""
    ruff = shutil.which("ruff")
    if ruff is not None:
        return [ruff]
    if importlib.util.find_spec("ruff") is not None:
        return [sys.executable, "-m", "ruff"]
    raise SystemExit(
        "ruff is required to verify the generated stub's layout; install it into this "
        "interpreter's environment (`pip install ruff` / `uv pip install ruff`)"
    )


def _ruff_format(text: str) -> str:
    """Run ``ruff format`` over the rendered stub and require it to be a no-op.

    The emitters above already produce ruff's layout, so the generator's output is the same with
    or without ruff; ruff only proves that.  A difference means an emitter fell out of step with
    the formatter (or ruff changed), and is reported rather than papered over so the stub cannot
    depend on which ruff, if any, happens to be on PATH.
    """
    result = subprocess.run(  # noqa: S603 - ruff from PATH or this interpreter, fixed arguments
        [*_ruff_command(), "format", "--stdin-filename", str(STUB_PATH), "-"],
        input=text,
        capture_output=True,
        text=True,
        check=False,
        cwd=ROOT,
    )
    if result.returncode != 0:
        raise SystemExit(f"ruff format failed on the generated stub:\n{result.stderr}")
    if result.stdout != text:
        diff = "".join(
            difflib.unified_diff(
                text.splitlines(keepends=True),
                result.stdout.splitlines(keepends=True),
                fromfile="generate_stubs.py output",
                tofile="ruff format",
                n=1,
            )
        )
        raise SystemExit(
            "scripts/generate_stubs.py emitted text that ruff would reformat; teach the emitter "
            "(_format_def / _wrap_return / _join_blocks) the formatter's layout:\n" + diff
        )
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if the stub is stale")
    parser.add_argument(
        "--verbose", action="store_true", help="list the symbols whose Rust type was not found"
    )
    args = parser.parse_args()
    expected = generate(verbose=args.verbose)
    if args.check:
        actual = STUB_PATH.read_text() if STUB_PATH.exists() else ""
        if actual != expected:
            sys.stderr.writelines(
                difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=str(STUB_PATH),
                    tofile=f"{STUB_PATH} (generated)",
                )
            )
            return 1
        return 0
    STUB_PATH.write_text(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
