"""Support code for the R differential fixtures in ``test/r/fixtures``.

The fixtures are generated by ``test/r/generate_fixtures.R``; see
``test/r/README.md`` for the schema.  This module knows how to

* load a topic document and its cases,
* materialise the data a case refers to (a bundled dataset loaded through
  ``survival.datasets`` with the same row subset R used, or an inline frame
  stored in the topic document),
* decode the JSON encoding of R values (``null`` for ``NA``, the strings
  ``"NaN"``/``"Inf"``/``"-Inf"`` for non-finite numbers, row-major nested
  arrays for matrices), and
* compare Python results against the R values with the tolerances used by
  ``test_r_fixtures.py``.
"""

from __future__ import annotations

import json
import math
import os
from collections.abc import Iterable, Mapping, Sequence
from functools import cache
from pathlib import Path
from typing import Any

FIXTURE_DIR = Path(__file__).resolve().parents[2] / "test" / "r" / "fixtures"

# Relative tolerances (see test/r/README.md).
RTOL_COEF = 1e-8  # coefficients, curves, residuals, linear predictors
RTOL_VAR = 1e-6  # variances, standard errors, test statistics, p-values
RTOL_EXACT = 0.0  # counts

# Environment variable naming a JSONL file that receives one record per
# fixture test (``{"id", "kind", "message"}`` with kind pass / mismatch /
# missing feature / error); used to build the KNOWN_FAILURES burndown list.
COLLECT_ENV = "R_FIXTURES_COLLECT"


class UnsupportedCaseError(Exception):
    """The Python API cannot express this fixture case (missing feature)."""


class FixtureMismatchError(AssertionError):
    """A numeric or structural difference between R and Python."""


# ---------------------------------------------------------------------------
# Fixture documents
# ---------------------------------------------------------------------------


def topic_names() -> list[str]:
    return sorted(path.stem for path in FIXTURE_DIR.glob("*.json"))


@cache
def load_topic(topic: str) -> dict[str, Any]:
    with open(FIXTURE_DIR / f"{topic}.json", encoding="utf-8") as handle:
        return json.load(handle)


def cases(topic: str) -> list[dict[str, Any]]:
    """The cases of a topic; jsonlite writes empty named lists as ``[]``, normalise them."""

    out = []
    for case in load_topic(topic)["cases"]:
        case = dict(case)
        if isinstance(case.get("args"), list):
            case["args"] = {}
        expected = case.get("expected")
        if isinstance(expected, Mapping):
            case["expected"] = {
                key: ({} if key == "coef" and isinstance(value, list) and not value else value)
                for key, value in expected.items()
            }
        out.append(case)
    return out


def case_id(topic: str, case: Mapping[str, Any], aspect: str | None = None) -> str:
    base = f"{topic}/{case['name']}"
    return base if aspect is None else f"{base}/{aspect}"


def is_r_error(value: Any) -> bool:
    return isinstance(value, Mapping) and "r_error" in value and len(value) == 1


# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------


class RFactor(list):
    """A column with R factor levels attached as ``categories``."""

    def __init__(self, values: Iterable[Any], categories: Sequence[Any]):
        super().__init__(values)
        self.categories = tuple(categories)

    def codes(self) -> list[int | None]:
        index = {level: idx for idx, level in enumerate(self.categories)}
        return [None if value is None else index[value] for value in self]


# R dataset name -> candidate loader names in the Python package.  The
# first loader found is used; a dataset with no loader raises Unsupported.
DATASET_LOADERS: dict[str, tuple[str, ...]] = {
    "nafld1": ("load_nafld1", "load_nafld"),
    "rhDNase": ("load_rhdnase", "load_rhDNase"),
    "cgd0": ("load_cgd0",),
}


def _loader_module() -> Any:
    try:
        import survival.datasets as datasets

        return datasets
    except ImportError:
        # A stale extension without the newest loaders makes the curated
        # module fail on import; fall back to the raw extension so the
        # remaining datasets stay reachable.
        import survival._survival as native

        return native


@cache
def load_dataset(name: str) -> dict[str, list[Any]]:
    module = _loader_module()
    candidates = DATASET_LOADERS.get(name, (f"load_{name}",))
    for candidate in candidates:
        loader = getattr(module, candidate, None)
        if loader is not None:
            raw = loader()
            return {
                key: list(value)
                for key, value in raw.items()
                if not (isinstance(key, str) and key.startswith("_"))
            }
    raise UnsupportedCaseError(
        f"no Python loader for dataset {name!r} (tried {', '.join(candidates)})"
    )


def decode_frame(frame: Mapping[str, Any]) -> dict[str, list[Any]]:
    """Decode an inline data frame written by ``jframe`` in the generator."""

    factors = frame.get("factors") or {}
    columns: dict[str, list[Any]] = {}
    for name, values in frame["columns"].items():
        if name in factors:
            columns[name] = RFactor(values, factors[name])
        elif values and isinstance(values[0], list):
            columns[name] = [decode_vector(row) for row in values]
        else:
            columns[name] = decode_vector(values)
    return columns


def subset_columns(columns: Mapping[str, Sequence[Any]], rows: Sequence[int] | None):
    if rows is None:
        return {
            name: (
                RFactor(values, values.categories) if isinstance(values, RFactor) else list(values)
            )
            for name, values in columns.items()
        }
    indices = [row - 1 for row in rows]
    out: dict[str, Any] = {}
    for name, values in columns.items():
        picked = [values[idx] for idx in indices]
        if isinstance(values, RFactor):
            picked = RFactor(picked, values.categories)
        out[name] = picked
    return out


def case_data(topic: str, case: Mapping[str, Any]) -> dict[str, Any]:
    """The data frame (dict of columns) a case operates on."""

    doc = load_topic(topic)
    if "data_ref" in case:
        columns = decode_frame(doc["data"][case["data_ref"]])
    elif "dataset" in case:
        columns = load_dataset(case["dataset"])
        for name, levels in (case.get("factors") or {}).items():
            if name in columns:
                columns[name] = RFactor(columns[name], levels)
    else:
        return {}
    return subset_columns(columns, case.get("rows"))


def newdata_frame(expected: Mapping[str, Any]) -> dict[str, Any] | None:
    frame = expected.get("newdata")
    return None if frame is None else decode_frame(frame)


def nrow(columns: Mapping[str, Sequence[Any]]) -> int:
    return len(next(iter(columns.values()))) if columns else 0


# ---------------------------------------------------------------------------
# Value decoding
# ---------------------------------------------------------------------------

_SPECIAL = {"NaN": math.nan, "Inf": math.inf, "-Inf": -math.inf}


def decode_scalar(value: Any) -> Any:
    if isinstance(value, str) and value in _SPECIAL:
        return _SPECIAL[value]
    return value


def decode_vector(values: Any) -> Any:
    if isinstance(values, list):
        return [decode_vector(value) for value in values]
    return decode_scalar(values)


def as_float_list(values: Any) -> list[float]:
    out = []
    for value in _iter_values(values):
        if isinstance(value, (list, tuple)) and len(value) == 1:
            value = value[0]
        if hasattr(value, "tolist"):
            value = value.tolist()
        out.append(math.nan if value is None else float(value))
    return out


def _iter_values(values: Any) -> list[Any]:
    if values is None:
        return []
    if hasattr(values, "tolist"):
        values = values.tolist()
    if isinstance(values, (int, float)):
        return [values]
    return list(values)


def flatten(values: Any) -> list[Any]:
    if hasattr(values, "tolist"):
        values = values.tolist()
    if isinstance(values, (list, tuple)):
        out: list[Any] = []
        for value in values:
            out.extend(flatten(value))
        return out
    return [values]


def transpose(matrix: Sequence[Sequence[Any]]) -> list[list[Any]]:
    if not matrix:
        return []
    return [list(column) for column in zip(*matrix, strict=True)]


def column(matrix: Sequence[Sequence[Any]], idx: int) -> list[Any]:
    return [row[idx] for row in matrix]


# ---------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------


def _is_missing(value: Any) -> bool:
    if value is None:
        return True
    try:
        return math.isnan(float(value))
    except (TypeError, ValueError):
        return False


def _shape_note(actual: Any, expected: Any) -> str:
    return f"actual {type(actual).__name__}, expected {type(expected).__name__}"


def array_scale(expected: Any) -> float:
    """Largest finite magnitude in a (nested) list of fixture numbers.

    Mappings inside the list are not entered: they are separate R objects
    and get their own scale when ``assert_close`` recurses into them.
    """

    scale = 0.0
    stack = [expected]
    while stack:
        value = stack.pop()
        if isinstance(value, list):
            stack.extend(value)
        elif isinstance(value, bool) or value is None or isinstance(value, Mapping):
            continue
        elif isinstance(value, (int, float)):
            if math.isfinite(value):
                scale = max(scale, abs(value))
        elif isinstance(value, str):
            decoded = decode_scalar(value)
            if isinstance(decoded, float) and math.isfinite(decoded):
                scale = max(scale, abs(decoded))
    return scale


def assert_close(
    actual: Any,
    expected: Any,
    *,
    rtol: float = RTOL_COEF,
    atol: float = 0.0,
    path: str = "value",
) -> None:
    """Recursively compare ``actual`` against a decoded fixture value.

    Scalars are compared as ``|a - e| <= atol + rtol * |e|``.  For a vector
    or matrix the absolute tolerance is raised to ``rtol * max|expected|``
    over the whole array (the way R's ``all.equal`` measures the difference
    relative to the size of the object), so floating-point noise around zero
    (``1e-17`` against an exact ``0``) inside an otherwise matching vector is
    not reported as a mismatch.
    """

    expected = decode_scalar(expected)
    if hasattr(actual, "tolist"):
        actual = actual.tolist()
    if isinstance(expected, Mapping):
        if not isinstance(actual, Mapping):
            raise FixtureMismatchError(
                f"{path}: expected a mapping ({_shape_note(actual, expected)})"
            )
        missing = [key for key in expected if key not in actual]
        if missing:
            raise FixtureMismatchError(f"{path}: missing keys {missing}")
        for key, value in expected.items():
            assert_close(actual[key], value, rtol=rtol, atol=atol, path=f"{path}.{key}")
        return
    if isinstance(expected, list):
        if isinstance(actual, (str, bytes)) or not isinstance(actual, (list, tuple)):
            if isinstance(actual, (int, float)) and len(expected) == 1:
                actual = [actual]
            else:
                raise FixtureMismatchError(
                    f"{path}: expected a sequence of length {len(expected)} "
                    f"({_shape_note(actual, expected)})"
                )
        if len(actual) != len(expected):
            raise FixtureMismatchError(
                f"{path}: length {len(actual)} differs from expected {len(expected)}"
            )
        atol = max(atol, rtol * array_scale(expected))
        for idx, (a_value, e_value) in enumerate(zip(actual, expected, strict=True)):
            assert_close(a_value, e_value, rtol=rtol, atol=atol, path=f"{path}[{idx}]")
        return
    if isinstance(expected, bool):
        if bool(actual) != expected:
            raise FixtureMismatchError(f"{path}: {actual!r} != {expected!r}")
        return
    if isinstance(expected, str):
        if str(actual) != expected:
            raise FixtureMismatchError(f"{path}: {actual!r} != {expected!r}")
        return
    if expected is None or (isinstance(expected, float) and math.isnan(expected)):
        if not _is_missing(actual):
            raise FixtureMismatchError(f"{path}: expected NA/NaN, got {actual!r}")
        return
    if isinstance(expected, float) and math.isinf(expected):
        try:
            actual_value = float(actual)
        except (TypeError, ValueError) as exc:
            raise FixtureMismatchError(f"{path}: expected {expected}, got {actual!r}") from exc
        if not (
            math.isinf(actual_value)
            and math.copysign(1, actual_value) == math.copysign(1, expected)
        ):
            raise FixtureMismatchError(f"{path}: expected {expected}, got {actual!r}")
        return
    if isinstance(actual, (list, tuple)) and len(actual) == 1:
        actual = actual[0]
    try:
        actual_value = float(actual)
    except (TypeError, ValueError) as exc:
        raise FixtureMismatchError(f"{path}: cannot compare {actual!r} with {expected!r}") from exc
    if math.isnan(actual_value) or math.isinf(actual_value):
        raise FixtureMismatchError(f"{path}: got {actual_value}, expected {expected}")
    expected_value = float(expected)
    if abs(actual_value - expected_value) > atol + rtol * abs(expected_value):
        raise FixtureMismatchError(
            f"{path}: {actual_value!r} != {expected_value!r} (rtol={rtol}, atol={atol})"
        )


def assert_exact(actual: Any, expected: Any, *, path: str = "value") -> None:
    assert_close(actual, expected, rtol=0.0, atol=0.0, path=path)


def assert_named_values(
    actual_names: Sequence[str] | None,
    actual_values: Sequence[float],
    expected: Mapping[str, Any],
    *,
    rtol: float = RTOL_COEF,
    path: str = "coef",
    check_names: bool = False,
) -> None:
    """Compare a named R vector (JSON object) against Python values by position."""

    expected_values = list(expected.values())
    if len(actual_values) != len(expected_values):
        raise FixtureMismatchError(
            f"{path}: {len(actual_values)} values, expected {len(expected_values)} "
            f"({list(expected)})"
        )
    if check_names and (actual_names is None or list(actual_names) != list(expected)):
        raise FixtureMismatchError(f"{path}: names {list(actual_names or [])} != {list(expected)}")
    assert_close(list(actual_values), expected_values, rtol=rtol, path=path)


def assert_matrix_close(
    actual: Any,
    expected: Sequence[Sequence[Any]],
    *,
    rtol: float = RTOL_COEF,
    atol: float = 0.0,
    path: str = "matrix",
) -> None:
    if hasattr(actual, "tolist"):
        actual = actual.tolist()
    rows = [list(row) if isinstance(row, (list, tuple)) else [row] for row in actual]
    assert_close(rows, list(expected), rtol=rtol, atol=atol, path=path)


def r_strata_value(name: str) -> str:
    """The value part of an R strata label such as ``sex=1`` -> ``1``."""

    if "=" in name:
        return name.split("=", 1)[1]
    return name


# ---------------------------------------------------------------------------
# Failure collection (burndown support)
# ---------------------------------------------------------------------------


def record_outcome(test_id: str, kind: str, message: str) -> None:
    path = os.environ.get(COLLECT_ENV)
    if not path:
        return
    with open(path, "a", encoding="utf-8") as handle:
        handle.write(json.dumps({"id": test_id, "kind": kind, "message": message}) + "\n")
