"""Contract between the Rust registrations, the binding manifest, the domain modules, the
stubs and the package root.

* ``_binding_manifest.py`` is generated from ``src/api/python`` and from the ``bind_names``
  lists of the domain modules; every registered binding is bound by exactly one module.
* ``_survival.pyi`` is generated by ``scripts/generate_stubs.py``: its name set equals the
  manifest and, for every manifest name, its signatures agree with ``inspect.signature`` of
  the runtime object (``test_stub_signature_matches_runtime``).
* ``__init__.pyi`` mirrors the root export lists of ``__init__.py``; ``r_api.pyi`` tracks the
  public signatures of ``survival.r``.
"""

import ast
import dataclasses
import importlib
import importlib.util
import inspect
import keyword
import re
import runpy
import subprocess
import sys
import tomllib
from pathlib import Path

import pytest

from .helpers import setup_survival_import

ROOT = Path(__file__).resolve().parents[2]
_MANIFEST_SCRIPT = ROOT / "scripts/generate_binding_manifest.py"
_MANIFEST_SPEC = importlib.util.spec_from_file_location(
    "generate_binding_manifest",
    _MANIFEST_SCRIPT,
)
if _MANIFEST_SPEC is None or _MANIFEST_SPEC.loader is None:
    raise RuntimeError(f"Could not load {_MANIFEST_SCRIPT}")
_MANIFEST_MODULE = importlib.util.module_from_spec(_MANIFEST_SPEC)
_MANIFEST_SPEC.loader.exec_module(_MANIFEST_MODULE)

extract_feature_registrations = _MANIFEST_MODULE.extract_feature_registrations
extract_python_module_bindings = _MANIFEST_MODULE.extract_python_module_bindings
extract_rust_registrations = _MANIFEST_MODULE.extract_rust_registrations

PACKAGE_ROOT = ROOT / "python/survival"
STUB_PATH = PACKAGE_ROOT / "_survival.pyi"
README = ROOT / "README.md"
MODULE_METADATA_NAMES = {"__all__", "__version__"}


def _manifest_bindings() -> tuple[str, ...]:
    manifest = runpy.run_path(str(PACKAGE_ROOT / "_binding_manifest.py"))
    return tuple(manifest["BINDINGS"])


def _feature_bindings() -> dict[str, tuple[str, ...]]:
    manifest = runpy.run_path(str(PACKAGE_ROOT / "_binding_manifest.py"))
    return manifest["FEATURE_BINDINGS"]


def _module_bindings() -> dict[str, tuple[str, ...]]:
    manifest = runpy.run_path(str(PACKAGE_ROOT / "_binding_manifest.py"))
    return manifest["MODULE_BINDINGS"]


def _has_ml_bindings(core) -> bool:
    sentinels = ("DeepSurv", "survival_forest", "GradientBoostSurvival")
    return any(hasattr(core, name) for name in sentinels)


def _literal_string_list(node: ast.AST) -> list[str]:
    if not isinstance(node, ast.List | ast.Tuple):
        return []
    return [
        element.value
        for element in node.elts
        if isinstance(element, ast.Constant) and isinstance(element.value, str)
    ]


def _binding_names_by_module() -> dict[str, set[str]]:
    return {module: set(names) for module, names in extract_python_module_bindings(ROOT).items()}


def _root_export_lists() -> dict[str, list[str]]:
    """The three export lists of ``__init__.py`` (the single source of the root surface)."""
    tree = ast.parse((PACKAGE_ROOT / "__init__.py").read_text())
    lists: dict[str, list[str]] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if not isinstance(target, ast.Name):
                continue
            if target.id == "_PUBLIC_MODULES" and isinstance(node.value, ast.Dict):
                lists[target.id] = [
                    key.value
                    for key in node.value.keys
                    if isinstance(key, ast.Constant) and isinstance(key.value, str)
                ]
            elif target.id in {"_SKLEARN_EXPORTS", "_R_EXPORTS"}:
                lists[target.id] = _literal_string_list(node.value)
    assert set(lists) == {"_PUBLIC_MODULES", "_SKLEARN_EXPORTS", "_R_EXPORTS"}
    return lists


def _top_level_names() -> set[str]:
    lists = _root_export_lists()
    return (
        set(lists["_PUBLIC_MODULES"])
        | set(lists["_R_EXPORTS"])
        | set(lists["_SKLEARN_EXPORTS"])
        | MODULE_METADATA_NAMES
    )


def _sklearn_names() -> set[str]:
    tree = ast.parse((PACKAGE_ROOT / "sklearn_compat.py").read_text())
    names = {
        node.name
        for node in tree.body
        if isinstance(node, ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef)
        and not node.name.startswith("_")
    }
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for target in node.targets:
            if isinstance(target, ast.Name) and target.id == "_PUBLIC_EXPORTS":
                names.update(_literal_string_list(node.value))
            if isinstance(target, ast.Name) and target.id == "__all__":
                names.update(_literal_string_list(node.value))
    return names


def _remove_survival_modules() -> None:
    for name in tuple(sys.modules):
        if name == "survival" or name.startswith("survival."):
            sys.modules.pop(name, None)


@pytest.fixture(autouse=True)
def _restore_survival_modules():
    """Put back whatever ``survival`` modules were imported before this test.

    Several tests here purge ``survival`` from ``sys.modules`` to watch the package
    import itself lazily.  Re-importing the extension builds fresh type objects, so a
    later test holding a fit made against the old ones fails its ``isinstance`` checks
    (``_is_survreg_fit`` and friends).  Restoring keeps that leakage inside this file.
    """

    saved = {
        name: module
        for name, module in sys.modules.items()
        if name == "survival" or name.startswith("survival.")
    }
    try:
        yield
    finally:
        _remove_survival_modules()
        sys.modules.update(saved)


def _pyi_top_level_names(path: Path) -> set[str]:
    tree = ast.parse(path.read_text(), filename=str(path))
    return {
        node.name
        for node in tree.body
        if isinstance(node, ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef)
    }


def _pyi_function_arg_names(path: Path, name: str) -> list[str]:
    tree = ast.parse(path.read_text(), filename=str(path))
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == name:
            args = [arg.arg for arg in node.args.posonlyargs]
            args.extend(arg.arg for arg in node.args.args)
            args.extend(arg.arg for arg in node.args.kwonlyargs)
            return args
    raise AssertionError(f"{name} not found in {path}")


def _pyi_function_kwarg_name(path: Path, name: str) -> str | None:
    tree = ast.parse(path.read_text(), filename=str(path))
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == name:
            return node.args.kwarg.arg if node.args.kwarg is not None else None
    raise AssertionError(f"{name} not found in {path}")


def _pyi_function_return(path: Path, name: str) -> str:
    tree = ast.parse(path.read_text(), filename=str(path))
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and node.name == name:
            if node.returns is None:
                return ""
            return ast.unparse(node.returns)
    raise AssertionError(f"{name} not found in {path}")


def _pyi_class_node(path: Path, name: str) -> ast.ClassDef:
    tree = ast.parse(path.read_text(), filename=str(path))
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name == name:
            return node
    raise AssertionError(f"{name} not found in {path}")


def _pyi_class_method_arg_names(path: Path, class_name: str, method_name: str) -> list[str]:
    class_node = _pyi_class_node(path, class_name)
    for node in class_node.body:
        if isinstance(node, ast.FunctionDef) and node.name == method_name:
            args = [arg.arg for arg in node.args.posonlyargs]
            args.extend(arg.arg for arg in node.args.args)
            args.extend(arg.arg for arg in node.args.kwonlyargs)
            return args
    raise AssertionError(f"{class_name}.{method_name} not found in {path}")


def _pyi_class_annotation_names(path: Path, class_name: str) -> set[str]:
    class_node = _pyi_class_node(path, class_name)
    return {
        node.target.id
        for node in class_node.body
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name)
    }


def _readme_python_blocks() -> list[str]:
    return re.findall(r"```python\n(.*?)```", README.read_text(), flags=re.DOTALL)


def _format_missing(missing: list[tuple[str, str]]) -> str:
    return "\n".join(f"{source}: {name}" for source, name in missing)


# ---------------------------------------------------------------------------------------------
# Manifest <-> Rust registrations <-> domain modules
# ---------------------------------------------------------------------------------------------


def test_generated_manifest_matches_rust_registration():
    assert _manifest_bindings() == extract_rust_registrations(ROOT)


def test_generated_feature_manifest_matches_rust_registration():
    assert _feature_bindings() == extract_feature_registrations(ROOT)


def test_generated_module_manifest_matches_python_modules():
    assert _module_bindings() == extract_python_module_bindings(ROOT)


def test_every_registered_binding_is_bound_by_exactly_one_domain_module():
    manifest = set(_manifest_bindings())
    owners: dict[str, list[str]] = {}
    for module, names in _binding_names_by_module().items():
        for name in names:
            owners.setdefault(name, []).append(module)

    unregistered = [
        (f"python/survival/{module}.py", name)
        for name, modules in sorted(owners.items())
        if name not in manifest
        for module in modules
    ]
    unbound = [
        ("python/survival/_binding_manifest.py", name) for name in sorted(manifest - set(owners))
    ]
    duplicated = [
        (", ".join(modules), name) for name, modules in sorted(owners.items()) if len(modules) > 1
    ]

    assert unregistered == [], _format_missing(unregistered)
    assert unbound == [], _format_missing(unbound)
    assert duplicated == [], _format_missing(duplicated)


def _bind_names_literals() -> dict[str, set[str]]:
    """The names each domain module binds straight from the extension (no Python wrapper)."""
    modules: dict[str, set[str]] = {}
    for path in sorted(PACKAGE_ROOT.glob("*.py")):
        if path.name.startswith("_") or path.name in {"__init__.py", "sklearn_compat.py"}:
            continue
        tree = ast.parse(path.read_text(), filename=str(path))
        names: set[str] = set()
        for node in ast.walk(tree):
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Name)
                and node.func.id == "bind_names"
                and len(node.args) >= 2
            ):
                names.update(_literal_string_list(node.args[1]))
        if names:
            modules[path.stem] = names
    return modules


def test_domain_modules_expose_exactly_their_bindings():
    setup_survival_import()
    core = importlib.import_module("survival._survival")
    ml_names = set(_feature_bindings()["ml"]) if not _has_ml_bindings(core) else set()
    direct = _bind_names_literals()
    for module_name, names in _binding_names_by_module().items():
        module = importlib.import_module(f"survival.{module_name}")
        expected = names - ml_names
        assert set(module.__all__) == expected, module_name
        for name in expected:
            if name in direct.get(module_name, set()):
                assert getattr(module, name) is getattr(core, name), f"{module_name}.{name}"
            else:
                assert callable(getattr(module, name)), f"{module_name}.{name}"


# ---------------------------------------------------------------------------------------------
# _survival.pyi <-> runtime
# ---------------------------------------------------------------------------------------------


def test_survival_stub_declares_exactly_the_registered_bindings():
    manifest = set(_manifest_bindings())
    stub_names = _pyi_top_level_names(STUB_PATH)

    extra = [("python/survival/_survival.pyi", name) for name in sorted(stub_names - manifest)]
    missing = [
        ("python/survival/_binding_manifest.py", name) for name in sorted(manifest - stub_names)
    ]

    assert extra == [], _format_missing(extra)
    assert missing == [], _format_missing(missing)


def test_survival_stub_is_generated_from_the_extension():
    setup_survival_import()
    core = importlib.import_module("survival._survival")
    if not _has_ml_bindings(core):
        pytest.skip("stub generation needs the extension built with the ml feature")
    result = subprocess.run(  # noqa: S603 - fixed interpreter and script arguments
        [sys.executable, str(ROOT / "scripts/generate_stubs.py"), "--check"],
        capture_output=True,
        text=True,
        check=False,
        cwd=ROOT,
    )
    assert result.returncode == 0, result.stderr[-4000:]


@dataclasses.dataclass(frozen=True)
class _Signature:
    params: tuple[tuple[str, str, object], ...]  # (name, kind, default or NO_DEFAULT)


_NO_DEFAULT = "<no default>"


def _runtime_signature(obj) -> _Signature | None:
    try:
        signature = inspect.signature(obj)
    except (TypeError, ValueError):
        return None
    params = []
    for parameter in signature.parameters.values():
        if parameter.name in {"self", "cls"}:
            continue
        default = _NO_DEFAULT if parameter.default is inspect.Parameter.empty else parameter.default
        params.append((parameter.name, parameter.kind.name, default))
    return _Signature(tuple(params))


def _stub_signature(node: ast.FunctionDef) -> _Signature:
    args = node.args
    params = []
    positional = list(args.posonlyargs) + list(args.args)
    defaults = [None] * (len(positional) - len(args.defaults)) + list(args.defaults)
    for index, (arg, default) in enumerate(zip(positional, defaults, strict=True)):
        if arg.arg in {"self", "cls"} and index == 0:
            continue
        kind = "POSITIONAL_ONLY" if arg in args.posonlyargs else "POSITIONAL_OR_KEYWORD"
        params.append((arg.arg, kind, _stub_default(default)))
    if args.vararg is not None:
        params.append((args.vararg.arg, "VAR_POSITIONAL", _NO_DEFAULT))
    for arg, default in zip(args.kwonlyargs, args.kw_defaults, strict=True):
        params.append((arg.arg, "KEYWORD_ONLY", _stub_default(default)))
    if args.kwarg is not None:
        params.append((args.kwarg.arg, "VAR_KEYWORD", _NO_DEFAULT))
    return _Signature(tuple(params))


def _stub_default(node: ast.AST | None):
    if node is None:
        return _NO_DEFAULT
    return ast.literal_eval(node)


def _stub_nodes() -> dict[str, ast.AST]:
    tree = ast.parse(STUB_PATH.read_text(), filename=str(STUB_PATH))
    return {
        node.name: node for node in tree.body if isinstance(node, ast.ClassDef | ast.FunctionDef)
    }


_STUB_NODES = _stub_nodes()
_SKIPPED_DUNDERS = {"__doc__", "__module__", "__new__", "__init__", "__hash__", "__eq__", "__ne__"}
_COMPARISONS = {"__lt__", "__le__", "__gt__", "__ge__"}


@pytest.mark.parametrize("name", sorted(_manifest_bindings()))
def test_stub_signature_matches_runtime(name):
    """Every manifest symbol: the stub's signatures (names, kinds, defaults) equal the runtime's."""
    setup_survival_import()
    core = importlib.import_module("survival._survival")
    if not hasattr(core, name):
        assert name in _feature_bindings()["ml"]
        pytest.skip(f"{name} needs the ml feature")
    runtime = getattr(core, name)
    node = _STUB_NODES[name]

    if not isinstance(runtime, type):
        assert isinstance(node, ast.FunctionDef), f"{name} is a function at runtime"
        assert _stub_signature(node) == _runtime_signature(runtime)
        return

    assert isinstance(node, ast.ClassDef), f"{name} is a class at runtime"
    stub_functions = [n for n in node.body if isinstance(n, ast.FunctionDef)]
    stub_properties = {
        n.name
        for n in stub_functions
        if any(isinstance(d, ast.Name) and d.id == "property" for d in n.decorator_list)
    }
    stub_setters = {
        n.name
        for n in stub_functions
        if any(isinstance(d, ast.Attribute) and d.attr == "setter" for d in n.decorator_list)
    }
    stub_methods = {n.name: n for n in stub_functions if n.name not in stub_properties}
    stub_attributes = {
        n.target.id
        for n in node.body
        if isinstance(n, ast.AnnAssign) and isinstance(n.target, ast.Name)
    }

    # constructor
    if runtime.__text_signature__ is None:
        assert "__init__" not in stub_methods, f"{name} has no constructor at runtime"
    else:
        assert "__init__" in stub_methods, f"{name} is constructible at runtime"
        assert _stub_signature(stub_methods["__init__"]) == _runtime_signature(runtime)

    # enum variants, properties and methods
    runtime_variants = set()
    runtime_properties = set()
    runtime_methods = {}
    for key, value in runtime.__dict__.items():
        if key in _SKIPPED_DUNDERS or key in _COMPARISONS or keyword.iskeyword(key):
            continue
        if isinstance(value, runtime):
            runtime_variants.add(key)
        elif type(value).__name__ == "getset_descriptor":
            runtime_properties.add(key)
        elif key.startswith("__") and key.endswith("__"):
            continue
        elif type(value).__name__ in {
            "method_descriptor",
            "builtin_function_or_method",
        } or isinstance(value, staticmethod | classmethod):
            runtime_methods[key] = value
    assert stub_attributes == runtime_variants, f"{name}: enum variants"
    assert stub_properties == runtime_properties, f"{name}: properties"
    assert stub_setters <= stub_properties, f"{name}: setters must be properties"
    plain_methods = {k for k in stub_methods if k not in stub_properties and not k.startswith("__")}
    assert plain_methods == set(runtime_methods), f"{name}: methods"
    for method, value in runtime_methods.items():
        stub_node = stub_methods[method]
        decorators = {d.id for d in stub_node.decorator_list if isinstance(d, ast.Name)}
        target = value.__func__ if isinstance(value, staticmethod | classmethod) else value
        if isinstance(value, staticmethod):
            assert "staticmethod" in decorators, f"{name}.{method}"
        elif isinstance(value, classmethod):
            assert "classmethod" in decorators, f"{name}.{method}"
        assert _stub_signature(stub_node) == _runtime_signature(target), f"{name}.{method}"


# ---------------------------------------------------------------------------------------------
# Package root, sklearn stub, README
# ---------------------------------------------------------------------------------------------


def test_init_stub_mirrors_root_export_lists():
    lists = _root_export_lists()
    tree = ast.parse((PACKAGE_ROOT / "__init__.pyi").read_text())
    module_imports: set[str] = set()
    r_imports: set[str] = set()
    sklearn_imports: set[str] = set()
    for node in tree.body:
        if not isinstance(node, ast.ImportFrom) or node.level != 1:
            continue
        names = {alias.name for alias in node.names}
        if node.module is None:
            module_imports |= names
        elif node.module == "r":
            r_imports |= names
        elif node.module == "sklearn_compat":
            sklearn_imports |= names
        else:
            raise AssertionError(f"unexpected import from {node.module} in __init__.pyi")

    assert module_imports == set(lists["_PUBLIC_MODULES"])
    assert r_imports == set(lists["_R_EXPORTS"])
    assert sklearn_imports == set(lists["_SKLEARN_EXPORTS"])


def test_root_exports_resolve_to_their_home_modules():
    setup_survival_import()
    survival = importlib.import_module("survival")
    lists = _root_export_lists()
    r_module = importlib.import_module("survival.r")
    sklearn_compat = importlib.import_module("survival.sklearn_compat")

    assert set(survival.__all__) == _top_level_names() - MODULE_METADATA_NAMES
    assert set(lists["_R_EXPORTS"]) <= set(r_module.__all__)
    for name in lists["_R_EXPORTS"]:
        assert getattr(survival, name) is getattr(r_module, name), name
    for name in lists["_SKLEARN_EXPORTS"]:
        assert getattr(survival, name) is getattr(sklearn_compat, name), name
    for name in lists["_PUBLIC_MODULES"]:
        assert getattr(survival, name) is sys.modules[f"survival.{name}"], name
    assert survival.survreg is not survival.regression.survreg
    assert survival.neardate is not survival.data_prep.neardate
    assert survival.is_surv(survival.Surv([1.0])) is True
    assert survival.is_surv([1.0]) is False

    with pytest.raises(AttributeError, match="has no attribute 'coxph_fit'"):
        _ = survival.coxph_fit
    assert not hasattr(survival, "__deprecated_root_exports__")


def test_sklearn_compat_stub_tracks_public_exports():
    setup_survival_import()
    sklearn_compat = importlib.import_module("survival.sklearn_compat")
    stub_path = PACKAGE_ROOT / "sklearn_compat.pyi"

    assert _pyi_top_level_names(stub_path) == set(sklearn_compat.__all__)
    assert _pyi_function_arg_names(stub_path, "iter_chunks") == ["X", "batch_size"]
    assert _pyi_function_arg_names(stub_path, "predict_large_dataset") == [
        "estimator",
        "X",
        "batch_size",
        "output_file",
        "verbose",
    ]
    assert _pyi_function_arg_names(stub_path, "survival_curves_to_disk") == [
        "estimator",
        "X",
        "output_file",
        "batch_size",
        "verbose",
    ]
    assert (
        _pyi_function_return(stub_path, "survival_curves_to_disk")
        == "tuple[NDArray[np.float64], np.memmap]"
    )
    for method_name, expected in {
        "predict_batched": ["self", "X", "batch_size"],
        "predict_survival_batched": ["self", "X", "batch_size"],
        "predict_to_array": ["self", "X", "batch_size", "out"],
    }.items():
        assert _pyi_class_method_arg_names(stub_path, "StreamingMixin", method_name) == expected
    for estimator in ("CoxPHEstimator", "AFTEstimator"):
        init_args = _pyi_class_method_arg_names(stub_path, estimator, "__init__")
        runtime_args = list(
            inspect.signature(getattr(sklearn_compat, estimator).__init__).parameters
        )
        assert init_args == runtime_args, estimator


def test_readme_python_examples_reference_public_symbols():
    manifest = set(_manifest_bindings())
    module_exports = _binding_names_by_module()
    top_level_names = _top_level_names()
    sklearn_names = _sklearn_names()
    module_names = set(module_exports) | {"sklearn_compat", "_survival"}
    missing: list[tuple[str, str]] = []

    for index, block in enumerate(_readme_python_blocks(), start=1):
        tree = ast.parse(block, filename=f"README.md python block {index}")
        aliases: dict[str, set[str]] = {}

        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom):
                module = node.module or ""
                if module == "survival":
                    for alias in node.names:
                        name = alias.name
                        if name not in top_level_names:
                            missing.append((f"README.md python block {index}", name))
                            continue
                        if name in module_exports:
                            aliases[alias.asname or name] = (
                                module_exports[name] | MODULE_METADATA_NAMES
                            )
                elif module.startswith("survival."):
                    submodule = module.removeprefix("survival.")
                    if submodule not in module_names:
                        missing.append((f"README.md python block {index}", module))
                        continue
                    surface = (
                        manifest
                        if submodule == "_survival"
                        else sklearn_names
                        if submodule == "sklearn_compat"
                        else module_exports[submodule]
                    )
                    for alias in node.names:
                        if alias.name == "*":
                            continue
                        if alias.name not in surface:
                            missing.append(
                                (f"README.md python block {index}", f"{module}.{alias.name}")
                            )
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    name = alias.name
                    if name == "survival":
                        aliases[alias.asname or "survival"] = top_level_names
                    elif name.startswith("survival."):
                        submodule = name.removeprefix("survival.")
                        if submodule not in module_names:
                            missing.append((f"README.md python block {index}", name))

        for node in ast.walk(tree):
            if not isinstance(node, ast.Attribute) or not isinstance(node.value, ast.Name):
                continue
            surface = aliases.get(node.value.id)
            if surface is not None and node.attr not in surface:
                missing.append((f"README.md python block {index}", f"{node.value.id}.{node.attr}"))

    assert missing == [], _format_missing(missing)


def _readme_low_level_blocks() -> list[tuple[int, str]]:
    """README blocks that use only the domain modules (the R-style facade has its own tests)."""
    lists = _root_export_lists()
    module_names = set(lists["_PUBLIC_MODULES"]) - {"r", "r_api"}
    blocks = []
    for index, block in enumerate(_readme_python_blocks(), start=1):
        tree = ast.parse(block)
        imported: set[str] = set()
        low_level = True
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom) and node.module == "survival":
                imported |= {alias.name for alias in node.names}
            elif isinstance(node, ast.ImportFrom) and (node.module or "").startswith("survival."):
                imported.add(node.module.removeprefix("survival."))
            elif isinstance(node, ast.Import):
                low_level = False
        if low_level and imported and imported <= module_names:
            blocks.append((index, block))
    return blocks


def test_readme_low_level_examples_run(capsys):
    blocks = _readme_low_level_blocks()
    assert len(blocks) >= 8
    for index, block in blocks:
        namespace: dict[str, object] = {"__name__": f"readme_block_{index}"}
        exec(compile(block, f"README.md python block {index}", "exec"), namespace)  # noqa: S102
    capsys.readouterr()


def test_runtime_extension_exports_manifest_symbols():
    setup_survival_import()
    core = importlib.import_module("survival._survival")
    expected = set(_manifest_bindings())
    if not _has_ml_bindings(core):
        expected -= set(_feature_bindings()["ml"])

    missing = [name for name in sorted(expected) if not hasattr(core, name)]

    assert missing == []


def test_feature_gated_module_exports_follow_runtime_features():
    setup_survival_import()
    core = importlib.import_module("survival._survival")
    survival = importlib.import_module("survival")

    if _has_ml_bindings(core):
        assert "deep_surv" in survival.ml.__all__
        return

    assert "deep_surv" not in survival.ml.__all__
    try:
        _ = survival.ml.deep_surv
    except AttributeError as exc:
        assert "built without the 'ml' feature" in str(exc)
    else:
        raise AssertionError("deep_surv should be unavailable without the ml feature")


def test_package_root_lazy_loads_domain_modules():
    _remove_survival_modules()
    survival = setup_survival_import()

    assert "survival._survival" not in sys.modules
    assert "survival._binding_utils" not in sys.modules
    assert "survival.regression" not in sys.modules
    assert "regression" not in vars(survival)

    regression = survival.regression

    assert sys.modules["survival.regression"] is regression
    assert "regression" in vars(survival)
    assert regression.coxph_fit is sys.modules["survival._survival"].coxph_fit

    assert survival._survival is sys.modules["survival._survival"]
    assert "_survival" in vars(survival)


def test_package_root_lazy_loads_r_exports():
    _remove_survival_modules()
    survival = setup_survival_import()

    assert "survival.r" not in sys.modules
    assert "r" not in vars(survival)
    assert "Surv" not in vars(survival)

    assert survival.Surv is survival.r.Surv
    assert "survival.r" in sys.modules
    assert "r" in vars(survival)
    assert "Surv" in vars(survival)
    assert survival.r_api.Surv is survival.Surv


def test_r_api_stub_tracks_surv_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "self",
        "type",
        "origin",
        "time",
        "time1",
        "time2",
        "event",
        "status",
        "start",
        "stop",
    ]
    runtime_params = inspect.signature(survival.r_api.Surv.__init__).parameters
    assert [
        name
        for name, parameter in runtime_params.items()
        if parameter.kind is not inspect.Parameter.VAR_POSITIONAL
    ] == expected
    assert runtime_params["args"].kind is inspect.Parameter.VAR_POSITIONAL
    assert _pyi_class_method_arg_names(stub_path, "Surv", "__init__") == expected


def test_r_api_stub_tracks_dataclass_public_fields():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    for class_name in sorted(_pyi_top_level_names(stub_path)):
        runtime_class = getattr(survival.r_api, class_name, None)
        if not isinstance(runtime_class, type) or not dataclasses.is_dataclass(runtime_class):
            continue
        runtime_fields = set(runtime_class.__dataclass_fields__)
        assert _pyi_class_annotation_names(stub_path, class_name) == runtime_fields


def test_r_api_stub_tracks_concordance_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "response",
        "data",
        "scores",
        "risk_scores",
        "weights",
        "subset",
        "na_action",
        "cluster",
        "ymin",
        "ymax",
        "timewt",
        "influence",
        "ranks",
        "reverse",
        "timefix",
        "keepstrata",
    ]
    runtime_params = inspect.signature(survival.r_api.concordance).parameters
    assert [
        name
        for name, parameter in runtime_params.items()
        if parameter.kind is not inspect.Parameter.VAR_KEYWORD
    ] == expected
    assert runtime_params["kwargs"].kind is inspect.Parameter.VAR_KEYWORD
    assert _pyi_function_arg_names(stub_path, "concordance") == expected
    assert _pyi_function_kwarg_name(stub_path, "concordance") == "kwargs"


def test_r_api_stub_tracks_model_generic_public_signatures():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected_by_name = {
        "coef": ["fit"],
        "coef_names": ["fit", "complete"],
        "confint": ["fit", "parm", "level"],
        "vcov": ["fit", "complete"],
        "loglik": ["fit"],
        "model_formula": ["fit"],
        "model_summary": ["fit"],
        "model_weights": ["fit"],
        "nobs": ["fit"],
        "degrees_freedom": ["fit"],
        "df_residual": ["fit"],
        "aic": ["fit", "k"],
        "bic": ["fit"],
        "brier": ["fit", "times", "newdata", "ties", "detail", "timefix", "efron"],
        "royston": ["fit", "newdata", "ties", "adjust"],
        "extract_aic": ["fit", "scale", "k"],
        "model_frame": ["fit"],
        "model_matrix": ["fit"],
        "as_data_frame": ["result"],
        "fitted": [
            "fit",
            "type",
            "centered",
            "terms",
            "collapse",
            "reference",
            "se_fit",
            "times",
            "p",
            "quantiles",
        ],
    }
    for name, expected in expected_by_name.items():
        runtime_params = inspect.signature(getattr(survival.r_api, name)).parameters
        assert [
            param_name
            for param_name, parameter in runtime_params.items()
            if parameter.kind is not inspect.Parameter.VAR_KEYWORD
        ] == expected
        assert _pyi_function_arg_names(stub_path, name) == expected
        if name == "fitted":
            assert _pyi_function_kwarg_name(stub_path, name) == "kwargs"


def test_r_api_stub_tracks_survfit_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "response",
        "data",
        "group",
        "newdata",
        "weights",
        "subset",
        "na_action",
        "conf_level",
        "conf_int",
        "conf_type",
        "se_fit",
        "start_time",
        "time0",
        "reverse",
        "censor",
        "type",
        "stype",
        "ctype",
        "id",
        "cluster",
        "robust",
        "istate",
        "etype",
        "p0",
        "model",
        "error",
        "entry",
        "timefix",
    ]
    runtime_params = inspect.signature(survival.r_api.survfit).parameters
    assert [
        name
        for name, parameter in runtime_params.items()
        if parameter.kind is not inspect.Parameter.VAR_KEYWORD
    ] == expected
    assert runtime_params["kwargs"].kind is inspect.Parameter.VAR_KEYWORD
    assert _pyi_function_arg_names(stub_path, "survfit") == expected
    tree = ast.parse(stub_path.read_text(), filename=str(stub_path))
    survfit_node = next(
        node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == "survfit"
    )
    assert survfit_node.args.kwarg is not None
    assert survfit_node.args.kwarg.arg == "kwargs"

    survfit0_params = inspect.signature(survival.r_api.survfit0).parameters
    assert list(survfit0_params) == ["x", "args", "kwargs"]
    assert survfit0_params["args"].kind is inspect.Parameter.VAR_POSITIONAL
    assert survfit0_params["kwargs"].kind is inspect.Parameter.VAR_KEYWORD
    assert _pyi_function_arg_names(stub_path, "survfit0") == ["x"]
    tree = ast.parse(stub_path.read_text(), filename=str(stub_path))
    survfit0_node = next(
        node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == "survfit0"
    )
    assert survfit0_node.args.vararg is not None
    assert survfit0_node.args.vararg.arg == "args"
    assert survfit0_node.args.kwarg is not None
    assert survfit0_node.args.kwarg.arg == "kwargs"


def test_r_api_stub_tracks_predict_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "fit",
        "newdata",
        "type",
        "centered",
        "terms",
        "collapse",
        "reference",
        "se_fit",
        "times",
        "p",
        "quantiles",
    ]
    runtime_params = inspect.signature(survival.r_api.predict).parameters
    assert [
        name
        for name, parameter in runtime_params.items()
        if parameter.kind is not inspect.Parameter.VAR_KEYWORD
    ] == expected
    assert runtime_params["kwargs"].kind is inspect.Parameter.VAR_KEYWORD
    assert _pyi_function_arg_names(stub_path, "predict") == expected
    tree = ast.parse(stub_path.read_text(), filename=str(stub_path))
    predict_node = next(
        node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == "predict"
    )
    assert predict_node.args.kwarg is not None
    assert predict_node.args.kwarg.arg == "kwargs"


def test_r_api_stub_tracks_residuals_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "fit",
        "type",
        "terms",
        "collapse",
        "weighted",
        "rsigma",
    ]
    runtime_params = inspect.signature(survival.r_api.residuals).parameters
    assert list(runtime_params) == expected
    assert _pyi_function_arg_names(stub_path, "residuals") == expected


def test_r_api_stub_tracks_aeqsurv_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = ["x", "tolerance"]
    assert list(inspect.signature(survival.r_api.aeqSurv).parameters) == expected
    assert _pyi_function_arg_names(stub_path, "aeqSurv") == expected


def test_r_api_stub_tracks_surv_utility_public_signatures():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected_by_name = {
        "is_na_surv": ["x"],
        "format_surv": ["x"],
        "is_ratetable": ["x", "has_rates", "has_dims", "verbose"],
        "ratetableDate": ["x", "month", "day", "origin_year"],
        "survexp_us": [],
        "survexp_mn": [],
        "survexp_usr": [],
    }
    for name, expected in expected_by_name.items():
        assert list(inspect.signature(getattr(survival.r_api, name)).parameters) == expected
        assert _pyi_function_arg_names(stub_path, name) == expected
    assert (
        inspect.signature(survival.r_api.ratetableDate).parameters["origin_year"].kind
        is inspect.Parameter.KEYWORD_ONLY
    )


def test_r_api_stub_tracks_survexp_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "time",
        "age",
        "year",
        "ratetable",
        "sex",
        "times",
        "method",
        "cohort",
        "conditional",
        "scale",
        "se_fit",
    ]
    runtime_params = inspect.signature(survival.r_api.survexp).parameters
    assert list(runtime_params) == expected
    assert runtime_params["cohort"].kind is inspect.Parameter.KEYWORD_ONLY
    assert runtime_params["conditional"].kind is inspect.Parameter.KEYWORD_ONLY
    assert runtime_params["scale"].kind is inspect.Parameter.KEYWORD_ONLY
    assert runtime_params["se_fit"].kind is inspect.Parameter.KEYWORD_ONLY
    assert _pyi_function_arg_names(stub_path, "survexp") == expected

    expected_individual = ["time", "age", "year", "ratetable", "sex"]
    assert (
        list(inspect.signature(survival.r_api.survexp_individual).parameters) == expected_individual
    )
    assert _pyi_function_arg_names(stub_path, "survexp_individual") == expected_individual


def test_r_api_stub_tracks_cipoisson_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = ["k", "time", "p", "method"]
    assert list(inspect.signature(survival.r_api.cipoisson).parameters) == expected
    assert _pyi_function_arg_names(stub_path, "cipoisson") == expected


def test_r_api_stub_tracks_bounded_link_public_signatures():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = ["x", "edge"]
    for name in ["blogit", "bprobit", "bcloglog", "blog"]:
        assert list(inspect.signature(getattr(survival.r_api, name)).parameters) == expected
        assert _pyi_function_arg_names(stub_path, name) == expected


def test_r_api_stub_tracks_pyears_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "response",
        "data",
        "time",
        "start",
        "stop",
        "event",
        "group",
        "weights",
        "subset",
        "na_action",
        "scale",
        "data_frame",
    ]
    runtime_params = inspect.signature(survival.r_api.pyears).parameters
    assert list(runtime_params) == expected
    for name in expected[2:]:
        assert runtime_params[name].kind is inspect.Parameter.KEYWORD_ONLY
    assert _pyi_function_arg_names(stub_path, "pyears") == expected


def test_r_api_stub_tracks_finegray_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "formula",
        "data",
        "weights",
        "subset",
        "na_action",
        "etype",
        "prefix",
        "count",
        "id",
        "timefix",
        "kwargs",
    ]
    runtime_params = inspect.signature(survival.r_api.finegray).parameters
    assert list(runtime_params) == expected
    for name in expected[2:-1]:
        assert runtime_params[name].kind is inspect.Parameter.KEYWORD_ONLY
    assert _pyi_function_arg_names(stub_path, "finegray") == expected[:-1]
    assert _pyi_function_kwarg_name(stub_path, "finegray") == "kwargs"


def test_r_api_stub_tracks_tmerge_public_surface():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "data1",
        "data2",
        "id",
        "tstart",
        "tstop",
        "options",
        "operations",
        "metadata",
        "updates",
    ]
    runtime_params = inspect.signature(survival.r_api.tmerge).parameters
    assert list(runtime_params) == expected
    for name in expected[3:-1]:
        assert runtime_params[name].kind is inspect.Parameter.KEYWORD_ONLY
    assert runtime_params["updates"].kind is inspect.Parameter.VAR_KEYWORD
    assert _pyi_function_arg_names(stub_path, "tmerge") == expected[:-1]
    assert _pyi_function_kwarg_name(stub_path, "tmerge") == "updates"
    assert _pyi_class_annotation_names(stub_path, "TMergeOperation") == {
        "kind",
        "time",
        "value",
        "default",
        "censor",
    }
    assert _pyi_class_annotation_names(stub_path, "TMergeFrame") == {
        "columns",
        "tname",
        "tevent",
        "tdcvar",
        "tcount",
    }


def test_r_api_stub_tracks_survobrien_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = ["time", "status", "covariate", "strata", "data", "subset", "na_action", "transform"]
    runtime_params = inspect.signature(survival.r_api.survobrien).parameters
    assert list(runtime_params) == expected
    for name in expected[4:]:
        assert runtime_params[name].kind is inspect.Parameter.KEYWORD_ONLY
    assert _pyi_function_arg_names(stub_path, "survobrien") == expected
    assert _pyi_class_annotation_names(stub_path, "SurvObrienResult") == {
        "statistic",
        "p_value",
        "df",
        "scores",
        "score_sum",
        "expected",
        "variance",
    }


def test_r_api_stub_tracks_survsplit_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = ["response", "data", "cut", "start", "end", "event", "episode", "id", "zero"]
    runtime_params = inspect.signature(survival.r_api.survSplit).parameters
    assert list(runtime_params) == expected
    assert runtime_params["cut"].kind is inspect.Parameter.KEYWORD_ONLY
    assert _pyi_function_arg_names(stub_path, "survSplit") == expected


def test_r_api_stub_tracks_survcondense_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "formula",
        "data",
        "subset",
        "weights",
        "na_action",
        "id",
        "start",
        "end",
        "event",
    ]
    runtime_params = inspect.signature(survival.r_api.survcondense).parameters
    assert [
        name
        for name, parameter in runtime_params.items()
        if parameter.kind is not inspect.Parameter.VAR_KEYWORD
    ] == expected
    assert runtime_params["id"].kind is inspect.Parameter.KEYWORD_ONLY
    assert runtime_params["kwargs"].kind is inspect.Parameter.VAR_KEYWORD
    assert _pyi_function_arg_names(stub_path, "survcondense") == expected
    assert _pyi_function_kwarg_name(stub_path, "survcondense") == "kwargs"


def test_r_api_stub_tracks_survconcordance_public_signatures():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = ["formula", "data", "weights", "subset", "na_action"]
    runtime_params = inspect.signature(survival.r_api.survConcordance).parameters
    assert [
        name
        for name, parameter in runtime_params.items()
        if parameter.kind is not inspect.Parameter.VAR_KEYWORD
    ] == expected
    assert runtime_params["kwargs"].kind is inspect.Parameter.VAR_KEYWORD
    assert _pyi_function_arg_names(stub_path, "survConcordance") == expected
    assert _pyi_function_kwarg_name(stub_path, "survConcordance") == "kwargs"

    fit_expected = ["y", "x", "strata", "weight"]
    fit_params = inspect.signature(survival.r_api.survConcordance_fit).parameters
    assert [
        name
        for name, parameter in fit_params.items()
        if parameter.kind is not inspect.Parameter.VAR_KEYWORD
    ] == fit_expected
    assert fit_params["kwargs"].kind is inspect.Parameter.VAR_KEYWORD
    assert _pyi_function_arg_names(stub_path, "survConcordance_fit") == fit_expected
    assert _pyi_function_kwarg_name(stub_path, "survConcordance_fit") == "kwargs"


def test_r_api_stub_tracks_survcheck_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "response",
        "data",
        "subset",
        "na_action",
        "id",
        "istate",
        "istate0",
        "timefix",
        "time1",
        "time2",
        "status",
    ]
    runtime_params = inspect.signature(survival.r_api.survcheck).parameters
    assert [
        name
        for name, parameter in runtime_params.items()
        if parameter.kind is not inspect.Parameter.VAR_KEYWORD
    ] == expected
    assert runtime_params["kwargs"].kind is inspect.Parameter.VAR_KEYWORD
    assert _pyi_function_arg_names(stub_path, "survcheck") == expected
    assert _pyi_function_kwarg_name(stub_path, "survcheck") == "kwargs"


def test_r_api_stub_tracks_rttright_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "response",
        "status",
        "weights",
        "data",
        "subset",
        "na_action",
        "times",
        "id",
        "timefix",
        "renorm",
    ]
    runtime_params = inspect.signature(survival.r_api.rttright).parameters
    assert [
        name
        for name, parameter in runtime_params.items()
        if parameter.kind is not inspect.Parameter.VAR_KEYWORD
    ] == expected
    assert runtime_params["data"].kind is inspect.Parameter.KEYWORD_ONLY
    assert runtime_params["kwargs"].kind is inspect.Parameter.VAR_KEYWORD
    assert _pyi_function_arg_names(stub_path, "rttright") == expected
    assert _pyi_function_kwarg_name(stub_path, "rttright") == "kwargs"


def test_r_api_stub_tracks_pseudo_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "fit",
        "status",
        "eval_times",
        "type_",
        "times",
        "type",
        "collapse",
        "data_frame",
        "time",
    ]
    runtime_params = inspect.signature(survival.r_api.pseudo).parameters
    assert [
        name
        for name, parameter in runtime_params.items()
        if parameter.kind is not inspect.Parameter.VAR_KEYWORD
    ] == expected
    assert runtime_params["times"].kind is inspect.Parameter.KEYWORD_ONLY
    assert runtime_params["kwargs"].kind is inspect.Parameter.VAR_KEYWORD
    assert _pyi_function_arg_names(stub_path, "pseudo") == expected
    assert _pyi_function_kwarg_name(stub_path, "pseudo") == "kwargs"


def test_r_api_stub_tracks_strata_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"
    tree = ast.parse(stub_path.read_text(), filename=str(stub_path))
    node = next(
        node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name == "strata"
    )

    runtime_params = inspect.signature(survival.r_api.strata).parameters
    assert runtime_params["variables"].kind is inspect.Parameter.VAR_POSITIONAL
    assert list(_pyi_function_arg_names(stub_path, "strata")) == [
        "na_group",
        "shortlabel",
        "sep",
        "labels",
    ]
    assert node.args.vararg is not None
    assert node.args.vararg.arg == "variables"


def test_r_api_stub_tracks_survreg_distribution_helper_signatures():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected_by_name = {
        "dsurvreg": ["x", "mean", "scale", "distribution", "parms"],
        "psurvreg": ["q", "mean", "scale", "distribution", "parms"],
        "qsurvreg": ["p", "mean", "scale", "distribution", "parms"],
        "rsurvreg": ["n", "mean", "scale", "distribution", "parms"],
    }
    for name, expected in expected_by_name.items():
        assert list(inspect.signature(getattr(survival.r_api, name)).parameters) == expected
        assert _pyi_function_arg_names(stub_path, name) == expected


def test_r_api_stub_tracks_survdiff_public_signature():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected = [
        "response",
        "data",
        "group",
        "subset",
        "na_action",
        "rho",
        "timefix",
    ]
    runtime_params = inspect.signature(survival.r_api.survdiff).parameters
    assert [
        name
        for name, parameter in runtime_params.items()
        if parameter.kind is not inspect.Parameter.VAR_KEYWORD
    ] == expected
    assert runtime_params["kwargs"].kind is inspect.Parameter.VAR_KEYWORD
    assert _pyi_function_arg_names(stub_path, "survdiff") == expected
    assert _pyi_function_kwarg_name(stub_path, "survdiff") == "kwargs"


def test_r_api_stub_tracks_fit_control_public_signatures():
    setup_survival_import()
    survival = importlib.import_module("survival")
    stub_path = PACKAGE_ROOT / "r_api.pyi"

    expected_by_name = {
        "clogit": [
            "formula",
            "data",
            "weights",
            "subset",
            "na_action",
            "method",
        ],
        "coxph": [
            "response",
            "data",
            "x",
            "weights",
            "offset",
            "strata",
            "cluster",
            "subset",
            "na_action",
            "init",
            "initial_beta",
            "max_iter",
            "eps",
            "toler",
            "method",
            "ties",
            "robust",
            "model",
            "y",
            "tt",
            "id",
            "istate",
            "statedata",
            "singular_ok",
            "nocenter",
            "control",
        ],
        "survreg": [
            "response",
            "data",
            "x",
            "time",
            "time2",
            "status",
            "covariates",
            "weights",
            "offset",
            "offsets",
            "init",
            "initial",
            "initial_beta",
            "strata",
            "subset",
            "na_action",
            "dist",
            "distribution",
            "scale",
            "parms",
            "model",
            "y",
            "robust",
            "cluster",
            "score",
            "max_iter",
            "eps",
            "tol_chol",
            "control",
        ],
    }
    for name, expected in expected_by_name.items():
        runtime_params = inspect.signature(getattr(survival.r_api, name)).parameters
        assert [
            param_name
            for param_name, parameter in runtime_params.items()
            if parameter.kind is not inspect.Parameter.VAR_KEYWORD
        ] == expected
        assert runtime_params["kwargs"].kind is inspect.Parameter.VAR_KEYWORD
        assert _pyi_function_arg_names(stub_path, name) == expected
        assert _pyi_function_kwarg_name(stub_path, name) == "kwargs"


def test_package_root_version_matches_project_metadata():
    setup_survival_import()
    survival = importlib.import_module("survival")

    pyproject = tomllib.loads((ROOT / "pyproject.toml").read_text())
    cargo_version_match = re.search(
        r'(?m)^version\s*=\s*"([^"]+)"',
        (ROOT / "Cargo.toml").read_text(),
    )

    assert cargo_version_match is not None
    assert survival.__version__ == pyproject["project"]["version"]
    assert survival.__version__ == cargo_version_match.group(1)
    assert "__version__" in dir(survival)


def test_package_root_lazy_loads_sklearn_exports():
    _remove_survival_modules()
    survival = setup_survival_import()

    assert "CoxPHEstimator" in survival.__all__
    assert "CoxPHEstimator" not in vars(survival)

    sklearn_compat = importlib.import_module("survival.sklearn_compat")

    assert "survival._sklearn_cox" not in sys.modules
    assert "survival._sklearn_aft" not in sys.modules
    assert "survival._sklearn_deep" not in sys.modules
    assert "survival._sklearn_ensemble" not in sys.modules

    assert survival.CoxPHEstimator is sklearn_compat.CoxPHEstimator
    assert survival.CoxPHEstimator is sklearn_compat.CoxPHEstimator
    assert "survival._sklearn_cox" in sys.modules
    assert "survival._sklearn_aft" not in sys.modules
    assert "survival._sklearn_deep" not in sys.modules
    assert "survival._sklearn_ensemble" not in sys.modules


def test_package_root_lazy_loads_streaming_sklearn_exports():
    _remove_survival_modules()
    survival = setup_survival_import()

    assert "StreamingMixin" in survival.__all__
    assert "StreamingMixin" not in vars(survival)

    assert (
        survival.StreamingMixin is importlib.import_module("survival.sklearn_compat").StreamingMixin
    )
    assert "survival._sklearn_streaming" in sys.modules
    assert "survival._sklearn_cox" not in sys.modules
    assert "survival._sklearn_aft" not in sys.modules
    assert "survival._sklearn_deep" not in sys.modules
    assert "survival._sklearn_ensemble" not in sys.modules

    streaming_cox = survival.StreamingCoxPHEstimator

    assert "survival._sklearn_streaming_cox" in sys.modules
    assert "survival._sklearn_cox" in sys.modules
    assert "survival._sklearn_aft" not in sys.modules
    assert "survival._sklearn_deep" not in sys.modules
    assert "survival._sklearn_ensemble" not in sys.modules
    assert issubclass(
        streaming_cox,
        importlib.import_module("survival._sklearn_cox").CoxPHEstimator,
    )
