"""Model-matrix formula algebra independently generated by R's stats package."""

import importlib
import json
import re
from pathlib import Path

import numpy as np
import pytest

from .helpers import setup_survival_import
from .r_fixture_support import RFactor

survival = setup_survival_import()
formula = importlib.import_module("survival.r._formula")
fit_module = importlib.import_module("survival.r._fit")
REFERENCE = json.loads(
    (Path(__file__).parent / "fixtures/formula_algebra_reference.json").read_text()
)
DATA = dict(REFERENCE["data"])
for name, levels in REFERENCE["factor_levels"].items():
    DATA[name] = RFactor(DATA[name], levels)


@pytest.mark.parametrize("case", REFERENCE["cases"], ids=lambda case: case["formula"])
@pytest.mark.parametrize("as_array", [False, True], ids=["rows", "array"])
@pytest.mark.parametrize("columns", ["lists", "numpy", "pandas"])
def test_formula_design_matches_r(case, as_array, columns):
    data = dict(DATA)
    if columns != "lists":
        pd = pytest.importorskip("pandas") if columns == "pandas" else None
        for name, values in DATA.items():
            if name not in REFERENCE["factor_levels"]:
                data[name] = np.asarray(values) if pd is None else pd.Series(values)
    if "error" in case:
        with pytest.raises(ValueError, match=re.escape(case["error"])):
            formula.model_frame(case["formula"], data)
        return
    frame = formula.model_frame(case["formula"], data)
    design = fit_module._r_factor_design(
        frame.data,
        formula._fit_formula_design(
            frame.data, frame.spec, frame.terms, frame.n, include_intercept=True
        ),
    )
    assert int(design.intercept) == case["intercept"]
    assert list(dict(formula._model_variables(frame))) == case["variables"]
    assert [formula._design_term_name(term) for term in design.covariates] == case["terms"]
    columns = (["(Intercept)"] if design.intercept else []) + [
        name for term in design.covariates for name in formula._design_term_output_names(term)
    ]
    assign = ([0] if design.intercept else []) + [
        code
        for term, code in zip(design.covariates, design.term_assignments, strict=True)
        for _ in formula._design_term_output_names(term)
    ]
    assert columns == case["columns"]
    assert assign == case["assign"]
    make_design = formula._design_array_from_spec if as_array else formula._design_rows_from_spec
    actual = make_design(data, design, frame.n)
    if as_array:
        assert actual.dtype == np.dtype("float64")
        assert actual.flags.c_contiguous
        assert actual.flags.owndata
        assert actual.shape == (frame.n, len(columns))
    else:
        assert isinstance(actual, list)
    np.testing.assert_allclose(
        actual,
        case["x"],
        rtol=1e-14,
        atol=1e-14,
    )
